# Generated by Django 5.1.15 on 2026-06-03 04:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role', models.CharField(choices=[('sales', '宴会销售'), ('floor_supervisor', '厅面主管'), ('kitchen_coordinator', '后厨统筹')], max_length=50, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='菜品名称')),
                ('category', models.CharField(max_length=50, verbose_name='菜品分类')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
            },
        ),
        migrations.CreateModel(
            name='BanquetBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(max_length=50, unique=True, verbose_name='预订单号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('banquet_type', models.CharField(max_length=100, verbose_name='宴会类型')),
                ('banquet_date', models.DateField(verbose_name='宴会日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('venue', models.CharField(max_length=100, verbose_name='场地')),
                ('expected_guests', models.IntegerField(verbose_name='预计人数')),
                ('table_count', models.IntegerField(verbose_name='桌数')),
                ('budget_per_table', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每桌预算')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交待确认'), ('menu_confirmed', '菜单已确认'), ('kitchen_received', '后厨已接收'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('floor_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_handled', to='banquet.employee', verbose_name='厅面主管')),
                ('kitchen_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_kitchen', to='banquet.employee', verbose_name='后厨统筹')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_created', to='banquet.employee', verbose_name='销售人员')),
            ],
            options={
                'verbose_name': '宴会预订',
                'verbose_name_plural': '宴会预订',
                'ordering': ['-banquet_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('from_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('submitted', '已提交待确认'), ('menu_confirmed', '菜单已确认'), ('kitchen_received', '后厨已接收'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, choices=[('draft', '草稿'), ('submitted', '已提交待确认'), ('menu_confirmed', '菜单已确认'), ('kitchen_received', '后厨已接收'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=30, verbose_name='新状态')),
                ('operator_role', models.CharField(choices=[('sales', '宴会销售'), ('floor_supervisor', '厅面主管'), ('kitchen_coordinator', '后厨统筹')], max_length=50, verbose_name='操作人角色')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='banquet.banquetbooking', verbose_name='宴会预订')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='banquet.employee', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MenuConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('special_requirements', models.TextField(blank=True, verbose_name='特殊要求')),
                ('wine_arrangement', models.TextField(blank=True, verbose_name='酒水安排')),
                ('table_layout', models.TextField(blank=True, verbose_name='台型布置')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('customer_signed', models.BooleanField(default=False, verbose_name='客户已签字')),
                ('customer_signature', models.TextField(blank=True, verbose_name='客户签字')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_confirmation', to='banquet.banquetbooking', verbose_name='宴会预订')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_confirmations', to='banquet.employee', verbose_name='确认人')),
            ],
            options={
                'verbose_name': '菜单确认',
                'verbose_name_plural': '菜单确认',
            },
        ),
        migrations.CreateModel(
            name='MenuConfirmationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('remarks', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('menu_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banquet.menuconfirmation')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banquet.menuitem')),
            ],
            options={
                'verbose_name': '菜单确认明细',
                'verbose_name_plural': '菜单确认明细',
            },
        ),
        migrations.AddField(
            model_name='menuconfirmation',
            name='menu_items',
            field=models.ManyToManyField(through='banquet.MenuConfirmationItem', to='banquet.menuitem', verbose_name='菜单菜品'),
        ),
    ]
