# Generated by Django 4.2.30 on 2026-06-10 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('complaint', '投诉登记'), ('analysis', '批次分析'), ('recipe', '配方单'), ('feeding', '投料记录')], max_length=30, verbose_name='模块')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('approve', '审核'), ('review', '复核'), ('resolve', '解决')], max_length=20, verbose_name='操作类型')),
                ('object_id', models.IntegerField(verbose_name='对象ID')),
                ('object_code', models.CharField(max_length=50, verbose_name='对象编号')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('details', models.JSONField(verbose_name='操作详情')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='错误码')),
                ('description', models.CharField(max_length=200, verbose_name='错误描述')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='解决方案')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
            ],
            options={
                'verbose_name': '错误码',
                'verbose_name_plural': '错误码',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_code', models.CharField(max_length=50, unique=True, verbose_name='配方编号')),
                ('name', models.CharField(max_length=100, verbose_name='配方名称')),
                ('ingredients', models.JSONField(verbose_name='配料清单')),
                ('specifications', models.JSONField(verbose_name='技术规格')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审核'), ('production', '生产中'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='审核人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '配方单',
                'verbose_name_plural': '配方单',
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('feeding_data', models.JSONField(verbose_name='投料数据')),
                ('deviation', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='投料偏差')),
                ('is_deviation_exceeded', models.BooleanField(default=False, verbose_name='偏差超限')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('verified', '已验证')], default='pending', max_length=20, verbose_name='状态')),
                ('created_by', models.CharField(max_length=50, verbose_name='投料人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投料时间')),
                ('confirmed_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='确认人')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.recipe', verbose_name='配方单')),
            ],
            options={
                'verbose_name': '投料记录',
                'verbose_name_plural': '投料记录',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_code', models.CharField(max_length=50, unique=True, verbose_name='投诉编号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('contact_info', models.CharField(max_length=200, verbose_name='联系方式')),
                ('batch_number', models.CharField(max_length=50, verbose_name='涉及批次')),
                ('complaint_type', models.CharField(choices=[('weight_gain', '增重缓慢'), ('label_error', '标签错误'), ('ingredient_deviation', '投料偏差'), ('other', '其他')], max_length=30, verbose_name='投诉类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='投诉描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('analyzed', '已分析'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('created_by', models.CharField(max_length=50, verbose_name='登记人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('processed_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolved_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='解决人')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('related_feeding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint.feedingrecord', verbose_name='关联投料记录')),
            ],
            options={
                'verbose_name': '投诉登记',
                'verbose_name_plural': '投诉登记',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_code', models.CharField(max_length=50, unique=True, verbose_name='分析编号')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('analysis_data', models.JSONField(verbose_name='分析数据')),
                ('conclusion', models.TextField(verbose_name='分析结论')),
                ('result', models.CharField(choices=[('normal', '正常'), ('warning', '警告'), ('abnormal', '异常')], max_length=20, verbose_name='分析结果')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='处理建议')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('analyzing', '分析中'), ('completed', '已完成'), ('reviewed', '已复核')], default='pending', max_length=20, verbose_name='状态')),
                ('created_by', models.CharField(max_length=50, verbose_name='分析人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('reviewed_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='复核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.complaint', verbose_name='关联投诉')),
                ('feeding_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint.feedingrecord', verbose_name='投料记录')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaint.recipe', verbose_name='配方单')),
            ],
            options={
                'verbose_name': '批次分析',
                'verbose_name_plural': '批次分析',
            },
        ),
    ]
