// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/acceptance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/acceptance.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/acceptance.post').default>>>>
    }
    '/api/acceptance/:id/director': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/acceptance/[id]/director.post').default>>>>
    }
    '/api/acceptance/:id/engineer': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/acceptance/[id]/engineer.post').default>>>>
    }
    '/api/acceptance/:id/resubmit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/acceptance/[id]/resubmit.post').default>>>>
    }
    '/api/acceptance/:id/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/acceptance/[id]/submit.post').default>>>>
    }
    '/api/reset': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reset.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}