// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/courses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/courses.get').default>>>>
    }
    '/api/courses/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/courses/[id].get').default>>>>
    }
    '/api/courses/:id/promote-waitlist': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/courses/[id]/promote-waitlist.post').default>>>>
    }
    '/api/courses/:id/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/courses/[id]/register.post').default>>>>
    }
    '/api/courses/:id/reset-data': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/courses/[id]/reset-data.post').default>>>>
    }
    '/api/courses/:id/review': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/courses/[id]/review.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users.get').default>>>>
    }
    '/api/waitlist': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/waitlist.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.8_db0@0.3.4_ioredis@5.11.1_magicast@0.5.3_nuxt@3.21.8_@parcel+w_37c6cd8a65731976949c9e6884a80267/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}