import type { User, Warning, Exchange, OperationLog } from '@/types'
import { useWarningStore } from '@/stores/warningStore'
import { useExchangeStore } from '@/stores/exchangeStore'
import { useOperationLogStore } from '@/stores/operationLogStore'

export const SEED_USERS: User[] = [
  { id: 'u1', name: '张丽', role: 'sales' },
  { id: 'u2', name: '王刚', role: 'warehouse' },
  { id: 'u3', name: '李明', role: 'aftersales' },
]

function fmt(d: Date): string {
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

function addDays(d: Date, n: number): Date {
  const r = new Date(d)
  r.setDate(r.getDate() + n)
  return r
}

function subDays(d: Date, n: number): Date {
  return addDays(d, -n)
}

export function generateSeedData(): void {
  if (useWarningStore.getState().warnings.length > 0) return

  const now = new Date()
  const today = fmt(now)

  const warnings: Warning[] = [
    {
      id: 'w1',
      productName: '光固化树脂',
      batchNo: 'BN20250301',
      expiryDate: fmt(addDays(now, 3)),
      quantity: 50,
      unit: '支',
      storageLocation: 'A区-货架3',
      urgency: 'critical',
      status: 'pending',
      note: '近期用量较大，请尽快处理',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 1)),
      confirmedById: '',
      confirmedByName: '',
      confirmedAt: '',
      confirmNote: '',
      rejectReason: '',
      updatedAt: fmt(subDays(now, 1)),
    },
    {
      id: 'w2',
      productName: '牙科印模材',
      batchNo: 'BN20250215',
      expiryDate: fmt(addDays(now, 5)),
      quantity: 30,
      unit: '盒',
      storageLocation: 'B区-冷藏柜2',
      urgency: 'critical',
      status: 'pending',
      note: '需冷藏保存，注意温度监控',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 2)),
      confirmedById: '',
      confirmedByName: '',
      confirmedAt: '',
      confirmNote: '',
      rejectReason: '',
      updatedAt: fmt(subDays(now, 2)),
    },
    {
      id: 'w3',
      productName: '粘接剂',
      batchNo: 'BN20250120',
      expiryDate: fmt(addDays(now, 15)),
      quantity: 80,
      unit: '瓶',
      storageLocation: 'A区-货架1',
      urgency: 'urgent',
      status: 'confirmed',
      note: '常用型号，库存较多',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 5)),
      confirmedById: 'u2',
      confirmedByName: '王刚',
      confirmedAt: fmt(subDays(now, 3)),
      confirmNote: '已核实库存，确认临期',
      rejectReason: '',
      updatedAt: fmt(subDays(now, 3)),
    },
    {
      id: 'w4',
      productName: '根管充填材',
      batchNo: 'BN20250110',
      expiryDate: fmt(addDays(now, 20)),
      quantity: 25,
      unit: '套',
      storageLocation: 'C区-货架5',
      urgency: 'urgent',
      status: 'rejected',
      note: '该批次已部分使用，剩余数量待核实',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 7)),
      confirmedById: 'u2',
      confirmedByName: '王刚',
      confirmedAt: fmt(subDays(now, 5)),
      confirmNote: '',
      rejectReason: '库存数量与实际不符，请核实后重新提交',
      updatedAt: fmt(subDays(now, 5)),
    },
    {
      id: 'w5',
      productName: '藻酸盐印模材',
      batchNo: 'BN20241215',
      expiryDate: fmt(addDays(now, 60)),
      quantity: 100,
      unit: '袋',
      storageLocation: 'B区-货架2',
      urgency: 'normal',
      status: 'exchanged',
      note: '大批量库存，建议分批处理',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 10)),
      confirmedById: 'u2',
      confirmedByName: '王刚',
      confirmedAt: fmt(subDays(now, 8)),
      confirmNote: '确认临期，同意换货申请',
      rejectReason: '',
      updatedAt: fmt(subDays(now, 6)),
    },
    {
      id: 'w6',
      productName: '口腔消毒液',
      batchNo: 'BN20241201',
      expiryDate: fmt(addDays(now, 75)),
      quantity: 60,
      unit: '瓶',
      storageLocation: 'D区-危险品柜1',
      urgency: 'normal',
      status: 'exchanged',
      note: '消毒液过期风险较高，需及时处理',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 12)),
      confirmedById: 'u2',
      confirmedByName: '王刚',
      confirmedAt: fmt(subDays(now, 10)),
      confirmNote: '已确认，安排换货',
      rejectReason: '',
      updatedAt: fmt(subDays(now, 7)),
    },
    {
      id: 'w7',
      productName: '临时冠材料',
      batchNo: 'BN20241120',
      expiryDate: fmt(addDays(now, 2)),
      quantity: 40,
      unit: '盒',
      storageLocation: 'A区-货架2',
      urgency: 'critical',
      status: 'exchanged',
      note: '即将到期，紧急处理',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 4)),
      confirmedById: 'u2',
      confirmedByName: '王刚',
      confirmedAt: fmt(subDays(now, 3)),
      confirmNote: '紧急确认，立即安排换货',
      rejectReason: '',
      updatedAt: fmt(subDays(now, 2)),
    },
    {
      id: 'w8',
      productName: '牙科缝合线',
      batchNo: 'BN20241110',
      expiryDate: fmt(addDays(now, 25)),
      quantity: 200,
      unit: '包',
      storageLocation: 'C区-货架3',
      urgency: 'urgent',
      status: 'confirmed',
      note: '库存量较大，需关注消耗速度',
      createdById: 'u1',
      createdByName: '张丽',
      createdAt: fmt(subDays(now, 6)),
      confirmedById: 'u2',
      confirmedByName: '王刚',
      confirmedAt: fmt(subDays(now, 4)),
      confirmNote: '已核实，数量准确',
      rejectReason: '',
      updatedAt: fmt(subDays(now, 4)),
    },
  ]

  const exchanges: Exchange[] = [
    {
      id: 'e1',
      warningId: 'w5',
      reason: '临期产品退回供应商换新',
      expectedHandling: '退回供应商并换新批次',
      quantity: 100,
      supplierInfo: '上海医疗器械有限公司',
      handlingNote: '需要供应商出具退货接收证明',
      status: 'pending',
      appliedById: 'u2',
      appliedByName: '王刚',
      appliedAt: fmt(subDays(now, 6)),
      reviewedById: '',
      reviewedByName: '',
      reviewedAt: '',
      reviewNote: '',
      rejectReason: '',
      result: 'return_supplier',
      resultNote: '',
      completedAt: '',
      updatedAt: fmt(subDays(now, 6)),
      supplementNote: '',
      supplementedAt: '',
      supplementById: '',
      supplementByName: '',
      attachmentName: '',
      attachmentNote: '',
    },
    {
      id: 'e2',
      warningId: 'w6',
      reason: '消毒液临期，申请换新入库',
      expectedHandling: '换新入库处理',
      quantity: 60,
      supplierInfo: '广州医用消毒剂厂',
      handlingNote: '新批次需在30天内到货',
      status: 'approved',
      appliedById: 'u2',
      appliedByName: '王刚',
      appliedAt: fmt(subDays(now, 7)),
      reviewedById: 'u3',
      reviewedByName: '李明',
      reviewedAt: fmt(subDays(now, 5)),
      reviewNote: '同意换新，请尽快安排',
      rejectReason: '',
      result: 'replace_new',
      resultNote: '',
      completedAt: '',
      updatedAt: fmt(subDays(now, 5)),
      supplementNote: '',
      supplementedAt: '',
      supplementById: '',
      supplementByName: '',
      attachmentName: '',
      attachmentNote: '',
    },
    {
      id: 'e3',
      warningId: 'w7',
      reason: '临时冠材料即将到期，紧急换货',
      expectedHandling: '紧急退回供应商换新',
      quantity: 40,
      supplierInfo: '北京口腔材料供应商',
      handlingNote: '紧急处理，需供应商优先处理',
      status: 'completed',
      appliedById: 'u2',
      appliedByName: '王刚',
      appliedAt: fmt(subDays(now, 2)),
      reviewedById: 'u3',
      reviewedByName: '李明',
      reviewedAt: fmt(subDays(now, 1)),
      reviewNote: '紧急处理，立即安排',
      rejectReason: '',
      result: 'replace_new',
      resultNote: '已收到新批次，旧批次已退回',
      completedAt: today,
      updatedAt: today,
      supplementNote: '供应商已确认收到退货',
      supplementedAt: today,
      supplementById: 'u1',
      supplementByName: '张丽',
      attachmentName: '退货确认单.pdf',
      attachmentNote: '供应商退货确认凭证',
    },
    {
      id: 'e4',
      warningId: 'w8',
      reason: '牙科缝合线临期，申请退回供应商',
      expectedHandling: '退回供应商换新批次',
      quantity: 0,
      supplierInfo: '',
      handlingNote: '',
      status: 'rejected',
      appliedById: 'u2',
      appliedByName: '王刚',
      appliedAt: fmt(subDays(now, 3)),
      reviewedById: 'u3',
      reviewedByName: '李明',
      reviewedAt: fmt(subDays(now, 2)),
      reviewNote: '',
      rejectReason: '供应商信息不完整，换货数量未填写，请补充完整后重新提交',
      result: 'return_supplier',
      resultNote: '',
      completedAt: '',
      updatedAt: fmt(subDays(now, 2)),
      supplementNote: '已联系供应商确认可接收退货，但需提供完整换货数量',
      supplementedAt: fmt(subDays(now, 1)),
      supplementById: 'u1',
      supplementByName: '张丽',
      attachmentName: '供应商沟通记录.pdf',
      attachmentNote: '与供应商的邮件沟通记录',
    },
  ]

  const logs: OperationLog[] = [
    {
      id: 'log1',
      type: 'create_warning',
      relatedId: 'w1',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 1)),
      detail: '提交光固化树脂临期预警，批次BN20250301',
      isSupplement: false,
    },
    {
      id: 'log2',
      type: 'create_warning',
      relatedId: 'w2',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 2)),
      detail: '提交牙科印模材临期预警，批次BN20250215',
      isSupplement: false,
    },
    {
      id: 'log3',
      type: 'create_warning',
      relatedId: 'w3',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 5)),
      detail: '提交粘接剂临期预警，批次BN20250120',
      isSupplement: false,
    },
    {
      id: 'log4',
      type: 'confirm_warning',
      relatedId: 'w3',
      relatedType: 'warning',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 3)),
      detail: '确认粘接剂临期预警，备注：已核实库存',
      isSupplement: false,
    },
    {
      id: 'log5',
      type: 'create_warning',
      relatedId: 'w4',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 7)),
      detail: '提交根管充填材临期预警，批次BN20250110',
      isSupplement: false,
    },
    {
      id: 'log6',
      type: 'reject_warning',
      relatedId: 'w4',
      relatedType: 'warning',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 5)),
      detail: '退回根管充填材预警，原因：库存数量与实际不符',
      isSupplement: false,
    },
    {
      id: 'log7',
      type: 'create_warning',
      relatedId: 'w5',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 10)),
      detail: '提交藻酸盐印模材临期预警，批次BN20241215',
      isSupplement: false,
    },
    {
      id: 'log8',
      type: 'confirm_warning',
      relatedId: 'w5',
      relatedType: 'warning',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 8)),
      detail: '确认藻酸盐印模材临期预警',
      isSupplement: false,
    },
    {
      id: 'log9',
      type: 'create_exchange',
      relatedId: 'e1',
      relatedType: 'exchange',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 6)),
      detail: '为藻酸盐印模材提交换货申请，原因：临期产品退回供应商换新',
      isSupplement: false,
    },
    {
      id: 'log10',
      type: 'create_warning',
      relatedId: 'w6',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 12)),
      detail: '提交口腔消毒液临期预警，批次BN20241201',
      isSupplement: false,
    },
    {
      id: 'log11',
      type: 'confirm_warning',
      relatedId: 'w6',
      relatedType: 'warning',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 10)),
      detail: '确认口腔消毒液临期预警',
      isSupplement: false,
    },
    {
      id: 'log12',
      type: 'create_exchange',
      relatedId: 'e2',
      relatedType: 'exchange',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 7)),
      detail: '为口腔消毒液提交换货申请，原因：消毒液临期，申请换新入库',
      isSupplement: false,
    },
    {
      id: 'log13',
      type: 'approve_exchange',
      relatedId: 'e2',
      relatedType: 'exchange',
      operatorId: 'u3',
      operatorName: '李明',
      operatorRole: 'aftersales',
      operatedAt: fmt(subDays(now, 5)),
      detail: '审批通过口腔消毒液换货申请，备注：同意换新',
      isSupplement: false,
    },
    {
      id: 'log14',
      type: 'create_warning',
      relatedId: 'w7',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 4)),
      detail: '提交临时冠材料临期预警，批次BN20241120',
      isSupplement: false,
    },
    {
      id: 'log15',
      type: 'confirm_warning',
      relatedId: 'w7',
      relatedType: 'warning',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 3)),
      detail: '确认临时冠材料临期预警，紧急处理',
      isSupplement: false,
    },
    {
      id: 'log16',
      type: 'create_exchange',
      relatedId: 'e3',
      relatedType: 'exchange',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 2)),
      detail: '为临时冠材料提交换货申请，原因：即将到期，紧急换货',
      isSupplement: false,
    },
    {
      id: 'log17',
      type: 'approve_exchange',
      relatedId: 'e3',
      relatedType: 'exchange',
      operatorId: 'u3',
      operatorName: '李明',
      operatorRole: 'aftersales',
      operatedAt: fmt(subDays(now, 1)),
      detail: '审批通过临时冠材料换货申请，紧急安排',
      isSupplement: false,
    },
    {
      id: 'log18',
      type: 'complete_exchange',
      relatedId: 'e3',
      relatedType: 'exchange',
      operatorId: 'u3',
      operatorName: '李明',
      operatorRole: 'aftersales',
      operatedAt: today,
      detail: '完成临时冠材料换货处理，结果：换新入库',
      isSupplement: false,
    },
    {
      id: 'log19',
      type: 'supplement_exchange',
      relatedId: 'e3',
      relatedType: 'exchange',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: today,
      detail: '补录临时冠材料换货信息，供应商已确认收到退货',
      isSupplement: true,
    },
    {
      id: 'log20',
      type: 'create_warning',
      relatedId: 'w8',
      relatedType: 'warning',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 6)),
      detail: '提交牙科缝合线临期预警，批次BN20241110',
      isSupplement: false,
    },
    {
      id: 'log21',
      type: 'confirm_warning',
      relatedId: 'w8',
      relatedType: 'warning',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 4)),
      detail: '确认牙科缝合线临期预警，数量准确',
      isSupplement: false,
    },
    {
      id: 'log22',
      type: 'create_exchange',
      relatedId: 'e4',
      relatedType: 'exchange',
      operatorId: 'u2',
      operatorName: '王刚',
      operatorRole: 'warehouse',
      operatedAt: fmt(subDays(now, 3)),
      detail: '为牙科缝合线提交换货申请，原因：临期产品退回供应商',
      isSupplement: false,
    },
    {
      id: 'log23',
      type: 'reject_exchange',
      relatedId: 'e4',
      relatedType: 'exchange',
      operatorId: 'u3',
      operatorName: '李明',
      operatorRole: 'aftersales',
      operatedAt: fmt(subDays(now, 2)),
      detail: '驳回牙科缝合线换货申请，原因：供应商信息不完整，换货数量未填写',
      isSupplement: false,
    },
    {
      id: 'log24',
      type: 'supplement_exchange',
      relatedId: 'e4',
      relatedType: 'exchange',
      operatorId: 'u1',
      operatorName: '张丽',
      operatorRole: 'sales',
      operatedAt: fmt(subDays(now, 1)),
      detail: '补录牙科缝合线换货信息：已联系供应商确认可接收退货，但需提供完整换货数量',
      isSupplement: true,
    },
  ]

  useWarningStore.getState().setWarnings(warnings)
  useExchangeStore.getState().setExchanges(exchanges)
  useOperationLogStore.getState().setLogs(logs)
}
