export enum Role {
  BRAND_MANAGER = 'BRAND_MANAGER',
  OPERATION_SUPERVISOR = 'OPERATION_SUPERVISOR',
  LEASING_MANAGER = 'LEASING_MANAGER',
}

export enum ReportStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  MATERIALS_MISSING = 'MATERIALS_MISSING',
  MATERIALS_COMPLETE = 'MATERIALS_COMPLETE',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
  REVIEW_PASSED = 'REVIEW_PASSED',
  SETTLED = 'SETTLED',
  OVERDUE = 'OVERDUE',
}

export enum MaterialType {
  SALES_SLIP = 'SALES_SLIP',
  SETTLEMENT_STATEMENT = 'SETTLEMENT_STATEMENT',
  INVOICE = 'INVOICE',
  OTHER = 'OTHER',
}

export enum LogAction {
  SUBMIT = 'SUBMIT',
  RECEIVE_MATERIALS = 'RECEIVE_MATERIALS',
  MARK_MISSING = 'MARK_MISSING',
  SUPPLEMENT = 'SUPPLEMENT',
  REVIEW_PASS = 'REVIEW_PASS',
  REVIEW_REJECT = 'REVIEW_REJECT',
  SETTLE = 'SETTLE',
  MARK_OVERDUE = 'MARK_OVERDUE',
  COMMENT = 'COMMENT',
}
