const dishes = [
  { id: 1, name: '招牌肥牛', price: 68, category: '肉类' },
  { id: 2, name: '鲜切羊肉', price: 58, category: '肉类' },
  { id: 3, name: '虾滑', price: 48, category: '海鲜' },
  { id: 4, name: '毛肚', price: 58, category: '内脏' },
  { id: 5, name: '黄喉', price: 45, category: '内脏' },
  { id: 6, name: '鸭肠', price: 38, category: '内脏' },
  { id: 7, name: '藕片', price: 22, category: '蔬菜' },
  { id: 8, name: '土豆片', price: 18, category: '蔬菜' },
  { id: 9, name: '菠菜', price: 16, category: '蔬菜' },
  { id: 10, name: '金针菇', price: 20, category: '菌菇' },
  { id: 11, name: '香菇', price: 22, category: '菌菇' },
  { id: 12, name: '豆腐', price: 15, category: '豆制品' },
  { id: 13, name: '鸭血', price: 18, category: '豆制品' },
  { id: 14, name: '粉条', price: 16, category: '主食' },
  { id: 15, name: '面条', price: 12, category: '主食' },
  { id: 16, name: '蛋饺', price: 28, category: '主食' },
  { id: 17, name: '鱼丸', price: 32, category: '海鲜' },
  { id: 18, name: '蟹棒', price: 26, category: '海鲜' },
  { id: 19, name: '牛肉丸', price: 30, category: '肉类' },
  { id: 20, name: '午餐肉', price: 24, category: '肉类' }
];