import type {
  Order,
  StatusHistoryItem,
  User,
  UserRole,
  TireSpec,
} from '../../shared/types.js';

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3600 * 1000).toISOString();

export const users: User[] = [
  { id: 'u1', username: 'reception', name: '王小敏', role: 'RECEPTION' },
  { id: 'u2', username: 'tech', name: '李大力', role: 'TECHNICIAN' },
  { id: 'u3', username: 'manager', name: '张建国', role: 'MANAGER' },
];

const tireSpecs1: TireSpec[] = [
  {
    id: 't1',
    brand: '米其林',
    size: '225/55 R17',
    loadIndex: '97',
    speedRating: 'W',
    unitPrice: 1180,
    quantity: 4,
  },
];

const tireSpecs2: TireSpec[] = [
  {
    id: 't2',
    brand: '倍耐力',
    size: '245/45 R18',
    loadIndex: '96',
    speedRating: 'Y',
    unitPrice: 1680,
    quantity: 2,
  },
  {
    id: 't3',
    brand: '倍耐力',
    size: '275/40 R18',
    loadIndex: '99',
    speedRating: 'Y',
    unitPrice: 1980,
    quantity: 2,
  },
];

const tireSpecs3: TireSpec[] = [
  {
    id: 't4',
    brand: '固特异',
    size: '205/55 R16',
    loadIndex: '91',
    speedRating: 'V',
    unitPrice: 680,
    quantity: 4,
  },
];

export const orders: Order[] = [
  {
    id: 'o1',
    orderNo: 'TS20260614001',
    customerName: '陈先生',
    vehiclePlate: '京A·88888',
    vehicleModel: '奥迪 A6L 2023款',
    phone: '138****6688',
    status: 'PENDING_SELECTION',
    tireSpecs: [],
    quote: null,
    selectionResponsible: null,
    selectionResponsibleName: null,
    quoteResponsible: null,
    quoteResponsibleName: null,
    rejectReason: null,
    basisMaterials: ['旧台账记录：2023年更换同款米其林4条', '现场照片：轮胎磨损接近警戒线'],
    remark: '客户反映高速时抖动明显，建议做动平衡',
    createdAt: hours(2),
    updatedAt: hours(2),
    isException: true,
    exceptionReason: '创建已超过2小时未分配技师',
  },
  {
    id: 'o2',
    orderNo: 'TS20260614002',
    customerName: '刘女士',
    vehiclePlate: '京B·66666',
    vehicleModel: '宝马 530Li',
    phone: '139****1234',
    status: 'IN_SELECTION',
    tireSpecs: [],
    quote: null,
    selectionResponsible: 'u2',
    selectionResponsibleName: '李大力',
    quoteResponsible: null,
    quoteResponsibleName: null,
    rejectReason: null,
    basisMaterials: ['旧台账记录：前胎2022年、后胎2021年', '沟通截图：客户要求推荐静音舒适型'],
    remark: '客户下午3点到店取车',
    createdAt: hours(5),
    updatedAt: hours(3),
  },
  {
    id: 'o3',
    orderNo: 'TS20260614003',
    customerName: '赵总',
    vehiclePlate: '京C·A8888',
    vehicleModel: '保时捷 Cayenne',
    phone: '137****9999',
    status: 'PENDING_QUOTE',
    tireSpecs: tireSpecs2,
    quote: {
      subtotal: 7320,
      laborFee: 400,
      discount: 200,
      total: 7520,
    },
    selectionResponsible: 'u2',
    selectionResponsibleName: '李大力',
    quoteResponsible: null,
    quoteResponsibleName: null,
    rejectReason: null,
    basisMaterials: ['旧台账：上次更换为马牌CSC5', '现场检测：胎壁鼓包2处'],
    remark: 'VIP客户，要求原厂规格',
    createdAt: hours(8),
    updatedAt: hours(1),
  },
  {
    id: 'o4',
    orderNo: 'TS20260613005',
    customerName: '孙先生',
    vehiclePlate: '京D·12345',
    vehicleModel: '大众 帕萨特',
    phone: '136****5555',
    status: 'QUOTE_REJECTED',
    tireSpecs: tireSpecs3,
    quote: {
      subtotal: 2720,
      laborFee: 200,
      discount: 0,
      total: 2920,
    },
    selectionResponsible: 'u2',
    selectionResponsibleName: '李大力',
    quoteResponsible: 'u3',
    quoteResponsibleName: '张建国',
    rejectReason: '品牌选择不符，客户指定米其林，已改用固特异',
    basisMaterials: ['旧台账：2020年原厂韩泰', '现场记录：花纹深度不足2mm'],
    remark: '客户对价格敏感，需重新选型',
    createdAt: hours(26),
    updatedAt: hours(4),
    isException: true,
    exceptionReason: '报价被驳回，等待技师重新选型',
  },
  {
    id: 'o5',
    orderNo: 'TS20260613002',
    customerName: '周女士',
    vehiclePlate: '京E·77777',
    vehicleModel: '丰田 凯美瑞',
    phone: '135****7777',
    status: 'QUOTE_CONFIRMED',
    tireSpecs: tireSpecs1,
    quote: {
      subtotal: 4720,
      laborFee: 280,
      discount: 150,
      total: 4850,
    },
    selectionResponsible: 'u2',
    selectionResponsibleName: '李大力',
    quoteResponsible: 'u3',
    quoteResponsibleName: '张建国',
    rejectReason: null,
    basisMaterials: ['旧台账：2020年邓禄普', '现场记录：老化裂纹明显'],
    remark: '已安装完成，客户满意',
    createdAt: hours(30),
    updatedAt: hours(20),
  },
  {
    id: 'o6',
    orderNo: 'TS20260612008',
    customerName: '吴先生',
    vehiclePlate: '京F·99999',
    vehicleModel: '奔驰 E300L',
    phone: '133****2222',
    status: 'QUOTE_CONFIRMED',
    tireSpecs: tireSpecs2,
    quote: {
      subtotal: 7320,
      laborFee: 400,
      discount: 500,
      total: 7220,
    },
    selectionResponsible: 'u2',
    selectionResponsibleName: '李大力',
    quoteResponsible: 'u3',
    quoteResponsibleName: '张建国',
    rejectReason: null,
    basisMaterials: ['旧台账：2022年倍耐力P7'],
    remark: '老客户，给予特别折扣',
    createdAt: hours(50),
    updatedAt: hours(44),
  },
  {
    id: 'o7',
    orderNo: 'TS20260611003',
    customerName: '郑女士',
    vehiclePlate: '京G·33333',
    vehicleModel: '本田 CR-V',
    phone: '132****8888',
    status: 'QUOTE_CONFIRMED',
    tireSpecs: tireSpecs1,
    quote: {
      subtotal: 4720,
      laborFee: 280,
      discount: 0,
      total: 5000,
    },
    selectionResponsible: 'u2',
    selectionResponsibleName: '李大力',
    quoteResponsible: 'u3',
    quoteResponsibleName: '张建国',
    rejectReason: null,
    basisMaterials: ['沟通截图：客户指定米其林浩悦4'],
    remark: '周末取车',
    createdAt: hours(72),
    updatedAt: hours(66),
  },
];

export const statusHistory: StatusHistoryItem[] = [
  {
    id: 'h1',
    orderId: 'o1',
    fromStatus: null,
    toStatus: 'PENDING_SELECTION',
    operatorId: 'u1',
    operatorName: '王小敏',
    operatorRole: 'RECEPTION',
    timestamp: hours(2),
    remark: '前台创建工单',
  },
  {
    id: 'h2',
    orderId: 'o2',
    fromStatus: null,
    toStatus: 'PENDING_SELECTION',
    operatorId: 'u1',
    operatorName: '王小敏',
    operatorRole: 'RECEPTION',
    timestamp: hours(5),
    remark: '前台创建工单',
  },
  {
    id: 'h3',
    orderId: 'o2',
    fromStatus: 'PENDING_SELECTION',
    toStatus: 'IN_SELECTION',
    operatorId: 'u2',
    operatorName: '李大力',
    operatorRole: 'TECHNICIAN',
    timestamp: hours(3),
    remark: '技师领取工单开始选型',
  },
  {
    id: 'h4',
    orderId: 'o3',
    fromStatus: null,
    toStatus: 'PENDING_SELECTION',
    operatorId: 'u1',
    operatorName: '王小敏',
    operatorRole: 'RECEPTION',
    timestamp: hours(8),
    remark: '前台创建工单',
  },
  {
    id: 'h5',
    orderId: 'o3',
    fromStatus: 'PENDING_SELECTION',
    toStatus: 'IN_SELECTION',
    operatorId: 'u2',
    operatorName: '李大力',
    operatorRole: 'TECHNICIAN',
    timestamp: hours(6),
    remark: '技师领取工单',
  },
  {
    id: 'h6',
    orderId: 'o3',
    fromStatus: 'IN_SELECTION',
    toStatus: 'PENDING_QUOTE',
    operatorId: 'u2',
    operatorName: '李大力',
    operatorRole: 'TECHNICIAN',
    timestamp: hours(1),
    remark: '提交轮胎选型：倍耐力 P ZERO 前2后2',
  },
  {
    id: 'h7',
    orderId: 'o4',
    fromStatus: null,
    toStatus: 'PENDING_SELECTION',
    operatorId: 'u1',
    operatorName: '王小敏',
    operatorRole: 'RECEPTION',
    timestamp: hours(26),
    remark: '前台创建工单',
  },
  {
    id: 'h8',
    orderId: 'o4',
    fromStatus: 'PENDING_SELECTION',
    toStatus: 'IN_SELECTION',
    operatorId: 'u2',
    operatorName: '李大力',
    operatorRole: 'TECHNICIAN',
    timestamp: hours(24),
    remark: '技师领取工单',
  },
  {
    id: 'h9',
    orderId: 'o4',
    fromStatus: 'IN_SELECTION',
    toStatus: 'PENDING_QUOTE',
    operatorId: 'u2',
    operatorName: '李大力',
    operatorRole: 'TECHNICIAN',
    timestamp: hours(18),
    remark: '提交选型：固特异 御乘II代 4条',
  },
  {
    id: 'h10',
    orderId: 'o4',
    fromStatus: 'PENDING_QUOTE',
    toStatus: 'QUOTE_REJECTED',
    operatorId: 'u3',
    operatorName: '张建国',
    operatorRole: 'MANAGER',
    timestamp: hours(4),
    remark: '驳回：品牌选择不符，客户指定米其林',
  },
];

export const usersMap: Record<string, User> = Object.fromEntries(
  users.map((u) => [u.id, u]),
);

export function getUserByUsername(username: string): User | undefined {
  return users.find((u) => u.username === username);
}

export function getUserByRole(role: UserRole): User | undefined {
  return users.find((u) => u.role === role);
}
