import sys
lines = []
lines.append("func (s *Store) GetComplaintDetail(id string) (*models.ComplaintDetail, bool) {")
lines.append("	s.mu.RLock()")
lines.append("	defer s.mu.RUnlock()")
lines.append("")
lines.append("	complaint, ok := s.complaints[id]")
lines.append("	if ok != true {")
lines.append("		return nil, false")
lines.append("	}")
lines.append("")
lines.append("	detail := &models.ComplaintDetail{")
lines.append("		Complaint: *complaint,")
lines.append("	}")
lines.append("")
lines.append("	if complaint.BookingID != \"\" {")
lines.append("		if booking, ok := s.bookings[complaint.BookingID]; ok {")
lines.append("			detail.Booking = booking")
lines.append("		}")
lines.append("")
lines.append("		var checkins []models.CheckinRecord")
lines.append("		for _, c := range s.checkins {")
lines.append("			if c.BookingID == complaint.BookingID {")
lines.append("				checkins = append(checkins, *c)")
lines.append("			}")
lines.append("		}")
lines.append("		sort.Slice(checkins, func(i, j int) bool {")
lines.append("			return checkins[i].CheckinTime.Before(checkins[j].CheckinTime)")
lines.append("		})")
lines.append("		detail.Checkins = checkins")
lines.append("	}")
method = "
".join(lines)
content = open("internal/store/complaint.go").read()
content = content.rstrip() + "
" + method + "
"
open("internal/store/complaint.go", "w").write(content)
print("Method added successfully")
imports = open("internal/store/complaint.go").read()
if "sort" not in imports:
    imports = imports.replace("	\"fmt\"\n\t\"time\"", "	\"fmt\"\n\t\"sort\"\n\t\"time\"", 1)
    open("internal/store/complaint.go", "w").write(imports)
    print("Added sort import")
