import { writeFileSync } from 'fs'

const lines = []
lines.push('<script setup lang="ts">')
lines.push("import { ref, computed, onMounted } from 'vue'")
lines.push("import { useRoute, useRouter } from 'vue-router'")
lines.push('import {')
lines.push('  ArrowLeft,')
lines.push('  User,')
lines.push('  Calendar,')
lines.push('  Folder,')
lines.push('  CheckCircle2,')
lines.push('  XCircle,')
lines.push('  FileText,')
lines.push('  AlertTriangle,')
lines.push('  Check,')
lines.push('  X,')
lines.push('  Loader2,')
lines.push("} from 'lucide-vue-next'")
lines.push("import type { JointTest, TestItem } from '@/types'")
lines.push("import { testApi } from '@/api'")
lines.push("import StatusTag from '@/components/StatusTag.vue'")
lines.push("import Timeline from '@/components/Timeline.vue'")
lines.push('')
lines.push('const route = useRoute()')
lines.push('const router = useRouter()')
lines.push('')
lines.push('const test = ref<JointTest | null>(null)')
lines.push('const loading = ref(false)')
lines.push('const executingItems = ref<Set<string>>(new Set())')
lines.push('const completing = ref(false)')
lines.push('const converting = ref(false)')
lines.push('const selectedFailedItems = ref<Set<string>>(new Set())')
lines.push('const remarkInputs = ref<Record<string, string>>({})')
lines.push('')
lines.push('const testId = computed(() => route.params.id as string)')
lines.push('')
lines.push('const allItemsExecuted = computed(() => {')
lines.push('  if (!test.value?.items) return false')
lines.push('  return test.value.items.every((item) => item.passed !== null)')
lines.push('})')
lines.push('')
lines.push('const hasFailedItems = computed(() => {')
lines.push('  if (!test.value?.items) return false')
lines.push('  return test.value.items.some((item) => item.passed === false)')
lines.push('})')
lines.push('')
lines.push('const failedItems = computed(() => {')
lines.push('  if (!test.value?.items) return []')
lines.push('  return test.value.items.filter((item) => item.passed === false)')
lines.push('})')
lines.push('')
lines.push('const allFailedSelected = computed(() => {')
lines.push('  return failedItems.value.length > 0 && failedItems.value.every((item) => selectedFailedItems.value.has(item.id))')
lines.push('})')
lines.push('')
lines.push('const formatDate = (dateStr: string | null) => {')
lines.push("  if (!dateStr) return '-'")
lines.push('  const date = new Date(dateStr)')
lines.push("  return date.toLocaleString('zh-CN', {")
lines.push("    year: 'numeric',")
lines.push("    month: '2-digit',")
lines.push("    day: '2-digit',")
lines.push("    hour: '2-digit',")
lines.push("    minute: '2-digit',")
lines.push('  })')
lines.push('}')
lines.push('')
lines.push('async function fetchTest() {')
lines.push('  loading.value = true')
lines.push('  try {')
lines.push('    const res = await testApi.getTest(testId.value)')
lines.push('    if (res.success) {')
lines.push('      test.value = res.data')
lines.push('      if (res.data?.items) {')
lines.push('        res.data.items.forEach((item) => {')
lines.push('          if (!(item.id in remarkInputs.value)) {')
lines.push("            remarkInputs.value[item.id] = item.remark || ''")
lines.push('          }')
lines.push('        })')
lines.push('      }')
lines.push('    }')
lines.push('  } catch (err) {')
lines.push("    console.error('获取测试详情失败:', err)")
lines.push('  } finally {')
lines.push('    loading.value = false')
lines.push('  }')
lines.push('}')

writeFileSync('./src/pages/TestDetail.vue', lines.join('\n') + '\n', 'utf-8')
console.log('Part 1 done:', lines.length, 'lines')
