const fs = require('fs');
const p = './src/pages/TestDetail.vue';
const L = [];
const a = (s) => L.push(s);
a('<script setup lang="ts">');
a("import { ref, computed, onMounted } from 'vue'");
a("import { useRoute, useRouter } from 'vue-router'");
a('import { ArrowLeft, User, Calendar, Folder, CheckCircle2, XCircle, FileText, AlertTriangle, Check, X, Loader2 } from \'lucide-vue-next\'');
a("import type { JointTest, TestItem } from '@/types'");
a("import { testApi } from '@/api'");
a("import StatusTag from '@/components/StatusTag.vue'");
a("import Timeline from '@/components/Timeline.vue'");
a('const route = useRoute(); const router = useRouter();');
a('const test = ref(null); const loading = ref(false);');
a('const executingItems = ref(new Set()); const completing = ref(false);');
a('const converting = ref(false); const selectedFailedItems = ref(new Set());');
a('const remarkInputs = ref({});');
a('const testId = computed(() => route.params.id);');
a('const allItemsExecuted = computed(() => test.value?.items ? test.value.items.every(i => i.passed !== null) : false);');
a('const hasFailedItems = computed(() => test.value?.items ? test.value.items.some(i => i.passed === false) : false);');
a('const failedItems = computed(() => test.value?.items ? test.value.items.filter(i => i.passed === false) : []);');
a('const allFailedSelected = computed(() => failedItems.value.length > 0 && failedItems.value.every(i => selectedFailedItems.value.has(i.id)));');
a('const formatDate = (d) => !d ? "-" : new Date(d).toLocaleString("zh-CN", {year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});');
a('async function fetchTest() { loading.value = true; try { const res = await testApi.getTest(testId.value); if (res.success) { test.value = res.data; if (res.data?.items) res.data.items.forEach(i => { if (!(i.id in remarkInputs.value)) remarkInputs.value[i.id] = i.remark || ""; }); } } catch(e) { console.error("fail", e); } finally { loading.value = false; } }');
a('async function handleExecuteItem(item, passed) { executingItems.value.add(item.id); try { const res = await testApi.executeTestItem(testId.value, { testItemId: item.id, passed, remark: remarkInputs.value[item.id] || undefined }); if (res.success) test.value = res.data; } catch(e) { console.error(e); } finally { executingItems.value.delete(item.id); } }');
a('async function handleCompleteTest() { completing.value = true; try { const res = await testApi.completeTest(testId.value); if (res.success) test.value = res.data; } catch(e) { console.error(e); } finally { completing.value = false; } }');
a('function toggleFailedItem(id) { if (selectedFailedItems.value.has(id)) selectedFailedItems.value.delete(id); else selectedFailedItems.value.add(id); selectedFailedItems.value = new Set(selectedFailedItems.value); }');
a('function toggleAllFailedItems() { if (allFailedSelected.value) selectedFailedItems.value = new Set(); else selectedFailedItems.value = new Set(failedItems.value.map(i => i.id)); }');
a('async function handleConvertToIssue() { if (selectedFailedItems.value.size === 0) return; converting.value = true; try { const res = await testApi.convertToIssue(testId.value, Array.from(selectedFailedItems.value)); if (res.success && res.data && res.data[0]) router.push(`/issues/${res.data[0].id}`); } catch(e) { console.error(e); } finally { converting.value = false; } }');
a('onMounted(fetchTest);');
a('</script>');
fs.writeFileSync(p, L.join('\n') + '\n');
console.log('script done:', L.length, 'lines');
