const fs = require("fs");
const path = require("path");

const content = [
  "import db from \"./db\";",
  "",
  "export function initDatabase() {",
  "  db.exec(`",
  \"    CREATE TABLE IF NOT EXISTS students (\",
  \"      id TEXT PRIMARY KEY,\",
  \"      name TEXT NOT NULL,\",
  \"      student_id TEXT UNIQUE NOT NULL,\",
  \"      dorm_room TEXT NOT NULL,\",
  \"      counselor TEXT NOT NULL,\",
  \"      phone TEXT\",
  \"    );\",
  \"\",
  \"    CREATE TABLE IF NOT EXISTS users (\",
  \"      id TEXT PRIMARY KEY,\",
  \"      name TEXT NOT NULL,\",
  \"      role TEXT NOT NULL\",
  \"    );\",
  \"\",
  \"    CREATE TABLE IF NOT EXISTS keys_register (\",
  \"      id TEXT PRIMARY KEY,\",
  \"      student_id TEXT NOT NULL,\",
  \"      key_number TEXT NOT NULL,\",
  \"      status TEXT DEFAULT "\"正常\"",\",
  \"      issued_at TEXT\",
  \"    );\",
  \"\",
  \"    CREATE TABLE IF NOT EXISTS late_return_records (\",
  \"      id INTEGER PRIMARY KEY AUTOINCREMENT,\",
  \"      student_id TEXT NOT NULL,\",
  \"      late_time TEXT NOT NULL,\",
  \"      return_time TEXT NOT NULL,\",
  \"      reason TEXT NOT NULL,\",
  \"      dorm_officer_id TEXT NOT NULL,\",
  \"      dorm_officer_name TEXT NOT NULL,\",
  \"      dorm_officer_note TEXT,\",
  \"      counselor_id TEXT,\",
  \"      counselor_name TEXT,\",
  \"      counselor_note TEXT,\",
  \"      counselor_followed_at TEXT,\",
  \"      repair_needed INTEGER DEFAULT 0,\",
  \"      repair_note TEXT,\",
  \"      repair_person_id TEXT,\",
  \"      repair_person_name TEXT,\",
  \"      repair_completed_at TEXT,\",
  \"      status TEXT NOT NULL DEFAULT "\"已登记\"",\",
  \"      registered_at TEXT DEFAULT datetime("\"now\"")\",
  \"    );\",
  \"\",
  \"    CREATE TABLE IF NOT EXISTS status_logs (\",
  \"      id INTEGER PRIMARY KEY AUTOINCREMENT,\",
  \"      record_id INTEGER NOT NULL,\",
  \"      from_status TEXT,\",
  \"      to_status TEXT NOT NULL,\",
  \"      operator_id TEXT NOT NULL,\",
  \"      operator_name TEXT NOT NULL,\",
  \"      operator_role TEXT NOT NULL,\",
  \"      note TEXT,\",
  \"      created_at TEXT DEFAULT datetime("\"now\"")\",
  \"    );\",
  \"  `);\",
  \"\",
  \"  console.log("\"数据库表初始化完成\"");\",
  \"}\"
].join(\"\n\");

fs.writeFileSync(path.join(__dirname, \"api\", \"schema.ts\"), content);
console.log(\"schema.ts 写入成功\");
