import {
  Vehicle,
  InspectionTask,
  InspectionReport,
  ReportDistribution,
  FollowupTask,
} from '../types';

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
const fiveDaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000);

export const mockVehicles: Vehicle[] = [
  {
    id: 'V001',
    plateNumber: '京A·12345',
    ownerName: '李明',
    ownerPhone: '13800138001',
    ownerIdCard: '110101199001011234',
    brand: '宝马',
    model: 'BMW 525Li',
    vinCode: 'LBV8V9100EMS12345',
    registerDate: '2020-05-15',
    inspectionType: '初检',
    status: '已完成',
    createdAt: fiveDaysAgo.toISOString(),
    updatedAt: yesterday.toISOString(),
  },
  {
    id: 'V002',
    plateNumber: '京B·67890',
    ownerName: '王芳',
    ownerPhone: '13800138002',
    ownerIdCard: '110102199002022345',
    brand: '奔驰',
    model: 'C260L',
    vinCode: 'LNVU8V9101EMS67890',
    registerDate: '2019-08-20',
    inspectionType: '复检',
    status: '已发放',
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: twoDaysAgo.toISOString(),
  },
  {
    id: 'V003',
    plateNumber: '京C·11111',
    ownerName: '张伟',
    ownerPhone: '13800138003',
    ownerIdCard: '110105199003033456',
    brand: '奥迪',
    model: 'A4L',
    vinCode: 'LFV3A28W0E5011111',
    registerDate: '2021-03-10',
    inspectionType: '初检',
    status: '待审核',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
  },
  {
    id: 'V004',
    plateNumber: '京D·22222',
    ownerName: '刘强',
    ownerPhone: '13800138004',
    ownerIdCard: '110106199004044567',
    brand: '大众',
    model: '帕萨特',
    vinCode: 'LSVET4189E5022222',
    registerDate: '2018-11-25',
    inspectionType: '变更',
    status: '检测中',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'V005',
    plateNumber: '京E·33333',
    ownerName: '陈静',
    ownerPhone: '13800138005',
    ownerIdCard: '110107199005055678',
    brand: '丰田',
    model: '凯美瑞',
    vinCode: 'LVGBH42K0EG503333',
    registerDate: '2022-01-18',
    inspectionType: '初检',
    status: '待审核',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'V006',
    plateNumber: '京F·44444',
    ownerName: '赵磊',
    ownerPhone: '13800138006',
    ownerIdCard: '110108199006066789',
    brand: '本田',
    model: '雅阁',
    vinCode: 'LHGCM4620E8044444',
    registerDate: '2020-09-05',
    inspectionType: '复检',
    status: '发放中',
    createdAt: twoDaysAgo.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'V007',
    plateNumber: '京G·55555',
    ownerName: '周洋',
    ownerPhone: '13800138007',
    ownerIdCard: '110111199007077890',
    brand: '比亚迪',
    model: '汉',
    vinCode: 'LGWCA6H70NH805555',
    registerDate: '2023-02-28',
    inspectionType: '初检',
    status: '已发放',
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: yesterday.toISOString(),
  },
];

export const mockTasks: InspectionTask[] = [
  {
    id: 'T001',
    vehicleId: 'V001',
    inspectorId: 'I001',
    inspectorName: '张检测',
    status: '已完成',
    startTime: fiveDaysAgo.toISOString(),
    endTime: fiveDaysAgo.toISOString(),
    reportId: 'R001',
    createdAt: fiveDaysAgo.toISOString(),
  },
  {
    id: 'T002',
    vehicleId: 'V002',
    inspectorId: 'I001',
    inspectorName: '张检测',
    status: '已完成',
    startTime: threeDaysAgo.toISOString(),
    endTime: twoDaysAgo.toISOString(),
    reportId: 'R002',
    createdAt: threeDaysAgo.toISOString(),
  },
  {
    id: 'T003',
    vehicleId: 'V003',
    inspectorId: 'I002',
    inspectorName: '李检测',
    status: '已完成',
    startTime: yesterday.toISOString(),
    endTime: yesterday.toISOString(),
    reportId: 'R003',
    createdAt: yesterday.toISOString(),
  },
  {
    id: 'T004',
    vehicleId: 'V004',
    inspectorId: 'I001',
    inspectorName: '张检测',
    status: '进行中',
    startTime: now.toISOString(),
    createdAt: now.toISOString(),
  },
  {
    id: 'T005',
    vehicleId: 'V005',
    inspectorId: 'I002',
    inspectorName: '李检测',
    status: '已完成',
    startTime: now.toISOString(),
    endTime: now.toISOString(),
    reportId: 'R005',
    createdAt: now.toISOString(),
  },
  {
    id: 'T006',
    vehicleId: 'V006',
    inspectorId: 'I001',
    inspectorName: '张检测',
    status: '已完成',
    startTime: twoDaysAgo.toISOString(),
    endTime: twoDaysAgo.toISOString(),
    reportId: 'R006',
    createdAt: twoDaysAgo.toISOString(),
  },
  {
    id: 'T007',
    vehicleId: 'V007',
    inspectorId: 'I002',
    inspectorName: '李检测',
    status: '已完成',
    startTime: threeDaysAgo.toISOString(),
    endTime: threeDaysAgo.toISOString(),
    reportId: 'R007',
    createdAt: threeDaysAgo.toISOString(),
  },
];

export const mockReports: InspectionReport[] = [
  {
    id: 'R001',
    vehicleId: 'V001',
    taskId: 'T001',
    inspectorName: '张检测',
    auditorId: 'A001',
    auditorName: '王审核',
    status: '已通过',
    items: [
      { id: '1', name: '外观检查', result: '合格' },
      { id: '2', name: '灯光检查', result: '合格' },
      { id: '3', name: '制动检查', result: '合格' },
      { id: '4', name: '尾气检查', result: '合格' },
      { id: '5', name: '底盘检查', result: '合格' },
      { id: '6', name: '安全装置', result: '合格' },
    ],
    conclusion: '合格',
    photos: [],
    remark: '全部项目合格通过',
    submittedAt: fiveDaysAgo.toISOString(),
    auditedAt: fiveDaysAgo.toISOString(),
    distributedAt: fiveDaysAgo.toISOString(),
    createdAt: fiveDaysAgo.toISOString(),
  },
  {
    id: 'R002',
    vehicleId: 'V002',
    taskId: 'T002',
    inspectorName: '张检测',
    auditorId: 'A001',
    auditorName: '王审核',
    status: '已通过',
    items: [
      { id: '1', name: '外观检查', result: '合格' },
      { id: '2', name: '灯光检查', result: '合格' },
      { id: '3', name: '制动检查', result: '合格' },
      { id: '4', name: '尾气检查', result: '合格' },
      { id: '5', name: '底盘检查', result: '合格' },
      { id: '6', name: '安全装置', result: '合格' },
    ],
    conclusion: '合格',
    photos: [],
    remark: '全部项目合格通过',
    submittedAt: twoDaysAgo.toISOString(),
    auditedAt: twoDaysAgo.toISOString(),
    distributedAt: twoDaysAgo.toISOString(),
    createdAt: twoDaysAgo.toISOString(),
  },
  {
    id: 'R003',
    vehicleId: 'V003',
    taskId: 'T003',
    inspectorName: '李检测',
    status: '待审核',
    items: [
      { id: '1', name: '外观检查', result: '合格' },
      { id: '2', name: '灯光检查', result: '合格' },
      { id: '3', name: '制动检查', result: '合格' },
      { id: '4', name: '尾气检查', result: '合格' },
      { id: '5', name: '底盘检查', result: '合格' },
      { id: '6', name: '安全装置', result: '合格' },
    ],
    conclusion: '合格',
    photos: [],
    remark: '全部项目合格通过，等待审核',
    submittedAt: yesterday.toISOString(),
    createdAt: yesterday.toISOString(),
  },
  {
    id: 'R005',
    vehicleId: 'V005',
    taskId: 'T005',
    inspectorName: '李检测',
    status: '待审核',
    items: [
      { id: '1', name: '外观检查', result: '合格' },
      { id: '2', name: '灯光检查', result: '合格' },
      { id: '3', name: '制动检查', result: '合格' },
      { id: '4', name: '尾气检查', result: '合格' },
      { id: '5', name: '底盘检查', result: '合格' },
      { id: '6', name: '安全装置', result: '合格' },
    ],
    conclusion: '合格',
    photos: [],
    remark: '全部项目合格通过，等待审核',
    submittedAt: now.toISOString(),
    createdAt: now.toISOString(),
  },
  {
    id: 'R006',
    vehicleId: 'V006',
    taskId: 'T006',
    inspectorName: '张检测',
    auditorId: 'A001',
    auditorName: '王审核',
    status: '已通过',
    items: [
      { id: '1', name: '外观检查', result: '合格' },
      { id: '2', name: '灯光检查', result: '合格' },
      { id: '3', name: '制动检查', result: '合格' },
      { id: '4', name: '尾气检查', result: '合格' },
      { id: '5', name: '底盘检查', result: '合格' },
      { id: '6', name: '安全装置', result: '合格' },
    ],
    conclusion: '合格',
    photos: [],
    remark: '全部项目合格通过',
    submittedAt: twoDaysAgo.toISOString(),
    auditedAt: twoDaysAgo.toISOString(),
    distributedAt: twoDaysAgo.toISOString(),
    createdAt: twoDaysAgo.toISOString(),
  },
  {
    id: 'R007',
    vehicleId: 'V007',
    taskId: 'T007',
    inspectorName: '李检测',
    auditorId: 'A001',
    auditorName: '王审核',
    status: '已通过',
    items: [
      { id: '1', name: '外观检查', result: '合格' },
      { id: '2', name: '灯光检查', result: '合格' },
      { id: '3', name: '制动检查', result: '合格' },
      { id: '4', name: '尾气检查', result: '合格' },
      { id: '5', name: '底盘检查', result: '合格' },
      { id: '6', name: '安全装置', result: '合格' },
    ],
    conclusion: '合格',
    photos: [],
    remark: '全部项目合格通过',
    submittedAt: threeDaysAgo.toISOString(),
    auditedAt: threeDaysAgo.toISOString(),
    distributedAt: threeDaysAgo.toISOString(),
    createdAt: threeDaysAgo.toISOString(),
  },
];

export const mockDistributions: ReportDistribution[] = [
  {
    id: 'D001',
    reportId: 'R001',
    vehicleId: 'V001',
    status: '已发放',
    sentAt: fiveDaysAgo.toISOString(),
    confirmedAt: fiveDaysAgo.toISOString(),
    followupTaskId: 'F001',
    createdAt: fiveDaysAgo.toISOString(),
  },
  {
    id: 'D002',
    reportId: 'R002',
    vehicleId: 'V002',
    status: '已发放',
    sentAt: twoDaysAgo.toISOString(),
    confirmedAt: twoDaysAgo.toISOString(),
    followupTaskId: 'F002',
    createdAt: twoDaysAgo.toISOString(),
  },
  {
    id: 'D006',
    reportId: 'R006',
    vehicleId: 'V006',
    status: '发放中',
    sentAt: now.toISOString(),
    createdAt: now.toISOString(),
  },
  {
    id: 'D007',
    reportId: 'R007',
    vehicleId: 'V007',
    status: '已发放',
    sentAt: threeDaysAgo.toISOString(),
    confirmedAt: threeDaysAgo.toISOString(),
    followupTaskId: 'F003',
    createdAt: threeDaysAgo.toISOString(),
  },
];

const deadline1 = new Date(now.getTime() - 48 * 60 * 60 * 1000);
const deadline2 = new Date(now.getTime() - 24 * 60 * 60 * 1000);


export const mockFollowups: FollowupTask[] = [
  {
    id: 'F001',
    distributionId: 'D001',
    reportId: 'R001',
    vehicleId: 'V001',
    ownerName: '李明',
    ownerPhone: '13800138001',
    status: '已完成',
    deadline: deadline1.toISOString(),
    attempts: 1,
    result: {
      reportReceived: true,
      serviceSatisfaction: '非常满意',
      processSatisfaction: '满意',
      feedback: '检测过程很专业，服务态度好',
      conclusion: '满意',
      completedAt: fiveDaysAgo.toISOString(),
    },
    followupRecords: [
      {
        id: 'FR001',
        taskId: 'F001',
        type: '回访',
        contactResult: '成功',
        reportReceived: true,
        serviceSatisfaction: '非常满意',
        processSatisfaction: '满意',
        feedback: '检测过程很专业，服务态度好',
        operator: '管理员',
        operatedAt: fiveDaysAgo.toISOString(),
      },
    ],
    createdAt: fiveDaysAgo.toISOString(),
  },
  {
    id: 'F002',
    distributionId: 'D002',
    reportId: 'R002',
    vehicleId: 'V002',
    ownerName: '王芳',
    ownerPhone: '13800138002',
    status: '待回访',
    deadline: deadline2.toISOString(),
    attempts: 2,
    followupRecords: [
      {
        id: 'FR002',
        taskId: 'F002',
        type: '首次联系',
        contactResult: '无人接听',
        reportReceived: false,
        serviceSatisfaction: '一般',
        processSatisfaction: '基本满意',
        feedback: '',
        operator: '管理员',
        operatedAt: twoDaysAgo.toISOString(),
      },
      {
        id: 'FR003',
        taskId: 'F002',
        type: '催促',
        contactResult: '无人接听',
        reportReceived: false,
        serviceSatisfaction: '一般',
        processSatisfaction: '基本满意',
        feedback: '',
        operator: '管理员',
        operatedAt: yesterday.toISOString(),
      },
    ],
    createdAt: twoDaysAgo.toISOString(),
  },
  {
    id: 'F003',
    distributionId: 'D007',
    reportId: 'R007',
    vehicleId: 'V007',
    ownerName: '周洋',
    ownerPhone: '13800138007',
    status: '无法联系',
    deadline: yesterday.toISOString(),
    attempts: 3,
    followupRecords: [
      {
        id: 'FR004',
        taskId: 'F003',
        type: '首次联系',
        contactResult: '号码错误',
        reportReceived: false,
        serviceSatisfaction: '一般',
        processSatisfaction: '基本满意',
        feedback: '电话号码可能有误',
        operator: '管理员',
        operatedAt: threeDaysAgo.toISOString(),
      },
      {
        id: 'FR005',
        taskId: 'F003',
        type: '催促',
        contactResult: '号码错误',
        reportReceived: false,
        serviceSatisfaction: '一般',
        processSatisfaction: '基本满意',
        feedback: '再次确认号码错误',
        operator: '管理员',
        operatedAt: twoDaysAgo.toISOString(),
      },
      {
        id: 'FR006',
        taskId: 'F003',
        type: '催促',
        contactResult: '无人接听',
        reportReceived: false,
        serviceSatisfaction: '一般',
        processSatisfaction: '基本满意',
        feedback: '尝试多次均无法联系',
        operator: '管理员',
        operatedAt: yesterday.toISOString(),
      },
    ],
    createdAt: threeDaysAgo.toISOString(),
  },
];

export const initialMockData = {
  vehicles: mockVehicles,
  tasks: mockTasks,
  reports: mockReports,
  distributions: mockDistributions,
  followups: mockFollowups,
};
