import { Member, Room, DrinkItem, Order, RefundRecord } from './types';
import dayjs from 'dayjs';

export const mockMembers: Member[] = [
  {
    id: 'm1',
    name: '张三',
    phone: '13800138001',
    level: '金卡',
    balance: 2580.50,
    totalRecharge: 10000,
    createdAt: '2025-03-15 14:30:00',
  },
  {
    id: 'm2',
    name: '李四',
    phone: '13800138002',
    level: '银卡',
    balance: 860.00,
    totalRecharge: 3000,
    createdAt: '2025-08-20 19:15:00',
  },
  {
    id: 'm3',
    name: '王五',
    phone: '13800138003',
    level: '钻石',
    balance: 12800.00,
    totalRecharge: 50000,
    createdAt: '2024-12-01 10:00:00',
  },
  {
    id: 'm4',
    name: '赵六',
    phone: '13800138004',
    level: '普通',
    balance: 120.00,
    totalRecharge: 500,
    createdAt: '2026-01-10 20:45:00',
  },
  {
    id: 'm5',
    name: '钱七',
    phone: '13800138005',
    level: '金卡',
    balance: 3200.00,
    totalRecharge: 15000,
    createdAt: '2025-06-05 16:20:00',
  },
];

export const mockRooms: Room[] = [
  { id: 'r1', name: 'A01', type: '小包', pricePerHour: 68, status: 'available' },
  { id: 'r2', name: 'A02', type: '小包', pricePerHour: 68, status: 'occupied' },
  { id: 'r3', name: 'A03', type: '小包', pricePerHour: 68, status: 'available' },
  { id: 'r4', name: 'B01', type: '中包', pricePerHour: 98, status: 'occupied' },
  { id: 'r5', name: 'B02', type: '中包', pricePerHour: 98, status: 'available' },
  { id: 'r6', name: 'B03', type: '中包', pricePerHour: 98, status: 'maintenance' },
  { id: 'r7', name: 'C01', type: '大包', pricePerHour: 158, status: 'available' },
  { id: 'r8', name: 'C02', type: '大包', pricePerHour: 158, status: 'occupied' },
  { id: 'r9', name: 'D01', type: '豪华包', pricePerHour: 298, status: 'available' },
];

export const mockDrinks: DrinkItem[] = [
  { id: 'd1', name: '青岛啤酒', price: 15, category: '啤酒' },
  { id: 'd2', name: '百威啤酒', price: 20, category: '啤酒' },
  { id: 'd3', name: '1664白啤', price: 28, category: '啤酒' },
  { id: 'd4', name: '芝华士12年', price: 580, category: '洋酒' },
  { id: 'd5', name: '黑方', price: 480, category: '洋酒' },
  { id: 'd6', name: '红牛', price: 12, category: '饮料' },
  { id: 'd7', name: '可乐', price: 8, category: '饮料' },
  { id: 'd8', name: '雪碧', price: 8, category: '饮料' },
  { id: 'd9', name: '果盘（大）', price: 88, category: '小吃' },
  { id: 'd10', name: '果盘（小）', price: 48, category: '小吃' },
  { id: 'd11', name: '爆米花', price: 28, category: '小吃' },
  { id: 'd12', name: '瓜子', price: 18, category: '小吃' },
];

const now = dayjs();

export const mockOrders: Order[] = [
  {
    id: 'o1',
    orderNo: 'KTV' + now.format('YYYYMMDD') + '0001',
    memberId: 'm1',
    memberName: '张三',
    memberPhone: '13800138001',
    roomId: 'r2',
    roomName: 'A02',
    roomType: '小包',
    checkInTime: now.subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    durationHours: 0,
    roomFee: 0,
    items: [],
    drinksFee: 0,
    complimentaryFee: 0,
    totalAmount: 0,
    useBalance: 0,
    payAmount: 0,
    status: 'consuming',
    createdBy: '前台小王',
    createdAt: now.subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 'o2',
    orderNo: 'KTV' + now.format('YYYYMMDD') + '0002',
    memberId: 'm3',
    memberName: '王五',
    memberPhone: '13800138003',
    roomId: 'r4',
    roomName: 'B01',
    roomType: '中包',
    checkInTime: now.subtract(3, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    durationHours: 0,
    roomFee: 0,
    items: [],
    drinksFee: 0,
    complimentaryFee: 0,
    totalAmount: 0,
    useBalance: 0,
    payAmount: 0,
    status: 'consuming',
    createdBy: '前台小李',
    createdAt: now.subtract(3, 'hour').format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 'o3',
    orderNo: 'KTV' + now.subtract(1, 'day').format('YYYYMMDD') + '0015',
    memberId: 'm2',
    memberName: '李四',
    memberPhone: '13800138002',
    roomId: 'r8',
    roomName: 'C02',
    roomType: '大包',
    checkInTime: now.subtract(1, 'day').subtract(4, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    checkOutTime: now.subtract(1, 'day').subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    durationHours: 3,
    roomFee: 474,
    items: [
      { drinkId: 'd2', drinkName: '百威啤酒', quantity: 12, price: 240, isComplimentary: false },
      { drinkId: 'd9', drinkName: '果盘（大）', quantity: 1, price: 88, isComplimentary: false },
      { drinkId: 'd7', drinkName: '可乐', quantity: 4, price: 32, isComplimentary: false },
    ],
    drinksFee: 360,
    complimentaryFee: 0,
    totalAmount: 834,
    useBalance: 834,
    payAmount: 0,
    status: 'completed',
    createdBy: '前台小王',
    createdAt: now.subtract(1, 'day').subtract(4, 'hour').format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 'o4',
    orderNo: 'KTV' + now.subtract(1, 'day').format('YYYYMMDD') + '0018',
    roomId: 'r5',
    roomName: 'B02',
    roomType: '中包',
    checkInTime: now.subtract(1, 'day').subtract(3, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    checkOutTime: now.subtract(1, 'day').subtract(30, 'minute').format('YYYY-MM-DD HH:mm:ss'),
    durationHours: 2.5,
    roomFee: 245,
    items: [
      { drinkId: 'd1', drinkName: '青岛啤酒', quantity: 6, price: 90, isComplimentary: false },
      { drinkId: 'd11', drinkName: '爆米花', quantity: 2, price: 56, isComplimentary: true },
    ],
    drinksFee: 90,
    complimentaryFee: 56,
    totalAmount: 335,
    useBalance: 0,
    payAmount: 335,
    status: 'completed',
    createdBy: '前台小李',
    createdAt: now.subtract(1, 'day').subtract(3, 'hour').format('YYYY-MM-DD HH:mm:ss'),
  },
];

export const abnormalOrders: Order[] = [
  {
    id: 'o5',
    orderNo: 'KTV' + now.format('YYYYMMDD') + '0003',
    memberId: 'm5',
    memberName: '钱七',
    memberPhone: '13800138005',
    roomId: 'r7',
    roomName: 'C01',
    roomType: '大包',
    checkInTime: now.subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    durationHours: 0,
    roomFee: 0,
    items: [],
    drinksFee: 0,
    complimentaryFee: 0,
    totalAmount: 0,
    useBalance: 0,
    payAmount: 0,
    status: 'abnormal',
    createdBy: '前台小王',
    createdAt: now.subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    abnormalRecord: {
      id: 'a1',
      orderId: 'o5',
      type: 'room_conflict',
      description: '客人预订了C01包厢，但到店后发现包厢已被安排给另一桌客人，客人情绪激动。现场已协调到D01豪华包，但客人不同意补差价。',
      reportedBy: '前台小王',
      reportedAt: now.subtract(30, 'minute').format('YYYY-MM-DD HH:mm:ss'),
    },
  },
  {
    id: 'o6',
    orderNo: 'KTV' + now.subtract(1, 'day').format('YYYYMMDD') + '0020',
    memberId: 'm4',
    memberName: '赵六',
    memberPhone: '13800138004',
    roomId: 'r1',
    roomName: 'A01',
    roomType: '小包',
    checkInTime: now.subtract(1, 'day').subtract(5, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    checkOutTime: now.subtract(1, 'day').subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    durationHours: 3,
    roomFee: 204,
    items: [
      { drinkId: 'd3', drinkName: '1664白啤', quantity: 8, price: 224, isComplimentary: false },
      { drinkId: 'd10', drinkName: '果盘（小）', quantity: 1, price: 48, isComplimentary: true },
    ],
    drinksFee: 224,
    complimentaryFee: 48,
    totalAmount: 428,
    useBalance: 120,
    payAmount: 308,
    status: 'refunding',
    createdBy: '前台小李',
    createdAt: now.subtract(1, 'day').subtract(5, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    abnormalRecord: {
      id: 'a2',
      orderId: 'o6',
      type: 'drink_dispute',
      description: '客人称服务员承诺赠送2份果盘，但账单上只免了1份。客人拒绝买单，已报警协调未果。账单已挂账。',
      reportedBy: '前台小李',
      reportedAt: now.subtract(1, 'day').subtract(2, 'hour').format('YYYY-MM-DD HH:mm:ss'),
      handlerNote: '已查看监控，服务员确实承诺赠送2份果盘。建议退还多收的48元，并赠送200元代金券致歉。',
      handledAt: now.subtract(1, 'day').subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
      handledBy: '处理员小张',
    },
    refundRecord: {
      id: 'rf1',
      orderId: 'o6',
      amount: 48,
      reason: '酒水赠送口径不一致，多收取果盘费用。客人投诉，需退还多收部分并致歉。',
      applicant: '处理员小张',
      appliedAt: now.subtract(1, 'day').subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
      status: 'pending',
    },
    handlerNote: '已与客人电话沟通，客人接受退款方案，但要求尽快处理。',
    handledBy: '处理员小张',
    handledAt: now.subtract(1, 'day').subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
  },
];

export const refundHistory: RefundRecord[] = [
  {
    id: 'rf2',
    orderId: 'o7',
    amount: 256,
    reason: '设备故障，包厢音响中途损坏2小时，客人要求部分退款。',
    applicant: '处理员小张',
    appliedAt: now.subtract(3, 'day').format('YYYY-MM-DD HH:mm:ss'),
    status: 'approved',
    managerNote: '同意退款，已通知前台联系客人。',
    reviewedAt: now.subtract(2, 'day').format('YYYY-MM-DD HH:mm:ss'),
    reviewedBy: '店长陈经理',
  },
  {
    id: 'rf3',
    orderId: 'o8',
    amount: 580,
    reason: '客人称未消费芝华士，但账单上有记录。',
    applicant: '处理员小李',
    appliedAt: now.subtract(5, 'day').format('YYYY-MM-DD HH:mm:ss'),
    status: 'rejected',
    managerNote: '调取监控确认客人已开瓶饮用，拒绝退款。已将监控截图发送给客人。',
    reviewedAt: now.subtract(4, 'day').format('YYYY-MM-DD HH:mm:ss'),
    reviewedBy: '店长陈经理',
  },
];
