import type {
  Room,
  User,
  InspectionTask,
  InspectionResult,
  LinenRecord,
  MaintenanceOrder,
  MinibarCheck,
  MinibarProduct,
  AppState,
} from '@/types'

const rooms: Room[] = [
  // 3楼房间 (301-310)
  { id: 'room-301', number: '301', floor: '3F', status: 'dirty' },
  { id: 'room-302', number: '302', floor: '3F', status: 'occupied', currentGuest: '王建国' },
  { id: 'room-303', number: '303', floor: '3F', status: 'clean' },
  { id: 'room-304', number: '304', floor: '3F', status: 'dirty' },
  { id: 'room-305', number: '305', floor: '3F', status: 'inspecting' },
  { id: 'room-306', number: '306', floor: '3F', status: 'occupied', currentGuest: '李明华' },
  { id: 'room-307', number: '307', floor: '3F', status: 'maintenance' },
  { id: 'room-308', number: '308', floor: '3F', status: 'clean' },
  { id: 'room-309', number: '309', floor: '3F', status: 'dirty' },
  { id: 'room-310', number: '310', floor: '3F', status: 'occupied', currentGuest: '赵志强' },

  // 4楼房间 (401-410)
  { id: 'room-401', number: '401', floor: '4F', status: 'occupied', currentGuest: '孙丽萍' },
  { id: 'room-402', number: '402', floor: '4F', status: 'dirty' },
  { id: 'room-403', number: '403', floor: '4F', status: 'clean' },
  { id: 'room-404', number: '404', floor: '4F', status: 'inspecting' },
  { id: 'room-405', number: '405', floor: '4F', status: 'occupied', currentGuest: '周晓红' },
  { id: 'room-406', number: '406', floor: '4F', status: 'dirty' },
  { id: 'room-407', number: '407', floor: '4F', status: 'clean' },
  { id: 'room-408', number: '408', floor: '4F', status: 'maintenance' },
  { id: 'room-409', number: '409', floor: '4F', status: 'dirty' },
  { id: 'room-410', number: '410', floor: '4F', status: 'occupied', currentGuest: '吴海燕' },

  // 5楼房间 (501-510)
  { id: 'room-501', number: '501', floor: '5F', status: 'clean' },
  { id: 'room-502', number: '502', floor: '5F', status: 'occupied', currentGuest: '郑伟' },
  { id: 'room-503', number: '503', floor: '5F', status: 'dirty' },
  { id: 'room-504', number: '504', floor: '5F', status: 'inspecting' },
  { id: 'room-505', number: '505', floor: '5F', status: 'occupied', currentGuest: '陈美兰' },
  { id: 'room-506', number: '506', floor: '5F', status: 'dirty' },
  { id: 'room-507', number: '507', floor: '5F', status: 'clean' },
  { id: 'room-508', number: '508', floor: '5F', status: 'maintenance' },
  { id: 'room-509', number: '509', floor: '5F', status: 'clean' },
  { id: 'room-510', number: '510', floor: '5F', status: 'dirty' },
]

const users: User[] = [
  { id: 'user-1', name: '张主管', role: 'supervisor' },
  { id: 'user-2', name: '李主管', role: 'supervisor' },
  { id: 'user-3', name: '王保洁', role: 'attendant' },
  { id: 'user-4', name: '赵保洁', role: 'attendant' },
  { id: 'user-5', name: '刘保洁', role: 'attendant' },
  { id: 'user-6', name: '陈工程师', role: 'engineer' },
]

const inspectionTasks: InspectionTask[] = [
  { id: 'task-1', roomId: 'room-301', status: 'pending', createdAt: '2026-06-08T08:00:00' },
  { id: 'task-2', roomId: 'room-304', status: 'pending', createdAt: '2026-06-08T08:05:00' },
  { id: 'task-3', roomId: 'room-305', assignedTo: 'user-3', status: 'in_progress', createdAt: '2026-06-08T07:30:00' },
  { id: 'task-4', roomId: 'room-309', status: 'pending', createdAt: '2026-06-08T08:10:00' },
  { id: 'task-5', roomId: 'room-402', assignedTo: 'user-4', status: 'assigned', createdAt: '2026-06-08T07:45:00' },
  { id: 'task-6', roomId: 'room-404', assignedTo: 'user-3', status: 'in_progress', createdAt: '2026-06-08T07:15:00' },
  { id: 'task-7', roomId: 'room-406', status: 'pending', createdAt: '2026-06-08T08:15:00' },
  { id: 'task-8', roomId: 'room-409', assignedTo: 'user-5', status: 'assigned', createdAt: '2026-06-08T07:50:00' },
  { id: 'task-9', roomId: 'room-503', assignedTo: 'user-4', status: 'assigned', createdAt: '2026-06-08T08:00:00' },
  { id: 'task-10', roomId: 'room-506', status: 'pending', createdAt: '2026-06-08T08:20:00' },
]

const inspectionResults: InspectionResult[] = [
  {
    id: 'result-1',
    taskId: 'task-3',
    roomId: 'room-305',
    facilityOk: false,
    cleanlinessOk: true,
    linenStatus: 'ok',
    minibarInitialStatus: 'partial',
    issues: '浴室花洒头漏水，需要维修',
    createdAt: '2026-06-08T08:30:00',
  },
  {
    id: 'result-2',
    taskId: 'task-6',
    roomId: 'room-404',
    facilityOk: true,
    cleanlinessOk: true,
    linenStatus: 'missing',
    minibarInitialStatus: 'ok',
    issues: '缺少一条浴巾',
    createdAt: '2026-06-08T08:45:00',
  },
]

const linenRecords: LinenRecord[] = [
  {
    id: 'linen-1',
    taskId: 'task-3',
    roomId: 'room-305',
    itemType: '浴巾',
    expectedCount: 3,
    actualCount: 3,
    action: 'none',
  },
  {
    id: 'linen-2',
    taskId: 'task-3',
    roomId: 'room-305',
    itemType: '面巾',
    expectedCount: 2,
    actualCount: 2,
    action: 'none',
  },
  {
    id: 'linen-3',
    taskId: 'task-3',
    roomId: 'room-305',
    itemType: '床单',
    expectedCount: 2,
    actualCount: 2,
    action: 'replace',
  },
  {
    id: 'linen-4',
    taskId: 'task-6',
    roomId: 'room-404',
    itemType: '浴巾',
    expectedCount: 3,
    actualCount: 2,
    action: 'replenish',
  },
  {
    id: 'linen-5',
    taskId: 'task-6',
    roomId: 'room-404',
    itemType: '被套',
    expectedCount: 1,
    actualCount: 1,
    action: 'replace',
  },
]

const maintenanceOrders: MaintenanceOrder[] = [
  {
    id: 'order-1',
    roomId: 'room-305',
    taskId: 'task-3',
    description: '浴室花洒头漏水，需要更换花洒头',
    priority: 'medium',
    status: 'pending',
    assignedTo: 'user-6',
    createdAt: '2026-06-08T08:30:00',
    category: 'leak',
  },
  {
    id: 'order-2',
    roomId: 'room-307',
    taskId: 'task-1',
    description: '空调不制冷，需要检修压缩机',
    priority: 'high',
    status: 'in_progress',
    assignedTo: 'user-6',
    createdAt: '2026-06-07T14:00:00',
    category: 'electrical',
  },
  {
    id: 'order-3',
    roomId: 'room-408',
    taskId: 'task-5',
    description: '马桶冲水不畅，疑似堵塞',
    priority: 'medium',
    status: 'pending',
    createdAt: '2026-06-08T07:45:00',
    category: 'other',
  },
  {
    id: 'order-4',
    roomId: 'room-508',
    taskId: 'task-9',
    description: '房门门锁卡顿，需要润滑或更换',
    priority: 'low',
    status: 'completed',
    assignedTo: 'user-6',
    createdAt: '2026-06-07T10:00:00',
    completedAt: '2026-06-07T15:30:00',
    category: 'furniture',
  },
  {
    id: 'order-5',
    roomId: 'room-402',
    taskId: 'task-5',
    description: '窗帘轨道脱落，需要重新安装',
    priority: 'low',
    status: 'pending',
    createdAt: '2026-06-08T07:50:00',
    category: 'furniture',
  },
]

const minibarProducts: MinibarProduct[] = [
  { id: 'product-1', name: '可乐', defaultCount: 2, unitPrice: 8 },
  { id: 'product-2', name: '矿泉水', defaultCount: 2, unitPrice: 5 },
  { id: 'product-3', name: '啤酒', defaultCount: 2, unitPrice: 12 },
  { id: 'product-4', name: '薯片', defaultCount: 2, unitPrice: 10 },
  { id: 'product-5', name: '巧克力', defaultCount: 2, unitPrice: 15 },
]

const minibarChecks: MinibarCheck[] = [
  {
    id: 'check-1',
    taskId: 'task-3',
    roomId: 'room-305',
    checkedBy: 'user-3',
    status: 'anomaly',
    checkedAt: '2026-06-08T09:00:00',
    items: [
      { id: 'item-1', minibarCheckId: 'check-1', name: '可乐', expectedCount: 2, actualCount: 2, unitPrice: 8, isAnomaly: false },
      { id: 'item-2', minibarCheckId: 'check-1', name: '矿泉水', expectedCount: 2, actualCount: 1, unitPrice: 5, isAnomaly: true },
      { id: 'item-3', minibarCheckId: 'check-1', name: '啤酒', expectedCount: 2, actualCount: 2, unitPrice: 12, isAnomaly: false },
      { id: 'item-4', minibarCheckId: 'check-1', name: '薯片', expectedCount: 2, actualCount: 2, unitPrice: 10, isAnomaly: false },
      { id: 'item-5', minibarCheckId: 'check-1', name: '巧克力', expectedCount: 2, actualCount: 0, unitPrice: 15, isAnomaly: true },
    ],
  },
  {
    id: 'check-2',
    taskId: 'task-6',
    roomId: 'room-404',
    status: 'pending',
    items: [
      { id: 'item-6', minibarCheckId: 'check-2', name: '可乐', expectedCount: 2, actualCount: 2, unitPrice: 8, isAnomaly: false },
      { id: 'item-7', minibarCheckId: 'check-2', name: '矿泉水', expectedCount: 2, actualCount: 2, unitPrice: 5, isAnomaly: false },
      { id: 'item-8', minibarCheckId: 'check-2', name: '啤酒', expectedCount: 2, actualCount: 2, unitPrice: 12, isAnomaly: false },
      { id: 'item-9', minibarCheckId: 'check-2', name: '薯片', expectedCount: 2, actualCount: 2, unitPrice: 10, isAnomaly: false },
      { id: 'item-10', minibarCheckId: 'check-2', name: '巧克力', expectedCount: 2, actualCount: 2, unitPrice: 15, isAnomaly: false },
    ],
  },
  {
    id: 'check-3',
    taskId: 'task-5',
    roomId: 'room-402',
    checkedBy: 'user-4',
    status: 'checked',
    checkedAt: '2026-06-08T09:30:00',
    items: [
      { id: 'item-11', minibarCheckId: 'check-3', name: '可乐', expectedCount: 2, actualCount: 2, unitPrice: 8, isAnomaly: false },
      { id: 'item-12', minibarCheckId: 'check-3', name: '矿泉水', expectedCount: 2, actualCount: 2, unitPrice: 5, isAnomaly: false },
      { id: 'item-13', minibarCheckId: 'check-3', name: '啤酒', expectedCount: 2, actualCount: 2, unitPrice: 12, isAnomaly: false },
      { id: 'item-14', minibarCheckId: 'check-3', name: '薯片', expectedCount: 2, actualCount: 2, unitPrice: 10, isAnomaly: false },
      { id: 'item-15', minibarCheckId: 'check-3', name: '巧克力', expectedCount: 2, actualCount: 2, unitPrice: 15, isAnomaly: false },
    ],
  },
  {
    id: 'check-4',
    taskId: 'task-9',
    roomId: 'room-503',
    checkedBy: 'user-4',
    status: 'anomaly',
    checkedAt: '2026-06-08T10:00:00',
    items: [
      { id: 'item-16', minibarCheckId: 'check-4', name: '可乐', expectedCount: 2, actualCount: 1, unitPrice: 8, isAnomaly: true },
      { id: 'item-17', minibarCheckId: 'check-4', name: '矿泉水', expectedCount: 2, actualCount: 2, unitPrice: 5, isAnomaly: false },
      { id: 'item-18', minibarCheckId: 'check-4', name: '啤酒', expectedCount: 2, actualCount: 0, unitPrice: 12, isAnomaly: true },
      { id: 'item-19', minibarCheckId: 'check-4', name: '薯片', expectedCount: 2, actualCount: 2, unitPrice: 10, isAnomaly: false },
      { id: 'item-20', minibarCheckId: 'check-4', name: '巧克力', expectedCount: 2, actualCount: 2, unitPrice: 15, isAnomaly: false },
    ],
  },
]

export const mockData: AppState = {
  rooms,
  users,
  inspectionTasks,
  inspectionResults,
  linenRecords,
  maintenanceOrders,
  minibarChecks,
  minibarProducts,
  inspectionDrafts: {},
  uiFilters: {
    historySearchRoom: '',
    historyStatus: 'all',
    historyDateFrom: '',
    historyDateTo: '',
    reviewSearchRoom: '',
    reviewShowAll: false,
    engineerStatus: 'all',
    engineerSearchRoom: '',
    engineerCategory: 'all',
    engineerCompletedCategory: 'all',
  },
  currentUserId: undefined,
  currentRole: undefined,
}
