import type { Costume } from "@/types";
import { STATUS_META, USERS } from "@/constants";
import { genId, nowISO } from "@/utils";

const makeTimeline = (
  costumeId: string,
  entries: Array<{ status: Costume["status"]; operatorName: string; operatorRole: Costume["currentAssigneeRole"]; remark: string; daysAgo: number }>
) =>
  entries.map((e, i) => {
    const d = new Date();
    d.setDate(d.getDate() - e.daysAgo);
    d.setHours(9 + i, 30 + i * 10);
    const assigneeRole = STATUS_META[e.status].assigneeRole;
    const assignee = USERS[assigneeRole][0];
    return {
      id: genId("tl_"),
      costumeId,
      status: e.status,
      operatorName: e.operatorName,
      operatorRole: e.operatorRole,
      assigneeName: assignee.name,
      assigneeRole,
      timestamp: d.toISOString(),
      remark: e.remark,
    };
  });

export const seedCostumes: Costume[] = [
  {
    id: genId("cs_"),
    name: "2026 暑期汇演·少儿芭蕾《天鹅湖》",
    performanceDate: "2026-07-20",
    totalSets: 24,
    budget: 14400,
    classes: "少儿芭蕾初级A班、B班",
    status: "size_confirm_pending",
    currentAssignee: "陈老师",
    currentAssigneeRole: "teacher",
    remark: "白色 tutu 裙，需搭配白色连裤袜与软底鞋。家长反馈尺码偏小，建议订大一号。",
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    timeline: makeTimeline("", [
      { status: "created", operatorName: "李教务", operatorRole: "admin", remark: "根据汇演排课表发起服装需求，共24名学生参演", daysAgo: 12 },
      { status: "roster_pending", operatorName: "李教务", operatorRole: "admin", remark: "已转交陈老师确认学生名单", daysAgo: 11 },
      { status: "roster_confirmed", operatorName: "陈老师", operatorRole: "teacher", remark: "名单已核对，新增2名替补学生", daysAgo: 10 },
      { status: "sizing_pending", operatorName: "李教务", operatorRole: "admin", remark: "开始收集尺码信息", daysAgo: 9 },
      { status: "sizing_entered", operatorName: "李教务", operatorRole: "admin", remark: "已录入全部24名学生身高体重，尺码待老师确认", daysAgo: 3 },
      { status: "size_confirm_pending", operatorName: "李教务", operatorRole: "admin", remark: "已转交陈老师逐一确认尺码", daysAgo: 2 },
    ]),
    studentSizes: [
      {
        id: genId("ss_"),
        costumeId: "",
        studentName: "林小雨",
        height: 128,
        weight: 26,
        chest: 62,
        waist: 54,
        hips: 66,
        size: "S",
        confirmStatus: "confirmed",
        remark: "",
        createdAt: nowISO(),
        updatedAt: nowISO(),
        changeLogs: [],
      },
      {
        id: genId("ss_"),
        costumeId: "",
        studentName: "周子涵",
        height: 132,
        weight: 29,
        chest: 65,
        waist: 57,
        hips: 68,
        size: "M",
        confirmStatus: "confirmed",
        remark: "",
        createdAt: nowISO(),
        updatedAt: nowISO(),
        changeLogs: [
          {
            id: genId("log_"),
            studentSizeId: "",
            fieldName: "size",
            oldValue: "S",
            newValue: "M",
            operatorName: "李教务",
            operatorRole: "admin",
            timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
            remark: "家长反映孩子近期长高，原尺码偏小",
          },
        ],
      },
      {
        id: genId("ss_"),
        costumeId: "",
        studentName: "王梓萱",
        height: 125,
        weight: 25,
        chest: 60,
        waist: 52,
        hips: 64,
        size: "S",
        confirmStatus: "pending",
        remark: "",
        createdAt: nowISO(),
        updatedAt: nowISO(),
        changeLogs: [],
      },
      {
        id: genId("ss_"),
        costumeId: "",
        studentName: "赵一诺",
        height: 140,
        weight: 34,
        chest: 70,
        waist: 61,
        hips: 74,
        size: "L",
        confirmStatus: "exception",
        remark: "身高偏高，标准L号裙长偏短，需联系供应商定制加长2cm",
        createdAt: nowISO(),
        updatedAt: nowISO(),
        changeLogs: [
          {
            id: genId("log_"),
            studentSizeId: "",
            fieldName: "confirmStatus",
            oldValue: "pending",
            newValue: "exception",
            operatorName: "陈老师",
            operatorRole: "teacher",
            timestamp: new Date(Date.now() - 0.5 * 86400000).toISOString(),
            remark: "身高超出同年龄标准，裙长需定制",
          },
        ],
      },
    ],
  },
  {
    id: genId("cs_"),
    name: "2026 中国舞考级·五级考试服装",
    performanceDate: "2026-08-15",
    totalSets: 32,
    budget: 9600,
    classes: "中国舞五级班",
    status: "sizing_pending",
    currentAssignee: "李教务",
    currentAssigneeRole: "admin",
    remark: "水袖连体服，粉色。考级统一着装要求严格，必须合身。",
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    timeline: makeTimeline("", [
      { status: "created", operatorName: "王助理", operatorRole: "admin", remark: "根据考级名单发起，共32人", daysAgo: 6 },
      { status: "roster_pending", operatorName: "王助理", operatorRole: "admin", remark: "转交刘老师确认名单", daysAgo: 6 },
      { status: "roster_confirmed", operatorName: "刘老师", operatorRole: "teacher", remark: "名单已确认，无增减", daysAgo: 5 },
      { status: "sizing_pending", operatorName: "李教务", operatorRole: "admin", remark: "正在逐一联系家长收集尺码，进度约40%", daysAgo: 4 },
    ]),
    studentSizes: [
      {
        id: genId("ss_"),
        costumeId: "",
        studentName: "陈思琪",
        height: 135,
        weight: 30,
        chest: 66,
        waist: 58,
        hips: 70,
        size: "M",
        confirmStatus: "pending",
        remark: "",
        createdAt: nowISO(),
        updatedAt: nowISO(),
        changeLogs: [],
      },
      {
        id: genId("ss_"),
        costumeId: "",
        studentName: "黄思远",
        height: 142,
        weight: 33,
        chest: 69,
        waist: 60,
        hips: 73,
        size: "L",
        confirmStatus: "pending",
        remark: "",
        createdAt: nowISO(),
        updatedAt: nowISO(),
        changeLogs: [],
      },
    ],
  },
  {
    id: genId("cs_"),
    name: "2026 新年晚会·拉丁舞《燃情桑巴》",
    performanceDate: "2026-06-28",
    totalSets: 16,
    budget: 24000,
    classes: "拉丁舞精英班",
    status: "ordering",
    currentAssignee: "李教务",
    currentAssigneeRole: "admin",
    remark: "高级定制拉丁赛服，金黑配色，含头饰和舞鞋。预算较高，校长已特批。",
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    timeline: makeTimeline("", [
      { status: "created", operatorName: "李教务", operatorRole: "admin", remark: "根据精英班排演计划发起，共8对16人", daysAgo: 35 },
      { status: "roster_pending", operatorName: "李教务", operatorRole: "admin", remark: "转交张老师确认名单", daysAgo: 34 },
      { status: "roster_confirmed", operatorName: "张老师", operatorRole: "teacher", remark: "名单已确认，舞伴配对无误", daysAgo: 33 },
      { status: "sizing_pending", operatorName: "李教务", operatorRole: "admin", remark: "开始收集精确三围，赛服要求严格", daysAgo: 31 },
      { status: "sizing_entered", operatorName: "李教务", operatorRole: "admin", remark: "全部16人尺码已录齐", daysAgo: 28 },
      { status: "size_confirm_pending", operatorName: "李教务", operatorRole: "admin", remark: "转交张老师逐一确认", daysAgo: 27 },
      { status: "size_confirmed", operatorName: "张老师", operatorRole: "teacher", remark: "全部尺码确认无误，其中2人需微幅修改已备注供应商", daysAgo: 23 },
      { status: "approval_pending", operatorName: "李教务", operatorRole: "admin", remark: "预算24000元，提交校长审批", daysAgo: 20 },
      { status: "approved", operatorName: "赵校长", operatorRole: "principal", remark: "同意，演出效果是第一位的，务必确保质量", daysAgo: 19 },
      { status: "ordering", operatorName: "李教务", operatorRole: "admin", remark: "已下单供应商，预计15天到货，供应商承诺6月22日前交付", daysAgo: 5 },
    ]),
    studentSizes: [],
  },
];

seedCostumes.forEach((c) => {
  c.timeline.forEach((t) => (t.costumeId = c.id));
  c.studentSizes.forEach((s) => {
    s.costumeId = c.id;
    s.changeLogs.forEach((l) => (l.studentSizeId = s.id));
  });
});
