# Generated by Django 4.2.30 on 2026-06-10 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True)),
                ('source_order_no', models.CharField(blank=True, default='', max_length=32)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('flower_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(default='枝', max_length=10)),
                ('problem_desc', models.TextField()),
                ('photos_ref', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待受理'), ('urged', '有人催'), ('returned', '有人退回'), ('material_needed', '有人补材料'), ('in_progress', '处理中'), ('handed_off', '已接力'), ('completed', '补发完成'), ('to_loss', '待转损耗统计')], default='pending', max_length=20)),
                ('current_role', models.CharField(choices=[('planter', '种植员'), ('sales_staff', '销售内勤'), ('package_lead', '包装主管'), ('admin', '系统管理员')], default='sales_staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('has_loss', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_aftersale', to=settings.AUTH_USER_MODEL)),
                ('current_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_aftersale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'after_sale_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_no', models.CharField(max_length=32, unique=True)),
                ('flower_name', models.CharField(max_length=100)),
                ('loss_quantity', models.IntegerField()),
                ('unit', models.CharField(default='枝', max_length=10)),
                ('loss_reason', models.TextField()),
                ('responsibility', models.CharField(choices=[('planter', '种植环节'), ('sales_staff', '销售/内勤环节'), ('package_lead', '包装/发货环节'), ('logistics', '物流环节'), ('customer', '客户/不可抗力'), ('unclear', '责任不清待核')], default='unclear', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待责任确认'), ('confirmed', '责任已确认'), ('resolved', '损耗已处理'), ('closed', '已结案')], default='pending', max_length=20)),
                ('liable_person_name', models.CharField(blank=True, default='', max_length=50)),
                ('confirm_role', models.CharField(blank=True, choices=[('planter', '种植员'), ('sales_staff', '销售内勤'), ('package_lead', '包装主管'), ('admin', '系统管理员')], max_length=20, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('aftersale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_records', to='aftersale.aftersaleorder')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_losses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_losses', to=settings.AUTH_USER_MODEL)),
                ('liable_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_losses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loss_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('urge', '催促通知'), ('return', '退回通知'), ('material', '补材料通知'), ('handoff', '接力通知'), ('loss', '损耗通知')], max_length=20)),
                ('target_role', models.CharField(blank=True, choices=[('planter', '种植员'), ('sales_staff', '销售内勤'), ('package_lead', '包装主管'), ('admin', '系统管理员')], max_length=20, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_aftersale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to='aftersale.aftersaleorder')),
                ('related_loss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to='aftersale.lossrecord')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notify_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LossHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('action_role', models.CharField(choices=[('planter', '种植员'), ('sales_staff', '销售内勤'), ('package_lead', '包装主管'), ('admin', '系统管理员')], max_length=20)),
                ('operator_name', models.CharField(blank=True, default='', max_length=50)),
                ('status_from', models.CharField(blank=True, choices=[('pending', '待责任确认'), ('confirmed', '责任已确认'), ('resolved', '损耗已处理'), ('closed', '已结案')], default='', max_length=20)),
                ('status_to', models.CharField(blank=True, choices=[('pending', '待责任确认'), ('confirmed', '责任已确认'), ('resolved', '损耗已处理'), ('closed', '已结案')], default='', max_length=20)),
                ('responsibility_from', models.CharField(blank=True, choices=[('planter', '种植环节'), ('sales_staff', '销售/内勤环节'), ('package_lead', '包装/发货环节'), ('logistics', '物流环节'), ('customer', '客户/不可抗力'), ('unclear', '责任不清待核')], default='', max_length=20)),
                ('responsibility_to', models.CharField(blank=True, choices=[('planter', '种植环节'), ('sales_staff', '销售/内勤环节'), ('package_lead', '包装/发货环节'), ('logistics', '物流环节'), ('customer', '客户/不可抗力'), ('unclear', '责任不清待核')], default='', max_length=20)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='aftersale.lossrecord')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loss_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('planter', '种植员'), ('sales_staff', '销售内勤'), ('package_lead', '包装主管'), ('admin', '系统管理员')], max_length=20)),
                ('real_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_profile',
            },
        ),
        migrations.AddField(
            model_name='aftersaleorder',
            name='loss_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_aftersale', to='aftersale.lossrecord'),
        ),
        migrations.CreateModel(
            name='AfterSaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('action_role', models.CharField(choices=[('planter', '种植员'), ('sales_staff', '销售内勤'), ('package_lead', '包装主管'), ('admin', '系统管理员')], max_length=20)),
                ('operator_name', models.CharField(blank=True, default='', max_length=50)),
                ('status_from', models.CharField(blank=True, choices=[('pending', '待受理'), ('urged', '有人催'), ('returned', '有人退回'), ('material_needed', '有人补材料'), ('in_progress', '处理中'), ('handed_off', '已接力'), ('completed', '补发完成'), ('to_loss', '待转损耗统计')], default='', max_length=20)),
                ('status_to', models.CharField(blank=True, choices=[('pending', '待受理'), ('urged', '有人催'), ('returned', '有人退回'), ('material_needed', '有人补材料'), ('in_progress', '处理中'), ('handed_off', '已接力'), ('completed', '补发完成'), ('to_loss', '待转损耗统计')], default='', max_length=20)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aftersale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='aftersale.aftersaleorder')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'after_sale_history',
                'ordering': ['created_at'],
            },
        ),
    ]
