# Generated by Django 4.2.30 on 2026-06-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersaleorder',
            name='current_role',
            field=models.CharField(choices=[('planter', '种植员'), ('sales_staff', '销售内勤'), ('package_lead', '包装主管'), ('admin', '系统管理员')], default='planter', max_length=20),
        ),
    ]
