# Generated by Django 4.2.30 on 2026-06-06 01:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForkliftWorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('vehicle_plate', models.CharField(max_length=32, verbose_name='车牌号')),
                ('driver_name', models.CharField(max_length=32, verbose_name='司机姓名')),
                ('driver_phone', models.CharField(max_length=16, verbose_name='司机电话')),
                ('dock_number', models.CharField(max_length=16, verbose_name='月台号')),
                ('cargo_type', models.CharField(max_length=64, verbose_name='货物类型')),
                ('cargo_weight', models.FloatField(blank=True, null=True, verbose_name='货物重量(吨)')),
                ('status', models.CharField(choices=[('pending_dispatch', '待派工'), ('dispatched', '已派工'), ('in_progress', '作业中'), ('pending_confirm', '待确认'), ('completed', '已完成'), ('returned', '已退回'), ('exception', '异常')], default='pending_dispatch', max_length=20, verbose_name='状态')),
                ('current_role', models.CharField(choices=[('dispatcher', '调度员'), ('forklift_leader', '叉车班长'), ('warehouse_clerk', '仓库文员')], default='dispatcher', max_length=20, verbose_name='当前负责角色')),
                ('forklift_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='叉车编号')),
                ('operator_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='叉车司机')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='派工时间')),
                ('work_start_at', models.DateTimeField(blank=True, null=True, verbose_name='作业开始时间')),
                ('work_end_at', models.DateTimeField(blank=True, null=True, verbose_name='作业结束时间')),
                ('work_duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='作业时长(分钟)')),
                ('return_reason', models.TextField(blank=True, null=True, verbose_name='退回原因')),
                ('supplementary_notes', models.TextField(blank=True, null=True, verbose_name='补充备注')),
                ('exception_note', models.TextField(blank=True, null=True, verbose_name='异常说明')),
                ('dispatcher', models.CharField(blank=True, max_length=32, null=True, verbose_name='调度员')),
                ('warehouse_clerk', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库文员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '叉车派工作业单',
                'verbose_name_plural': '叉车派工作业单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('pending_dispatch', '待派工'), ('dispatched', '已派工'), ('in_progress', '作业中'), ('pending_confirm', '待确认'), ('completed', '已完成'), ('returned', '已退回'), ('exception', '异常')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('pending_dispatch', '待派工'), ('dispatched', '已派工'), ('in_progress', '作业中'), ('pending_confirm', '待确认'), ('completed', '已完成'), ('returned', '已退回'), ('exception', '异常')], max_length=20, verbose_name='新状态')),
                ('operator_role', models.CharField(choices=[('dispatcher', '调度员'), ('forklift_leader', '叉车班长'), ('warehouse_clerk', '仓库文员')], max_length=20, verbose_name='操作角色')),
                ('operator_name', models.CharField(max_length=32, verbose_name='操作人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='forklift.forkliftworkorder', verbose_name='作业单')),
            ],
            options={
                'verbose_name': '状态变更历史',
                'verbose_name_plural': '状态变更历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
