# Generated by Django 4.2.30 on 2026-06-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftworkorder',
            name='current_role',
            field=models.CharField(blank=True, choices=[('dispatcher', '调度员'), ('forklift_leader', '叉车班长'), ('warehouse_clerk', '仓库文员')], default='dispatcher', max_length=20, null=True, verbose_name='当前负责角色'),
        ),
    ]
