// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/patrols/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patrols/[id].get').default>>>>
    }
    '/api/patrols/:id/archive': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patrols/[id]/archive.put').default>>>>
    }
    '/api/patrols/:id/complete': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patrols/[id]/complete.put').default>>>>
    }
    '/api/patrols/:id/start': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patrols/[id]/start.put').default>>>>
    }
    '/api/patrols': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patrols/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/patrols/index.post').default>>>>
    }
    '/api/risks/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/risks/[id].get').default>>>>
    }
    '/api/risks/:id/approve': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/risks/[id]/approve.put').default>>>>
    }
    '/api/risks/:id/archive': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/risks/[id]/archive.put').default>>>>
    }
    '/api/risks/:id/reject': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/risks/[id]/reject.put').default>>>>
    }
    '/api/risks/:id/resubmit': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/risks/[id]/resubmit.put').default>>>>
    }
    '/api/risks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/risks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/risks/index.post').default>>>>
    }
    '/api/system/demo-accounts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/demo-accounts.get').default>>>>
    }
    '/api/system/reset': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/reset.post').default>>>>
    }
    '/api/todos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.get').default>>>>
    }
    '/api/trails': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trails/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}