# Generated by Django 6.0.6 on 2026-06-15 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='设备类型')),
                ('model_spec', models.CharField(blank=True, default='', max_length=128, verbose_name='型号规格')),
                ('status', models.CharField(choices=[('available', '空闲'), ('rented', '出租中'), ('in_maintenance', '维修中'), ('suspended', '停租')], default='available', max_length=32, verbose_name='设备状态')),
                ('daily_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='日租金(元)')),
                ('fuel_type', models.CharField(blank=True, default='', max_length=32, verbose_name='燃油类型')),
                ('current_project', models.CharField(blank=True, default='', max_length=128, verbose_name='当前项目')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=64, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('old_status', models.CharField(max_length=64, verbose_name='原状态')),
                ('new_status', models.CharField(max_length=64, verbose_name='新状态')),
                ('changed_by', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('reason', models.TextField(blank=True, default='', verbose_name='变更原因')),
            ],
            options={
                'verbose_name': '状态变更日志',
                'verbose_name_plural': '状态变更日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_no', models.CharField(max_length=64, unique=True, verbose_name='合同编号')),
                ('lessee', models.CharField(max_length=128, verbose_name='承租方')),
                ('start_date', models.DateField(verbose_name='租赁开始日')),
                ('end_date', models.DateField(verbose_name='租赁结束日')),
                ('daily_rent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同日租金(元)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='押金(元)')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否超期')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '租赁合同',
                'verbose_name_plural': '租赁合同',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('routine', '日常保养'), ('repair', '故障维修'), ('overhaul', '大修')], max_length=32, verbose_name='维保类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=32, verbose_name='维保状态')),
                ('reported_by', models.CharField(blank=True, default='', max_length=64, verbose_name='报修人')),
                ('assigned_mechanic', models.CharField(blank=True, default='', max_length=64, verbose_name='维修师傅')),
                ('fault_description', models.TextField(blank=True, default='', verbose_name='故障描述')),
                ('repair_notes', models.TextField(blank=True, default='', verbose_name='维修备注')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='维修费用(元)')),
                ('cost_bearer', models.CharField(blank=True, default='', max_length=64, verbose_name='费用承担方')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始维修时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='维修完成时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='rental.equipment', verbose_name='设备')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='rental.rentalcontract', verbose_name='关联合同')),
            ],
            options={
                'verbose_name': '维修保养记录',
                'verbose_name_plural': '维修保养记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspension_date', models.DateField(verbose_name='停租日期')),
                ('return_condition', models.TextField(blank=True, default='', verbose_name='还机状况')),
                ('fuel_level', models.CharField(blank=True, default='', max_length=64, verbose_name='还机油量')),
                ('meter_reading', models.CharField(blank=True, default='', max_length=64, verbose_name='还机读数')),
                ('damage_description', models.TextField(blank=True, default='', verbose_name='损坏描述')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='扣款金额(元)')),
                ('deduction_reason', models.TextField(blank=True, default='', verbose_name='扣款原因')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已驳回'), ('settled', '已结算')], default='pending', max_length=32, verbose_name='停租状态')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=64, verbose_name='审核人')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='结算日期')),
                ('maintenance_snapshot', models.JSONField(blank=True, default=dict, verbose_name='维修快照')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensions', to='rental.rentalcontract', verbose_name='合同')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensions', to='rental.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '停租处理',
                'verbose_name_plural': '停租处理',
                'ordering': ['-suspension_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('maintenance_created', '维保创建'), ('maintenance_updated', '维保变更'), ('maintenance_completed', '维保完成'), ('suspension_created', '停租创建'), ('suspension_status_changed', '停租状态变更'), ('contract_overdue', '合同超期'), ('equipment_status_changed', '设备状态变更')], max_length=64, verbose_name='通知类型')),
                ('target_role', models.CharField(choices=[('rental_manager', '租赁经理'), ('dispatcher', '调度'), ('mechanic', '维修师傅')], max_length=32, verbose_name='目标角色')),
                ('title', models.CharField(max_length=256, verbose_name='通知标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rental.equipment', verbose_name='关联设备')),
                ('related_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rental.maintenancerecord', verbose_name='关联维保')),
                ('related_suspension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rental.rentalsuspension', verbose_name='关联停租')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
