# Generated by Django 6.0.5 on 2026-06-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='器材名称')),
                ('category', models.CharField(choices=[('camera', '相机'), ('lens', '镜头'), ('light', '灯光'), ('accessory', '配件'), ('drone', '无人机')], max_length=20, verbose_name='分类')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('status', models.CharField(choices=[('available', '可用'), ('rented', '已借出'), ('maintenance', '维修中'), ('retired', '已退役')], default='available', max_length=20, verbose_name='状态')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='日租金')),
                ('replacement_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='重置价值')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '器材',
                'verbose_name_plural': '器材',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('start_date', models.DateField(verbose_name='租借开始日期')),
                ('original_end_date', models.DateField(verbose_name='原定归还日期')),
                ('current_end_date', models.DateField(verbose_name='当前归还日期')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('status', models.CharField(choices=[('active', '租借中'), ('returned', '已归还'), ('overdue', '已逾期')], default='active', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.equipment', verbose_name='器材')),
                ('store_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='经办店员')),
            ],
            options={
                'verbose_name': '租赁单',
                'verbose_name_plural': '租赁单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_end_date', models.DateField(verbose_name='原归还日期')),
                ('requested_end_date', models.DateField(verbose_name='申请延至日期')),
                ('reason', models.TextField(verbose_name='延长原因')),
                ('fee_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用增量')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_extensions', to=settings.AUTH_USER_MODEL, verbose_name='申请店员')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extensions', to=settings.AUTH_USER_MODEL, verbose_name='审核管理员')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rental.rentalorder', verbose_name='租赁单')),
            ],
            options={
                'verbose_name': '租期延长记录',
                'verbose_name_plural': '租期延长记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础租金')),
                ('extension_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='延期费用')),
                ('damage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='损坏费用')),
                ('overdue_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='逾期罚金')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应付总额')),
                ('deposit_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金抵扣')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应退金额')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('paid', '已收款'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_fees', to=settings.AUTH_USER_MODEL, verbose_name='结算财务')),
                ('rental_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_settlement', to='rental.rentalorder', verbose_name='租赁单')),
            ],
            options={
                'verbose_name': '费用结算',
                'verbose_name_plural': '费用结算',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='损坏描述')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估维修费')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际维修费')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('assessed', '已定损'), ('repaired', '已修复')], default='reported', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damages', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.equipment', verbose_name='器材')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='rental.rentalorder', verbose_name='租赁单')),
            ],
            options={
                'verbose_name': '损坏记录',
                'verbose_name_plural': '损坏记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('rental_order', '租赁单'), ('extension', '租期延长'), ('settlement', '费用结算'), ('damage', '损坏记录'), ('equipment', '器材')], max_length=30, verbose_name='实体类型')),
                ('entity_id', models.PositiveIntegerField(verbose_name='实体ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('status_change', '状态变更'), ('extension_requested', '延长申请'), ('extension_approved', '延长通过'), ('extension_rejected', '延长驳回'), ('extension_cancelled', '延长取消'), ('settlement_created', '结算创建'), ('settlement_recalculated', '结算重算'), ('settlement_paid', '结算收款'), ('settlement_refunded', '结算退款'), ('damage_reported', '损坏上报'), ('damage_assessed', '损坏定损'), ('damage_repaired', '损坏修复'), ('equipment_status_change', '器材状态变更')], max_length=30, verbose_name='操作')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('operator_role', models.CharField(default='', max_length=20, verbose_name='操作人角色')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('related_entity_type', models.CharField(blank=True, default='', max_length=30, verbose_name='关联实体类型')),
                ('related_entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联实体ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='rental_audi_entity__23adb3_idx'), models.Index(fields=['action'], name='rental_audi_action_0704a2_idx'), models.Index(fields=['-created_at'], name='rental_audi_created_79dbf8_idx')],
            },
        ),
    ]
