const fs = require("fs");
const L = [];
const a = (s) => L.push(s);

a("const express = require(\"express\"); const cors = require(\"cors\"); const Database = require(\"better-sqlite3\"); const app = express(); const PORT = 3001; app.use(cors()); app.use(express.json()); const db = new Database(\"./art_training.db\"); db.pragma(\"journal_mode = WAL\");");

a("db.exec(\"CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE, name TEXT, role TEXT, phone TEXT, created_at TEXT)\"); db.exec(\"CREATE TABLE IF NOT EXISTS trial_bookings (id INTEGER PRIMARY KEY AUTOINCREMENT, student_name TEXT, age INTEGER, parent_name TEXT, phone TEXT, course_type TEXT, preferred_time TEXT, remark TEXT, status TEXT, reject_reason TEXT, supplement_note TEXT, scheduled_time TEXT, teacher_id INTEGER, consultant_id INTEGER, created_at TEXT, updated_at TEXT, processed_at TEXT, processed_by INTEGER, trial_result TEXT, trial_remark TEXT)\"); db.exec(\"CREATE TABLE IF NOT EXISTS follow_ups (id INTEGER PRIMARY KEY AUTOINCREMENT, trial_booking_id INTEGER, status TEXT, consultant_id INTEGER, created_at TEXT, updated_at TEXT, next_follow_at TEXT, closed_at TEXT, lost_reason TEXT, final_remark TEXT, contract_amount REAL)\"); db.exec(\"CREATE TABLE IF NOT EXISTS follow_up_records (id INTEGER PRIMARY KEY AUTOINCREMENT, follow_up_id INTEGER, content TEXT, method TEXT, handler_id INTEGER, created_at TEXT, next_follow_at TEXT)\"); db.exec(\"CREATE TABLE IF NOT EXISTS operation_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, trial_booking_id INTEGER, action TEXT, content TEXT, operator_id INTEGER, created_at TEXT)\");");

a("const userCount = db.prepare(\"SELECT COUNT(*) as count FROM users\").get().count; if (userCount === 0) { const now = new Date(); const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString(); const insUser = db.prepare(\"INSERT INTO users (username, name, role, phone, created_at) VALUES (?, ?, ?, ?, ?)\"); insUser.run(\"consultant1\", \"张老师（课程顾问）\", \"consultant\", \"13800138001\", daysAgo(30)); insUser.run(\"consultant2\", \"李老师（课程顾问）\", \"consultant\", \"13800138002\", daysAgo(25)); insUser.run(\"teacher1\", \"王老师（钢琴）\", \"teacher\", \"13800138003\", daysAgo(40)); insUser.run(\"teacher2\", \"赵老师（舞蹈）\", \"teacher\", \"13800138004\", daysAgo(35)); insUser.run(\"director1\", \"陈主管（校区主管）\", \"director\", \"13800138005\", daysAgo(50)); console.log(\"用户种子数据初始化完成\"); }");

a("const bookingCount = db.prepare(\"SELECT COUNT(*) as count FROM trial_bookings\").get().count; if (bookingCount === 0) { const now = new Date(); const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString(); const insBooking = db.prepare(\"INSERT INTO trial_bookings (student_name, age, parent_name, phone, course_type, preferred_time, remark, status, reject_reason, supplement_note, scheduled_time, teacher_id, consultant_id, created_at, updated_at, processed_at, processed_by, trial_result, trial_remark) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\"); insBooking.run(\"小明\", 8, \"王爸爸\", \"13900139001\", \"钢琴\", \"周六上午\", \"之前学过1年基础\", \"rejected\", \"家长时间不合适，建议改到周日\", null, null, null, 1, daysAgo(7), daysAgo(6), daysAgo(6), 5, null, null); insBooking.run(\"小红\", 6, \"李妈妈\", \"13900139002\", \"舞蹈\", \"周日下午\", \"零基础，喜欢跳舞\", \"need_supplement\", null, \"请补充孩子的身高体重和是否有过敏史\", null, null, 1, daysAgo(5), daysAgo(4), daysAgo(4), 5, null, null); insBooking.run(\"小刚\", 10, \"张爸爸\", \"13900139003\", \"钢琴\", \"周六下午\", \"考了3级，想继续提高\", \"scheduled\", null, null, daysAgo(2).split(\"T\")[0] + \" 14:00\", 3, 2, daysAgo(4), daysAgo(3), daysAgo(3), 5, null, null); insBooking.run(\"小美\", 7, \"陈妈妈\", \"13900139004\", \"舞蹈\", \"周日上午\", \"有1年舞蹈基础\", \"completed\", null, null, daysAgo(1).split(\"T\")[0] + \" 10:00\", 4, 1, daysAgo(3), daysAgo(1), daysAgo(1), 3, \"good\", \"孩子很有天赋，表现力强，建议报精英班\"); insBooking.run(\"小华\", 9, \"刘爸爸\", \"13900139005\", \"钢琴\", \"周六上午\", \"零基础，感兴趣\", \"pending\", null, null, null, null, 2, daysAgo(1), daysAgo(1), null, null, null, null); console.log(\"试听预约种子数据初始化完成\"); }");

a("const followCount = db.prepare(\"SELECT COUNT(*) as count FROM follow_ups\").get().count; if (followCount === 0) { const now = new Date(); const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString(); const insFollow = db.prepare(\"INSERT INTO follow_ups (trial_booking_id, status, consultant_id, created_at, updated_at, next_follow_at, closed_at, lost_reason, final_remark, contract_amount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\"); insFollow.run(4, \"contacted\", 1, daysAgo(1), daysAgo(0), daysAgo(-2), null, null, null, null); const insRecord = db.prepare(\"INSERT INTO follow_up_records (follow_up_id, content, method, handler_id, created_at, next_follow_at) VALUES (?, ?, ?, ?, ?, ?)\"); insRecord.run(1, \"已联系家长，对课程很感兴趣，约定后天再电话沟通\", \"电话\", 1, daysAgo(1), daysAgo(-2)); const insLog = db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\"); insLog.run(1, \"reject\", \"驳回原因：家长时间不合适，建议改到周日\", 5, daysAgo(6)); insLog.run(2, \"need_supplement\", \"需要补充：孩子的身高体重和是否有过敏史\", 5, daysAgo(4)); insLog.run(3, \"approve\", \"安排周六下午14:00，王老师带课\", 5, daysAgo(3)); insLog.run(4, \"approve\", \"安排周日上午10:00，赵老师带课\", 5, daysAgo(2)); insLog.run(4, \"complete\", \"试听完成，评价：good，建议报精英班\", 3, daysAgo(1)); insLog.run(4, \"follow_up\", \"首次跟进：电话联系，家长感兴趣\", 1, daysAgo(1)); console.log(\"转化跟进和日志种子数据初始化完成\"); }");

a("function getMenuByRole(role) { const menus = { consultant: [{ key: \"booking-list\", label: \"我的试听预约\", path: \"/trial-bookings/mine\" }, { key: \"booking-create\", label: \"新建预约\", path: \"/trial-bookings/create\" }, { key: \"follow-list\", label: \"转化跟进\", path: \"/follow-ups/mine\" }, { key: \"stats\", label: \"业绩统计\", path: \"/stats/mine\" }], teacher: [{ key: \"my-schedule\", label: \"我的试听安排\", path: \"/trial-bookings/teacher\" }, { key: \"my-records\", label: \"试听记录\", path: \"/trial-bookings/teacher/completed\" }], director: [{ key: \"booking-all\", label: \"试听预约管理\", path: \"/trial-bookings\" }, { key: \"booking-pending\", label: \"待审核预约\", path: \"/trial-bookings/pending\" }, { key: \"follow-all\", label: \"转化跟进总览\", path: \"/follow-ups\" }, { key: \"stats-all\", label: \"校区数据统计\", path: \"/stats\" }, { key: \"user-mgmt\", label: \"人员管理\", path: \"/users\" }] }; return menus[role] || []; }");

a("app.get(\"/api/menu\", (req, res) => { const role = req.query.role || \"consultant\"; res.json({ code: 0, data: getMenuByRole(role) }); });");

a("app.post(\"/api/login\", (req, res) => { const { username } = req.body; const user = db.prepare(\"SELECT * FROM users WHERE username = ?\").get(username); if (!user) return res.json({ code: 1, msg: \"用户不存在\" }); res.json({ code: 0, data: { user, token: \"mock-token-\" + user.id } }); });");

a("app.get(\"/api/users\", (req, res) => { const users = db.prepare(\"SELECT * FROM users\").all(); res.json({ code: 0, data: users }); });");

a("app.get(\"/api/trial-bookings\", (req, res) => { const { status, role, userId } = req.query; let sql = \"SELECT b.*, u1.name as consultant_name, u2.name as teacher_name, f.status as follow_status FROM trial_bookings b LEFT JOIN users u1 ON b.consultant_id = u1.id LEFT JOIN users u2 ON b.teacher_id = u2.id LEFT JOIN follow_ups f ON b.id = f.trial_booking_id WHERE 1=1\"; const params = []; if (status) { sql += \" AND b.status = ?\"; params.push(status); } if (role === \"consultant\" && userId) { sql += \" AND b.consultant_id = ?\"; params.push(userId); } if (role === \"teacher\" && userId) { sql += \" AND b.teacher_id = ?\"; params.push(userId); } sql += \" ORDER BY b.created_at DESC\"; const bookings = db.prepare(sql).all(...params); res.json({ code: 0, data: bookings }); });");

a("app.get(\"/api/trial-bookings/:id\", (req, res) => { const id = req.params.id; const booking = db.prepare(\"SELECT b.*, u1.name as consultant_name, u2.name as teacher_name, u3.name as processed_by_name, f.status as follow_status, f.closed_at as follow_closed_at, f.final_remark as follow_final_remark, f.lost_reason as follow_lost_reason, f.contract_amount as follow_contract_amount FROM trial_bookings b LEFT JOIN users u1 ON b.consultant_id = u1.id LEFT JOIN users u2 ON b.teacher_id = u2.id LEFT JOIN users u3 ON b.processed_by = u3.id LEFT JOIN follow_ups f ON b.id = f.trial_booking_id WHERE b.id = ?\").get(id); if (!booking) return res.json({ code: 1, msg: \"预约不存在\" }); const logs = db.prepare(\"SELECT l.*, u.name as operator_name FROM operation_logs l LEFT JOIN users u ON l.operator_id = u.id WHERE l.trial_booking_id = ? ORDER BY l.created_at DESC\").all(id); res.json({ code: 0, data: { booking, logs } }); });");

a("app.post(\"/api/trial-bookings\", (req, res) => { const { student_name, age, parent_name, phone, course_type, preferred_time, remark, consultant_id } = req.body; const now = new Date().toISOString(); const result = db.prepare(\"INSERT INTO trial_bookings (student_name, age, parent_name, phone, course_type, preferred_time, remark, status, consultant_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\").run(student_name, age, parent_name, phone, course_type, preferred_time, remark, \"pending\", consultant_id, now, now); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(result.lastInsertRowid, \"create\", \"创建试听预约\", consultant_id, now); res.json({ code: 0, data: { id: result.lastInsertRowid } }); });");

a("app.post(\"/api/trial-bookings/:id/reject\", (req, res) => { const id = req.params.id; const { reason, operator_id } = req.body; const now = new Date().toISOString(); db.prepare(\"UPDATE trial_bookings SET status = ?, reject_reason = ?, processed_at = ?, processed_by = ?, updated_at = ? WHERE id = ?\").run(\"rejected\", reason, now, operator_id, now, id); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(id, \"reject\", \"驳回原因：\" + reason, operator_id, now); res.json({ code: 0, msg: \"驳回成功\" }); });");

a("app.post(\"/api/trial-bookings/:id/need-supplement\", (req, res) => { const id = req.params.id; const { supplement_note, operator_id } = req.body; const now = new Date().toISOString(); db.prepare(\"UPDATE trial_bookings SET status = ?, supplement_note = ?, processed_at = ?, processed_by = ?, updated_at = ? WHERE id = ?\").run(\"need_supplement\", supplement_note, now, operator_id, now, id); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(id, \"need_supplement\", \"需要补充：\" + supplement_note, operator_id, now); res.json({ code: 0, msg: \"已发送补录要求\" }); });");

a("app.post(\"/api/trial-bookings/:id/supplement\", (req, res) => { const id = req.params.id; const { remark, operator_id } = req.body; const now = new Date().toISOString(); db.prepare(\"UPDATE trial_bookings SET status = ?, remark = remark || ? , updated_at = ? WHERE id = ?\").run(\"pending\", \"; 补充：\" + remark, now, id); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(id, \"supplement\", \"补充信息：\" + remark, operator_id, now); res.json({ code: 0, msg: \"补录成功\" }); });");

a("app.post(\"/api/trial-bookings/:id/approve\", (req, res) => { const id = req.params.id; const { scheduled_time, teacher_id, operator_id } = req.body; const now = new Date().toISOString(); db.prepare(\"UPDATE trial_bookings SET status = ?, scheduled_time = ?, teacher_id = ?, processed_at = ?, processed_by = ?, updated_at = ? WHERE id = ?\").run(\"scheduled\", scheduled_time, teacher_id, now, operator_id, now, id); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(id, \"approve\", \"安排试听时间：\" + scheduled_time, operator_id, now); res.json({ code: 0, msg: \"安排成功\" }); });");

a("app.post(\"/api/trial-bookings/:id/complete\", (req, res) => { const id = req.params.id; const { trial_result, trial_remark, operator_id, consultant_id } = req.body; const now = new Date().toISOString(); db.prepare(\"UPDATE trial_bookings SET status = ?, trial_result = ?, trial_remark = ?, updated_at = ? WHERE id = ?\").run(\"completed\", trial_result, trial_remark, now, id); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(id, \"complete\", \"试听完成，结果：\" + trial_result, operator_id, now); const existingFollow = db.prepare(\"SELECT id FROM follow_ups WHERE trial_booking_id = ?\").get(id); if (!existingFollow) { const followResult = db.prepare(\"INSERT INTO follow_ups (trial_booking_id, status, consultant_id, created_at, updated_at, next_follow_at) VALUES (?, ?, ?, ?, ?, ?)\").run(id, \"pending\", consultant_id, now, now, new Date(Date.now() + 86400000).toISOString()); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(id, \"follow_up_create\", \"自动创建转化跟进任务\", operator_id, now); res.json({ code: 0, msg: \"试听完成，已创建转化跟进任务\" }); } else { res.json({ code: 0, msg: \"试听完成，跟进任务已存在\" }); } });");

a("app.get(\"/api/follow-ups\", (req, res) => { const { role, userId, status } = req.query; let sql = \"SELECT f.*, b.student_name, b.course_type, b.parent_name, b.phone, u.name as consultant_name FROM follow_ups f LEFT JOIN trial_bookings b ON f.trial_booking_id = b.id LEFT JOIN users u ON f.consultant_id = u.id WHERE 1=1\"; const params = []; if (role === \"consultant\" && userId) { sql += \" AND f.consultant_id = ?\"; params.push(userId); } if (status) { sql += \" AND f.status = ?\"; params.push(status); } sql += \" ORDER BY f.updated_at DESC\"; const followUps = db.prepare(sql).all(...params); res.json({ code: 0, data: followUps }); });");

a("app.get(\"/api/follow-ups/:id\", (req, res) => { const id = req.params.id; const followUp = db.prepare(\"SELECT f.*, b.student_name, b.course_type, b.parent_name, b.phone, b.trial_result, b.trial_remark, u.name as consultant_name FROM follow_ups f LEFT JOIN trial_bookings b ON f.trial_booking_id = b.id LEFT JOIN users u ON f.consultant_id = u.id WHERE f.id = ?\").get(id); if (!followUp) return res.json({ code: 1, msg: \"跟进记录不存在\" }); const records = db.prepare(\"SELECT r.*, u.name as handler_name FROM follow_up_records r LEFT JOIN users u ON r.handler_id = u.id WHERE r.follow_up_id = ? ORDER BY r.created_at DESC\").all(id); res.json({ code: 0, data: { followUp, records } }); });");

a("app.post(\"/api/follow-ups/:id/records\", (req, res) => { const id = req.params.id; const { content, method, handler_id, next_follow_at, status } = req.body; const now = new Date().toISOString(); const followUp = db.prepare(\"SELECT trial_booking_id FROM follow_ups WHERE id = ?\").get(id); if (!followUp) return res.json({ code: 1, msg: \"跟进任务不存在\" }); db.prepare(\"INSERT INTO follow_up_records (follow_up_id, content, method, handler_id, created_at, next_follow_at) VALUES (?, ?, ?, ?, ?, ?)\").run(id, content, method, handler_id, now, next_follow_at); const updateSql = status ? \"UPDATE follow_ups SET status = ?, updated_at = ?, next_follow_at = ? WHERE id = ?\" : \"UPDATE follow_ups SET updated_at = ?, next_follow_at = ? WHERE id = ?\"; const params = status ? [status, now, next_follow_at, id] : [now, next_follow_at, id]; db.prepare(updateSql).run(...params); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(followUp.trial_booking_id, \"follow_up_record\", \"添加跟进记录：\" + content, handler_id, now); res.json({ code: 0, msg: \"记录添加成功\" }); });");

a("app.post(\"/api/follow-ups/:id/sign\", (req, res) => { const id = req.params.id; const { final_remark, operator_id, contract_amount } = req.body; const now = new Date().toISOString(); const followUp = db.prepare(\"SELECT trial_booking_id FROM follow_ups WHERE id = ?\").get(id); if (!followUp) return res.json({ code: 1, msg: \"跟进任务不存在\" }); db.prepare(\"UPDATE follow_ups SET status = ?, closed_at = ?, updated_at = ?, final_remark = ?, contract_amount = ? WHERE id = ?\").run(\"signed\", now, now, final_remark, contract_amount || 0, id); db.prepare(\"UPDATE trial_bookings SET status = ?, updated_at = ? WHERE id = ?\").run(\"converted\", now, followUp.trial_booking_id); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(followUp.trial_booking_id, \"sign\", \"签约成功，备注：\" + final_remark + (contract_amount ? \"，合同金额：\" + contract_amount : \"\"), operator_id, now); res.json({ code: 0, msg: \"签约成功，跟进已关闭\" }); });");

a("app.post(\"/api/follow-ups/:id/lost\", (req, res) => { const id = req.params.id; const { lost_reason, final_remark, operator_id } = req.body; const now = new Date().toISOString(); const followUp = db.prepare(\"SELECT trial_booking_id FROM follow_ups WHERE id = ?\").get(id); if (!followUp) return res.json({ code: 1, msg: \"跟进任务不存在\" }); db.prepare(\"UPDATE follow_ups SET status = ?, closed_at = ?, updated_at = ?, lost_reason = ?, final_remark = ? WHERE id = ?\").run(\"lost\", now, now, lost_reason, final_remark, id); db.prepare(\"UPDATE trial_bookings SET status = ?, updated_at = ? WHERE id = ?\").run(\"lost\", now, followUp.trial_booking_id); db.prepare(\"INSERT INTO operation_logs (trial_booking_id, action, content, operator_id, created_at) VALUES (?, ?, ?, ?, ?)\").run(followUp.trial_booking_id, \"lost\", \"失单，原因：\" + lost_reason + \"，备注：\" + final_remark, operator_id, now); res.json({ code: 0, msg: \"已标记失单，跟进已关闭\" }); });");

a("app.get(\"/api/stats/dashboard\", (req, res) => { const totalBookings = db.prepare(\"SELECT COUNT(*) as count FROM trial_bookings\").get().count; const pendingBookings = db.prepare(\"SELECT COUNT(*) as count FROM trial_bookings WHERE status = pending\").get().count; const completedTrials = db.prepare(\"SELECT COUNT(*) as count FROM trial_bookings WHERE status = completed\").get().count; const converted = db.prepare(\"SELECT COUNT(*) as count FROM follow_ups WHERE status = signed\").get().count; const totalFollowUps = db.prepare(\"SELECT COUNT(*) as count FROM follow_ups\").get().count; const conversionRate = completedTrials > 0 ? Math.round(converted / completedTrials * 100) : 0; res.json({ code: 0, data: { totalBookings, pendingBookings, completedTrials, converted, totalFollowUps, conversionRate } }); });");

a("app.get(\"/docs\", (req, res) => { const html = `<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>艺术培训机构-试听预约与转化跟进 API文档</title><style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;max-width:1000px;margin:0 auto;padding:20px;background:#f5f5f5}h1{color:#1976d2}h2{color:#333;border-bottom:2px solid #1976d2;padding-bottom:8px;margin-top:30px}.endpoint{background:#fff;padding:16px;margin:12px 0;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1)}.method{display:inline-block;padding:4px 12px;border-radius:4px;color:#fff;font-weight:bold;margin-right:12px}.get{background:#2196f3}.post{background:#4caf50}</style></head><body><h1>艺术培训机构-试听预约与转化跟进 API文档</h1><h2>接口列表</h2><p><b>POST</b> /api/login - 用户登录</p><p><b>GET</b> /api/menu?role=consultant - 获取角色菜单</p><p><b>GET</b> /api/users - 用户列表</p><p><b>GET</b> /api/trial-bookings - 试听预约列表</p><p><b>GET</b> /api/trial-bookings/:id - 预约详情(含日志和转化结论)</p><p><b>POST</b> /api/trial-bookings - 创建预约</p><p><b>POST</b> /api/trial-bookings/:id/reject - 驳回(持久化原因)</p><p><b>POST</b> /api/trial-bookings/:id/need-supplement - 要求补录(持久化)</p><p><b>POST</b> /api/trial-bookings/:id/supplement - 提交补录</p><p><b>POST</b> /api/trial-bookings/:id/approve - 审核安排</p><p><b>POST</b> /api/trial-bookings/:id/complete - 完成试听(自动创建跟进，防重复)</p><p><b>GET</b> /api/follow-ups - 转化跟进列表</p><p><b>GET</b> /api/follow-ups/:id - 跟进详情(含记录回看和转化结论)</p><p><b>POST</b> /api/follow-ups/:id/records - 添加跟进记录</p><p><b>POST</b> /api/follow-ups/:id/sign - 签约收口(落库最终结果、关闭时间、负责人备注)</p><p><b>POST</b> /api/follow-ups/:id/lost - 失单收口(落库失单原因、关闭时间、负责人备注)</p><p><b>GET</b> /api/stats/dashboard - 仪表盘统计</p><h2>测试账号</h2><ul><li>consultant1 - 张老师(课程顾问)</li><li>consultant2 - 李老师(课程顾问)</li><li>teacher1 - 王老师(钢琴)</li><li>teacher2 - 赵老师(舞蹈)</li><li>director1 - 陈主管(校区主管)</li></ul></body></html>`; res.send(html); });");

a("app.listen(PORT, () => { console.log(\"Server running at http://localhost:\" + PORT); console.log(\"API文档: http://localhost:\" + PORT + \"/docs\"); });");

fs.writeFileSync("server.js", L.join(" ") + " ");
console.log("生成 server.js 完成，共", L.length, "行");

