import { c as create_ssr_component, v as validate_component, d as add_attribute, f as each, e as escape } from "../../../../chunks/ssr.js";
import { T as TIME_SLOTS } from "../../../../chunks/constants.js";
import { A as ArrowLeft, S as Save } from "../../../../chunks/save.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let user;
  let { data } = $$props;
  let customer_name = "";
  let phone = "";
  let date = "";
  if ($$props.data === void 0 && $$bindings.data && data !== void 0)
    $$bindings.data(data);
  user = data.user;
  return `${!user ? `<div class="min-h-screen flex items-center justify-center" data-svelte-h="svelte-19y3vto"><p class="text-gray-500">请先登录</p></div>` : `<div><div class="flex items-center space-x-4 mb-6"><a href="/reservations" class="flex items-center space-x-2 text-gray-600 hover:text-gray-800 transition-colors">${validate_component(ArrowLeft, "ArrowLeft").$$render($$result, { class: "w-5 h-5" }, {}, {})} <span data-svelte-h="svelte-y94d90">返回</span></a> <div data-svelte-h="svelte-1b0fcre"><h1 class="text-2xl font-bold text-gray-800">新增订台</h1> <p class="text-gray-500 mt-1">录入新的订台记录</p></div></div> <div class="bg-white rounded-xl shadow-sm p-6">${``} ${``} ${``} <form class="space-y-6"><div class="grid grid-cols-2 gap-6"><div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-5ml9gm">客户姓名 <span class="text-red-500">*</span></label> <input type="text" placeholder="请输入客户姓名" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-purple-500 transition-colors"${add_attribute("value", customer_name, 0)}></div> <div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-kn9zau">联系电话 <span class="text-red-500">*</span></label> <input type="tel" placeholder="请输入联系电话" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-purple-500 transition-colors"${add_attribute("value", phone, 0)}></div></div> <div class="grid grid-cols-2 gap-6"><div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-1o9hb3n">订台日期 <span class="text-red-500">*</span></label> <input type="date" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-purple-500 transition-colors"${add_attribute("value", date, 0)}></div> <div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-1e4gqso">时段 <span class="text-red-500">*</span></label> <select class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-purple-500 transition-colors"><option value="" data-svelte-h="svelte-g3ep4i">请选择时段</option>${each(TIME_SLOTS, (slot) => {
    return `<option${add_attribute("value", slot.value, 0)}>${escape(slot.label)}</option>`;
  })}</select></div></div> <div class="grid grid-cols-2 gap-6"><div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-1qtz3ts">台号 <span class="text-red-500">*</span></label> <select class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-purple-500 transition-colors">${each(Array.from({ length: 20 }, (_, i) => i + 1), (num) => {
    return `<option${add_attribute("value", num, 0)}>台${escape(num)}</option>`;
  })}</select></div> <div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-1mnuufs">人数</label> <select class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-purple-500 transition-colors">${each(Array.from({ length: 20 }, (_, i) => i + 1), (num) => {
    return `<option${add_attribute("value", num, 0)}>${escape(num)}人</option>`;
  })}</select></div></div> <div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-1o4vxvr">状态</label> <div class="flex items-center space-x-4"><label class="flex items-center space-x-2"><input type="radio" value="pending" class="w-4 h-4 text-purple-600 border-gray-300 focus:ring-purple-500"${""}> <span class="text-gray-700" data-svelte-h="svelte-1f4rx13">待确认</span></label> <label class="flex items-center space-x-2"><input type="radio" value="confirmed" class="w-4 h-4 text-purple-600 border-gray-300 focus:ring-purple-500"${add_attribute("checked", true, 1)}> <span class="text-gray-700" data-svelte-h="svelte-1tk8yxg">已确认</span></label> <label class="flex items-center space-x-2"><input type="radio" value="cancelled" class="w-4 h-4 text-purple-600 border-gray-300 focus:ring-purple-500"${""}> <span class="text-gray-700" data-svelte-h="svelte-5mts4w">已取消</span></label> <label class="flex items-center space-x-2"><input type="radio" value="completed" class="w-4 h-4 text-purple-600 border-gray-300 focus:ring-purple-500"${""}> <span class="text-gray-700" data-svelte-h="svelte-1hjrjoy">已完成</span></label></div></div> <div><label class="block text-sm font-medium text-gray-700 mb-2" data-svelte-h="svelte-j71c1z">备注说明</label> <textarea${add_attribute("rows", 3, 0)} placeholder="如：特殊需求、备注信息等" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-purple-500 transition-colors resize-none">${escape("")}</textarea></div> <div class="flex items-center justify-end space-x-4 pt-4 border-t border-gray-200"><a href="/reservations" class="px-6 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors" data-svelte-h="svelte-bbu5a1">取消</a> <button type="submit" class="flex items-center space-x-2 px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors">${validate_component(Save, "Save").$$render($$result, { class: "w-5 h-5" }, {}, {})} <span data-svelte-h="svelte-1huiimi">确认订台</span></button></div></form></div></div>`}`;
});
export {
  Page as default
};
