// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/11/2026, 9:56:29 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/liu/Documents/private/model-test/trae-20260601-5/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-5/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-5/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-5/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-5/plugins/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-5/composables/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-5/utils/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-5/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-5/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-5/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-5/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;