// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/18/2026, 11:35:26 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/zhangliu/Documents/private/model-test/trae-20260601-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/plugins/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/composables/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/utils/**/*.{js,ts,mjs}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangliu/Documents/private/model-test/trae-20260601-2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;