// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/19/2026, 2:01:54 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/liu/Documents/private/model-test/trae-20260601-1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-1/plugins/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-1/composables/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-1/utils/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-1/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;