from datetime import date, timedelta

from sqlalchemy.orm import Session

from app.models.models import (
    AbnormalAlert,
    AlertSeverity,
    AlertStatus,
    BatchStatus,
    ExecutionResult,
    ImmunizationExecution,
    ImmunizationPlan,
    MedicationRecord,
    MedicationType,
    Pen,
    PenType,
    PigBatch,
    PlanStatus,
    WithdrawalBlockReason,
)


def seed_sample_data(db: Session) -> None:
    if db.query(Pen).first() is not None:
        return

    today = date(2026, 6, 10)

    pens_data = [
        Pen(
            pen_code="A-01",
            pen_name="1号妊娠舍",
            pen_type=PenType.GESTATION,
            capacity=30,
            current_count=25,
            building="A栋",
        ),
        Pen(
            pen_code="A-02",
            pen_name="2号妊娠舍",
            pen_type=PenType.GESTATION,
            capacity=30,
            current_count=22,
            building="A栋",
        ),
        Pen(
            pen_code="B-01",
            pen_name="1号分娩舍",
            pen_type=PenType.FARROWING,
            capacity=12,
            current_count=10,
            building="B栋",
        ),
        Pen(
            pen_code="C-01",
            pen_name="1号保育舍",
            pen_type=PenType.NURSERY,
            capacity=50,
            current_count=45,
            building="C栋",
        ),
        Pen(
            pen_code="D-01",
            pen_name="隔离舍",
            pen_type=PenType.ISOLATION,
            capacity=10,
            current_count=3,
            building="D栋",
        ),
        Pen(
            pen_code="E-01",
            pen_name="1号公猪舍",
            pen_type=PenType.BOAR,
            capacity=8,
            current_count=6,
            building="E栋",
        ),
    ]
    db.add_all(pens_data)
    db.flush()

    batches_data = [
        PigBatch(
            batch_code="LB-2026-001",
            breed="大白猪",
            batch_status=BatchStatus.ACTIVE,
            head_count=25,
            entry_date=date(2026, 3, 1),
            pen_id=pens_data[0].id,
            notes="初产母猪群",
        ),
        PigBatch(
            batch_code="LB-2026-002",
            breed="长白猪",
            batch_status=BatchStatus.ACTIVE,
            head_count=22,
            entry_date=date(2026, 3, 15),
            pen_id=pens_data[1].id,
            notes="经产母猪群",
        ),
        PigBatch(
            batch_code="LB-2026-003",
            breed="大白×长白",
            batch_status=BatchStatus.ACTIVE,
            head_count=10,
            entry_date=date(2026, 5, 1),
            pen_id=pens_data[2].id,
            notes="分娩中",
        ),
        PigBatch(
            batch_code="LB-2026-004",
            breed="杜长大三元",
            batch_status=BatchStatus.ISOLATED,
            head_count=3,
            entry_date=date(2026, 5, 20),
            pen_id=pens_data[4].id,
            source_pen_id=pens_data[1].id,
            transfer_date=date(2026, 5, 20),
            notes="呼吸道症状隔离观察",
        ),
        PigBatch(
            batch_code="LB-2026-005",
            breed="大白猪",
            batch_status=BatchStatus.ACTIVE,
            head_count=45,
            entry_date=date(2026, 4, 10),
            pen_id=pens_data[3].id,
            notes="保育仔猪群",
        ),
    ]
    db.add_all(batches_data)
    db.flush()

    plans_data = [
        ImmunizationPlan(
            batch_id=batches_data[0].id,
            vaccine_name="猪瘟活疫苗",
            planned_date=date(2026, 5, 15),
            planned_dose=2.0,
            dose_unit="头份",
            route="肌注",
            plan_status=PlanStatus.COMPLETED,
            applicable_week_age=12,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[0].id,
            vaccine_name="口蹄疫灭活疫苗",
            planned_date=date(2026, 5, 28),
            planned_dose=2.0,
            dose_unit="ml",
            route="肌注",
            plan_status=PlanStatus.OVERDUE,
            applicable_week_age=14,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[0].id,
            vaccine_name="伪狂犬活疫苗",
            planned_date=date(2026, 6, 5),
            planned_dose=1.0,
            dose_unit="头份",
            route="肌注",
            plan_status=PlanStatus.OVERDUE,
            applicable_week_age=16,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[1].id,
            vaccine_name="猪瘟活疫苗",
            planned_date=date(2026, 5, 20),
            planned_dose=2.0,
            dose_unit="头份",
            route="肌注",
            plan_status=PlanStatus.COMPLETED,
            applicable_week_age=12,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[1].id,
            vaccine_name="口蹄疫灭活疫苗",
            planned_date=date(2026, 6, 3),
            planned_dose=2.0,
            dose_unit="ml",
            route="肌注",
            plan_status=PlanStatus.OVERDUE,
            applicable_week_age=14,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[1].id,
            vaccine_name="乙型脑炎活疫苗",
            planned_date=date(2026, 6, 15),
            planned_dose=1.0,
            dose_unit="头份",
            route="肌注",
            plan_status=PlanStatus.PENDING,
            booster_required=True,
            booster_date=date(2026, 7, 15),
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[2].id,
            vaccine_name="大肠杆菌灭活疫苗",
            planned_date=date(2026, 6, 12),
            planned_dose=2.0,
            dose_unit="ml",
            route="肌注",
            plan_status=PlanStatus.PENDING,
            applicable_week_age=4,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[4].id,
            vaccine_name="猪瘟活疫苗",
            planned_date=date(2026, 6, 8),
            planned_dose=1.0,
            dose_unit="头份",
            route="肌注",
            plan_status=PlanStatus.PENDING,
            applicable_week_age=8,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[4].id,
            vaccine_name="圆环病毒2型灭活疫苗",
            planned_date=date(2026, 6, 20),
            planned_dose=1.0,
            dose_unit="ml",
            route="肌注",
            plan_status=PlanStatus.PENDING,
            applicable_week_age=10,
            responsible_role="繁育员",
        ),
        ImmunizationPlan(
            batch_id=batches_data[3].id,
            vaccine_name="猪瘟活疫苗",
            planned_date=date(2026, 5, 25),
            planned_dose=2.0,
            dose_unit="头份",
            route="肌注",
            plan_status=PlanStatus.OVERDUE,
            applicable_week_age=14,
            responsible_role="繁育员",
        ),
    ]
    db.add_all(plans_data)
    db.flush()

    executions_data = [
        ImmunizationExecution(
            plan_id=plans_data[0].id,
            batch_id=batches_data[0].id,
            execution_date=date(2026, 5, 15),
            executor="张繁育",
            actual_dose=2.0,
            result=ExecutionResult.COMPLETED,
            head_count_executed=25,
        ),
        ImmunizationExecution(
            plan_id=plans_data[3].id,
            batch_id=batches_data[1].id,
            execution_date=date(2026, 5, 20),
            executor="张繁育",
            actual_dose=2.0,
            result=ExecutionResult.COMPLETED,
            head_count_executed=22,
        ),
        ImmunizationExecution(
            plan_id=plans_data[4].id,
            batch_id=batches_data[1].id,
            execution_date=date(2026, 6, 5),
            executor="李繁育",
            actual_dose=2.0,
            result=ExecutionResult.DELAYED,
            reason="疫苗到货延迟2天",
            head_count_executed=22,
        ),
        ImmunizationExecution(
            plan_id=plans_data[1].id,
            batch_id=batches_data[0].id,
            execution_date=today,
            executor="张繁育",
            actual_dose=2.0,
            result=ExecutionResult.MISSED,
            reason="群内3头妊娠后期母猪因应激风险未接种，待产后补打",
            head_count_executed=22,
        ),
        ImmunizationExecution(
            plan_id=plans_data[1].id,
            batch_id=batches_data[0].id,
            execution_date=today,
            executor="张繁育",
            actual_dose=2.0,
            result=ExecutionResult.MAKEUP,
            reason="产后补打口蹄疫疫苗（原5月28日漏打的3头）",
            head_count_executed=3,
        ),
    ]
    db.add_all(executions_data)
    db.flush()

    medications_data = [
        MedicationRecord(
            batch_id=batches_data[3].id,
            pen_id=pens_data[4].id,
            medication_type=MedicationType.ANTIBIOTIC,
            drug_name="氟苯尼考注射液",
            reason="呼吸道感染治疗",
            diagnosis="胸膜肺炎放线杆菌感染，体温40.8°C，咳嗽气喘",
            dosage=0.2,
            dosage_unit="ml/kg",
            route="肌注",
            frequency="每日1次",
            start_date=date(2026, 5, 20),
            end_date=date(2026, 6, 2),
            withdrawal_days=28,
            withdrawal_end_date=date(2026, 6, 30),
            is_isolation=True,
            veterinarian="王兽医",
            head_count_treated=3,
        ),
        MedicationRecord(
            batch_id=batches_data[3].id,
            pen_id=pens_data[4].id,
            medication_type=MedicationType.ANTI_INFLAMMATORY,
            drug_name="氟尼辛葡甲胺注射液",
            reason="退热镇痛",
            diagnosis="配合抗生素治疗，缓解发热症状",
            dosage=0.04,
            dosage_unit="ml/kg",
            route="肌注",
            frequency="每日1次",
            start_date=date(2026, 5, 20),
            end_date=date(2026, 5, 24),
            withdrawal_days=14,
            withdrawal_end_date=date(2026, 6, 7),
            is_isolation=True,
            veterinarian="王兽医",
            head_count_treated=3,
        ),
        MedicationRecord(
            batch_id=batches_data[0].id,
            pen_id=pens_data[0].id,
            medication_type=MedicationType.ANTIBIOTIC,
            drug_name="阿莫西林可溶性粉",
            reason="预防性用药",
            diagnosis="产后母猪预防子宫内膜炎",
            dosage=10,
            dosage_unit="mg/kg",
            route="拌料",
            frequency="每日2次",
            start_date=date(2026, 6, 1),
            end_date=date(2026, 6, 5),
            withdrawal_days=14,
            withdrawal_end_date=date(2026, 6, 19),
            is_isolation=False,
            veterinarian="王兽医",
            head_count_treated=5,
        ),
        MedicationRecord(
            batch_id=batches_data[1].id,
            pen_id=pens_data[1].id,
            medication_type=MedicationType.ANTIPARASITIC,
            drug_name="伊维菌素注射液",
            reason="体表寄生虫感染",
            diagnosis="皮肤疥螨感染，部分猪只蹭墙掉毛",
            dosage=0.3,
            dosage_unit="mg/kg",
            route="皮下注射",
            frequency="单次",
            start_date=date(2026, 6, 3),
            end_date=date(2026, 6, 3),
            withdrawal_days=28,
            withdrawal_end_date=date(2026, 7, 1),
            is_isolation=False,
            veterinarian="赵兽医",
            head_count_treated=8,
        ),
        MedicationRecord(
            batch_id=batches_data[3].id,
            pen_id=pens_data[4].id,
            medication_type=MedicationType.ANTIBIOTIC,
            drug_name="头孢噻呋钠注射液",
            reason="呼吸道感染二线治疗",
            diagnosis="氟苯尼考疗程结束后仍有1头未完全康复，更换抗生素",
            dosage=3,
            dosage_unit="mg/kg",
            route="肌注",
            frequency="每日1次",
            start_date=date(2026, 6, 3),
            end_date=date(2026, 6, 8),
            withdrawal_days=7,
            withdrawal_end_date=date(2026, 6, 15),
            is_isolation=True,
            veterinarian="王兽医",
            head_count_treated=1,
        ),
    ]
    db.add_all(medications_data)
    db.flush()

    alerts_data = [
        AbnormalAlert(
            batch_id=batches_data[0].id,
            pen_id=pens_data[0].id,
            alert_type="漏打疫苗",
            severity=AlertSeverity.WARNING,
            title="口蹄疫疫苗漏打3头",
            detail="LB-2026-001批次1号妊娠舍中3头妊娠后期母猪因应激风险未在5月28日接种口蹄疫灭活疫苗，已于6月10日补打完成",
            alert_status=AlertStatus.RESOLVED,
            related_record_id=plans_data[1].id,
            related_record_type="immunization_plan",
        ),
        AbnormalAlert(
            batch_id=batches_data[0].id,
            pen_id=pens_data[0].id,
            alert_type="逾期未执行",
            severity=AlertSeverity.CRITICAL,
            title="伪狂犬活疫苗逾期未执行",
            detail="LB-2026-001批次伪狂犬活疫苗计划6月5日执行，至今未执行，已逾期5天",
            alert_status=AlertStatus.ACTIVE,
            related_record_id=plans_data[2].id,
            related_record_type="immunization_plan",
        ),
        AbnormalAlert(
            batch_id=batches_data[3].id,
            pen_id=pens_data[4].id,
            alert_type="停药期限制",
            severity=AlertSeverity.CRITICAL,
            title="隔离批次处于停药期内",
            detail="LB-2026-004批次（隔离舍）使用氟苯尼考，停药期至6月30日，期间禁止转栏、淘汰和销售",
            alert_status=AlertStatus.ACTIVE,
            block_reason=WithdrawalBlockReason.TRANSFER,
            related_record_id=medications_data[0].id,
            related_record_type="medication_record",
        ),
        AbnormalAlert(
            batch_id=batches_data[1].id,
            pen_id=pens_data[1].id,
            alert_type="重复用药风险",
            severity=AlertSeverity.WARNING,
            title="伊维菌素与计划疫苗时间冲突",
            detail="LB-2026-002批次6月3日使用伊维菌素，与6月15日乙脑疫苗间隔不足，建议评估免疫效果",
            alert_status=AlertStatus.ACTIVE,
            related_record_id=medications_data[3].id,
            related_record_type="medication_record",
        ),
        AbnormalAlert(
            batch_id=batches_data[3].id,
            pen_id=pens_data[4].id,
            alert_type="漏打疫苗",
            severity=AlertSeverity.WARNING,
            title="隔离批次猪瘟疫苗漏打",
            detail="LB-2026-004批次因隔离状态未在5月25日执行猪瘟活疫苗接种，待隔离解除后补打",
            alert_status=AlertStatus.ACTIVE,
            related_record_id=plans_data[9].id,
            related_record_type="immunization_plan",
        ),
        AbnormalAlert(
            batch_id=batches_data[1].id,
            pen_id=pens_data[1].id,
            alert_type="逾期未执行",
            severity=AlertSeverity.WARNING,
            title="口蹄疫疫苗逾期执行",
            detail="LB-2026-002批次口蹄疫疫苗计划6月3日执行，实际6月5日执行，延迟2天",
            alert_status=AlertStatus.ACKNOWLEDGED,
            related_record_id=plans_data[4].id,
            related_record_type="immunization_plan",
        ),
    ]
    db.add_all(alerts_data)

    db.commit()
