import type { Order, User } from './types'

export const users: User[] = [
  { id: 'u1', name: '张接单', role: 'receiver' },
  { id: 'u2', name: '李设计', role: 'designer' },
  { id: 'u3', name: '王安装', role: 'installer' },
]

const today = new Date()
const yesterday = new Date(today.getTime() - 24 * 60 * 60 * 1000)
const twoDaysAgo = new Date(today.getTime() - 48 * 60 * 60 * 1000)
const tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000)

const formatDate = (d: Date) => d.toISOString()

export function generateSampleOrders(): Order[] {
  return [
    {
      id: 'o1',
      orderNo: 'AD20260615001',
      customerName: '星巴克咖啡',
      customerPhone: '13800138001',
      projectName: '夏季促销海报',
      createdAt: formatDate(yesterday),
      updatedAt: formatDate(today),
      manuscriptReceived: false,
      manuscriptVersion: 1,
      originalDimension: { width: 120, height: 180, unit: 'cm' },
      dimensionModified: false,
      installTimeModified: false,
      status: 'pending_receipt',
      currentHandler: 'receiver',
      attachments: [
        {
          id: 'a1',
          name: '客户需求说明.docx',
          type: 'other',
          url: '/attachments/placeholder1',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '张接单',
        },
      ],
      history: [
        {
          id: 'h1',
          timestamp: formatDate(yesterday),
          operator: '张接单',
          role: 'receiver',
          action: '创建订单',
          content: '客户要求加急，明天下午前完成喷绘',
          orderId: 'o1',
        },
      ],
    },
    {
      id: 'o2',
      orderNo: 'AD20260615002',
      customerName: '华为旗舰店',
      customerPhone: '13800138002',
      projectName: 'Mate 新品发布会背景板',
      createdAt: formatDate(twoDaysAgo),
      updatedAt: formatDate(today),
      manuscriptReceived: true,
      manuscriptReceivedAt: formatDate(yesterday),
      manuscriptReceivedBy: '张接单',
      manuscriptContent: '客户提供PSD文件，分辨率300DPI，CMYK模式',
      manuscriptVersion: 2,
      originalDimension: { width: 600, height: 300, unit: 'cm' },
      reviewedDimension: { width: 600, height: 300, unit: 'cm' },
      dimensionReviewed: true,
      dimensionReviewedAt: formatDate(yesterday),
      dimensionReviewedBy: '李设计',
      dimensionReviewNote: '尺寸复核通过，注意底部留空10cm放LOGO',
      dimensionModified: false,
      colorRequirement: '深色背景，注意颜色均匀，避免色差',
      colorConfirmed: true,
      colorConfirmedAt: formatDate(yesterday),
      installTime: formatDate(tomorrow),
      installAddress: '深圳南山万象天地华为旗舰店',
      installTimeModified: false,
      status: 'pending_print',
      currentHandler: 'designer',
      attachments: [
        {
          id: 'a2',
          name: '发布会背景板_v2.psd',
          type: 'manuscript',
          url: '/attachments/placeholder2',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '张接单',
        },
        {
          id: 'a3',
          name: '尺寸复核草图.jpg',
          type: 'other',
          url: '/attachments/placeholder3',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '李设计',
        },
      ],
      history: [
        {
          id: 'h2',
          timestamp: formatDate(twoDaysAgo),
          operator: '张接单',
          role: 'receiver',
          action: '创建订单',
          content: '客户初稿尺寸550x280cm，后续可能调整',
          orderId: 'o2',
        },
        {
          id: 'h3',
          timestamp: formatDate(yesterday),
          operator: '张接单',
          role: 'receiver',
          action: '更新稿件',
          content: '客户调整尺寸为600x300cm，更新稿件版本v2',
          orderId: 'o2',
        },
        {
          id: 'h4',
          timestamp: formatDate(yesterday),
          operator: '李设计',
          role: 'designer',
          action: '尺寸复核通过',
          content: '核对设计稿尺寸与订单一致，喷绘材质：520灯布',
          orderId: 'o2',
        },
        {
          id: 'h5',
          timestamp: formatDate(yesterday),
          operator: '李设计',
          role: 'designer',
          action: '颜色确认',
          content: '已按客户要求调整深色背景，色值：#0A1A2F',
          orderId: 'o2',
        },
      ],
    },
    {
      id: 'o3',
      orderNo: 'AD20260615003',
      customerName: '喜茶',
      customerPhone: '13800138003',
      projectName: '新店开业灯箱',
      createdAt: formatDate(yesterday),
      updatedAt: formatDate(today),
      manuscriptReceived: true,
      manuscriptReceivedAt: formatDate(yesterday),
      manuscriptReceivedBy: '张接单',
      manuscriptContent: 'AI格式矢量文件，注意文字转曲',
      manuscriptVersion: 1,
      originalDimension: { width: 200, height: 100, unit: 'cm' },
      dimensionModified: true,
      installTimeModified: false,
      status: 'pending_review',
      currentHandler: 'designer',
      attachments: [
        {
          id: 'a4',
          name: '喜茶新店灯箱.ai',
          type: 'manuscript',
          url: '/attachments/placeholder4',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '张接单',
        },
      ],
      history: [
        {
          id: 'h6',
          timestamp: formatDate(yesterday),
          operator: '张接单',
          role: 'receiver',
          action: '创建订单',
          content: '初稿尺寸180x80cm',
          orderId: 'o3',
        },
        {
          id: 'h7',
          timestamp: formatDate(today),
          operator: '张接单',
          role: 'receiver',
          action: '修改稿件',
          content: '客户修改尺寸为200x100cm，请设计注意复核！',
          orderId: 'o3',
        },
      ],
    },
    {
      id: 'o4',
      orderNo: 'AD20260615004',
      customerName: 'Nike专卖店',
      customerPhone: '13800138004',
      projectName: 'Air Max 推广展架',
      createdAt: formatDate(twoDaysAgo),
      updatedAt: formatDate(today),
      manuscriptReceived: true,
      manuscriptReceivedAt: formatDate(twoDaysAgo),
      manuscriptReceivedBy: '张接单',
      manuscriptContent: 'PSD分层文件，含出血位',
      manuscriptVersion: 1,
      originalDimension: { width: 80, height: 200, unit: 'cm' },
      reviewedDimension: { width: 80, height: 200, unit: 'cm' },
      dimensionReviewed: true,
      dimensionReviewedAt: formatDate(yesterday),
      dimensionReviewedBy: '李设计',
      dimensionReviewNote: '尺寸正确，X展架标准尺寸',
      dimensionModified: false,
      colorRequirement: '色彩鲜艳，符合品牌VI',
      colorConfirmed: true,
      installTime: formatDate(today),
      installAddress: '深圳福田COCO Park Nike店',
      installTimeModified: true,
      status: 'pending_install',
      currentHandler: 'installer',
      attachments: [
        {
          id: 'a5',
          name: 'AirMax展架.psd',
          type: 'manuscript',
          url: '/attachments/placeholder5',
          uploadedAt: formatDate(twoDaysAgo),
          uploadedBy: '张接单',
        },
        {
          id: 'a6',
          name: '喷绘成品照片1.jpg',
          type: 'photo',
          url: '/attachments/placeholder6',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '李设计',
        },
        {
          id: 'a7',
          name: '喷绘成品照片2.jpg',
          type: 'photo',
          url: '/attachments/placeholder7',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '李设计',
        },
      ],
      history: [
        {
          id: 'h8',
          timestamp: formatDate(twoDaysAgo),
          operator: '张接单',
          role: 'receiver',
          action: '创建订单',
          content: '原定安装时间昨天下午',
          orderId: 'o4',
        },
        {
          id: 'h9',
          timestamp: formatDate(yesterday),
          operator: '李设计',
          role: 'designer',
          action: '尺寸复核通过',
          content: '展架尺寸80x200cm正确，喷绘精度600DPI',
          orderId: 'o4',
        },
        {
          id: 'h10',
          timestamp: formatDate(yesterday),
          operator: '王安装',
          role: 'installer',
          action: '变更安装时间',
          content: '客户店铺昨天有活动，安装时间改到今天上午10点',
          orderId: 'o4',
        },
      ],
    },
    {
      id: 'o5',
      orderNo: 'AD20260615005',
      customerName: '小米之家',
      customerPhone: '13800138005',
      projectName: 'SU7 汽车宣传海报',
      createdAt: formatDate(yesterday),
      updatedAt: formatDate(today),
      manuscriptReceived: true,
      manuscriptReceivedAt: formatDate(yesterday),
      manuscriptReceivedBy: '张接单',
      manuscriptContent: '客户提供高清PNG，需放大喷绘',
      manuscriptVersion: 1,
      originalDimension: { width: 300, height: 200, unit: 'cm' },
      dimensionModified: false,
      installTimeModified: false,
      status: 'pending_review',
      currentHandler: 'designer',
      attachments: [
        {
          id: 'a8',
          name: 'SU7宣传海报.png',
          type: 'manuscript',
          url: '/attachments/placeholder8',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '张接单',
        },
      ],
      history: [
        {
          id: 'h11',
          timestamp: formatDate(yesterday),
          operator: '张接单',
          role: 'receiver',
          action: '创建订单',
          content: '客户担心图片放大后模糊，需要设计检查',
          orderId: 'o5',
        },
      ],
    },
    {
      id: 'o6',
      orderNo: 'AD20260614006',
      customerName: '优衣库',
      customerPhone: '13800138006',
      projectName: '夏季新品橱窗海报',
      createdAt: formatDate(twoDaysAgo),
      updatedAt: formatDate(yesterday),
      manuscriptReceived: true,
      manuscriptReceivedAt: formatDate(twoDaysAgo),
      manuscriptReceivedBy: '张接单',
      manuscriptContent: 'AI矢量文件，已转曲',
      manuscriptVersion: 1,
      originalDimension: { width: 150, height: 250, unit: 'cm' },
      reviewedDimension: { width: 150, height: 250, unit: 'cm' },
      dimensionReviewed: true,
      dimensionReviewedAt: formatDate(twoDaysAgo),
      dimensionReviewedBy: '李设计',
      dimensionReviewNote: '尺寸复核通过',
      dimensionModified: false,
      colorRequirement: '按品牌VI标准色',
      colorConfirmed: true,
      installTime: formatDate(yesterday),
      installAddress: '深圳罗湖万象城优衣库',
      installTimeModified: false,
      status: 'completed',
      currentHandler: 'installer',
      attachments: [
        {
          id: 'a9',
          name: '优衣库橱窗海报.ai',
          type: 'manuscript',
          url: '/attachments/placeholder9',
          uploadedAt: formatDate(twoDaysAgo),
          uploadedBy: '张接单',
        },
        {
          id: 'a10',
          name: '安装现场照片.jpg',
          type: 'photo',
          url: '/attachments/placeholder10',
          uploadedAt: formatDate(yesterday),
          uploadedBy: '王安装',
        },
      ],
      history: [
        {
          id: 'h12',
          timestamp: formatDate(twoDaysAgo),
          operator: '张接单',
          role: 'receiver',
          action: '创建订单',
          content: '夏季促销橱窗海报',
          orderId: 'o6',
        },
        {
          id: 'h13',
          timestamp: formatDate(twoDaysAgo),
          operator: '李设计',
          role: 'designer',
          action: '尺寸复核通过',
          content: '尺寸正确，材质：车贴哑膜',
          orderId: 'o6',
        },
        {
          id: 'h14',
          timestamp: formatDate(yesterday),
          operator: '王安装',
          role: 'installer',
          action: '安装完成',
          content: '已完成安装，客户现场确认签字',
          orderId: 'o6',
        },
      ],
    },
  ]
}
