import type { Claim, Handler, AppSettings } from '@/types';
import { generateId, generateCaseNumber } from './workflow';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();
const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();

export const mockHandlers: Handler[] = [
  {
    id: 'h1',
    name: '张明',
    role: 'supervisor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhang',
  },
  {
    id: 'h2',
    name: '李华',
    role: 'specialist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=li',
  },
  {
    id: 'h3',
    name: '王强',
    role: 'surveyor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wang',
  },
  {
    id: 'h4',
    name: '赵芳',
    role: 'specialist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhao',
  },
  {
    id: 'h5',
    name: '陈伟',
    role: 'supervisor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chen',
  },
];

export const mockSettings: AppSettings = {
  autoBackup: true,
  autoBackupDays: 7,
  theme: 'light',
  currentUserId: 'h1',
};

export const mockClaims: Claim[] = [
  {
    id: generateId(),
    caseNumber: generateCaseNumber(),
    policyNumber: 'POL-2024-001234',
    claimantName: '刘建国',
    accidentType: '车辆碰撞',
    accidentDescription: '2024年1月10日，被保险人驾驶小型轿车在北京市朝阳区建国路与前车发生追尾事故，造成车辆前部受损。',
    claimAmount: 25000,
    status: 'urged',
    currentHandlerId: 'h2',
    currentHandlerRole: 'specialist',
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(2),
    stuckReason: '理赔专员李华未及时处理退回修改要求',
    urgeCount: 2,
    workflowLogs: [
      {
        id: generateId(),
        claimId: '',
        actionType: 'create',
        fromStatus: null,
        toStatus: 'pending',
        handlerId: 'h4',
        handlerRole: 'specialist',
        reason: '案件立案，提交核赔审批',
        createdAt: daysAgo(5),
        durationHours: 48.5,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'reject',
        fromStatus: 'pending',
        toStatus: 'returned',
        handlerId: 'h1',
        handlerRole: 'supervisor',
        reason: '查勘报告中事故现场照片缺失，请补充车辆损伤细节照片，重新提交',
        createdAt: daysAgo(3),
        durationHours: 24.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'urge',
        fromStatus: 'returned',
        toStatus: 'urged',
        handlerId: 'h5',
        handlerRole: 'supervisor',
        reason: '案件已退回超过24小时未处理，请尽快补充材料',
        createdAt: daysAgo(2),
        durationHours: 12.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'urge',
        fromStatus: 'urged',
        toStatus: 'urged',
        handlerId: 'h1',
        handlerRole: 'supervisor',
        reason: '再次催办，请立即处理退回修改',
        createdAt: hoursAgo(2),
        durationHours: 0,
      },
    ],
    urgeRecords: [
      {
        id: generateId(),
        claimId: '',
        operatorId: 'h5',
        targetHandlerId: 'h2',
        message: '案件已退回超过24小时未处理，请尽快补充材料',
        createdAt: daysAgo(2),
      },
      {
        id: generateId(),
        claimId: '',
        operatorId: 'h1',
        targetHandlerId: 'h2',
        message: '再次催办，请立即处理退回修改',
        createdAt: hoursAgo(2),
      },
    ],
    supplementMaterials: [],
  },
  {
    id: generateId(),
    caseNumber: generateCaseNumber(),
    policyNumber: 'POL-2024-001235',
    claimantName: '孙秀英',
    accidentType: '意外医疗',
    accidentDescription: '被保险人在家中不慎摔倒，导致左腿骨折，住院治疗7天，产生医疗费用。',
    claimAmount: 18500,
    status: 'returned',
    currentHandlerId: 'h3',
    currentHandlerRole: 'surveyor',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
    stuckReason: '查勘员王强需补充住院费用明细和诊断证明原件扫描件',
    urgeCount: 1,
    workflowLogs: [
      {
        id: generateId(),
        claimId: '',
        actionType: 'create',
        fromStatus: null,
        toStatus: 'pending',
        handlerId: 'h2',
        handlerRole: 'specialist',
        reason: '案件立案，提交核赔审批',
        createdAt: daysAgo(7),
        durationHours: 72.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'supplement',
        fromStatus: 'pending',
        toStatus: 'supplement',
        handlerId: 'h1',
        handlerRole: 'supervisor',
        reason: '需要补充：1. 住院费用明细清单 2. 诊断证明原件扫描件',
        createdAt: daysAgo(4),
        durationHours: 48.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'material_ok',
        fromStatus: 'supplement',
        toStatus: 'pending',
        handlerId: 'h3',
        handlerRole: 'surveyor',
        reason: '已上传住院费用明细和诊断证明',
        createdAt: daysAgo(2),
        durationHours: 18.5,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'reject',
        fromStatus: 'pending',
        toStatus: 'returned',
        handlerId: 'h5',
        handlerRole: 'supervisor',
        reason: '费用明细中部分项目不属于保险责任范围，请重新核对并标注可赔付项目',
        createdAt: daysAgo(1),
        durationHours: 0,
      },
    ],
    urgeRecords: [
      {
        id: generateId(),
        claimId: '',
        operatorId: 'h1',
        targetHandlerId: 'h3',
        message: '请尽快处理补材料要求',
        createdAt: daysAgo(3),
      },
    ],
    supplementMaterials: [
      {
        id: generateId(),
        claimId: '',
        name: '住院费用明细清单',
        description: '需提供医院出具的详细费用清单',
        requesterId: 'h1',
        providerId: 'h3',
        status: 'provided',
        requestedAt: daysAgo(4),
        providedAt: daysAgo(2),
      },
      {
        id: generateId(),
        claimId: '',
        name: '诊断证明原件扫描件',
        description: '需医院盖章的诊断证明',
        requesterId: 'h1',
        providerId: 'h3',
        status: 'provided',
        requestedAt: daysAgo(4),
        providedAt: daysAgo(2),
      },
    ],
  },
  {
    id: generateId(),
    caseNumber: generateCaseNumber(),
    policyNumber: 'POL-2024-001236',
    claimantName: '周志强',
    accidentType: '家庭财产损失',
    accidentDescription: '因厨房水管爆裂，导致室内地板、家具被水浸泡，造成财产损失。',
    claimAmount: 32000,
    status: 'supplement',
    currentHandlerId: 'h3',
    currentHandlerRole: 'surveyor',
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(8),
    stuckReason: '等待查勘员上传现场定损照片和维修报价单',
    urgeCount: 0,
    workflowLogs: [
      {
        id: generateId(),
        claimId: '',
        actionType: 'create',
        fromStatus: null,
        toStatus: 'pending',
        handlerId: 'h4',
        handlerRole: 'specialist',
        reason: '案件立案，提交核赔审批',
        createdAt: daysAgo(3),
        durationHours: 36.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'supplement',
        fromStatus: 'pending',
        toStatus: 'supplement',
        handlerId: 'h5',
        handlerRole: 'supervisor',
        reason: '需要补充：1. 现场定损照片（含受损物品特写）2. 维修厂家报价单 3. 水管爆裂原因鉴定报告',
        createdAt: hoursAgo(8),
        durationHours: 0,
      },
    ],
    urgeRecords: [],
    supplementMaterials: [
      {
        id: generateId(),
        claimId: '',
        name: '现场定损照片',
        description: '需包含整体现场和受损物品特写照片',
        requesterId: 'h5',
        providerId: 'h3',
        status: 'pending',
        requestedAt: hoursAgo(8),
      },
      {
        id: generateId(),
        claimId: '',
        name: '维修厂家报价单',
        description: '需正规维修厂家出具的盖章报价单',
        requesterId: 'h5',
        providerId: 'h3',
        status: 'pending',
        requestedAt: hoursAgo(8),
      },
      {
        id: generateId(),
        claimId: '',
        name: '水管爆裂原因鉴定报告',
        description: '需明确爆裂原因是否属于保险责任',
        requesterId: 'h5',
        providerId: 'h3',
        status: 'pending',
        requestedAt: hoursAgo(8),
      },
    ],
  },
  {
    id: generateId(),
    caseNumber: generateCaseNumber(),
    policyNumber: 'POL-2024-001237',
    claimantName: '吴敏',
    accidentType: '车辆盗抢',
    accidentDescription: '被保险人停放于小区地下停车场的车辆被盗，已向公安机关报案。',
    claimAmount: 150000,
    status: 'calculating',
    currentHandlerId: 'h4',
    currentHandlerRole: 'specialist',
    createdAt: daysAgo(14),
    updatedAt: hoursAgo(4),
    stuckReason: '',
    urgeCount: 0,
    workflowLogs: [
      {
        id: generateId(),
        claimId: '',
        actionType: 'create',
        fromStatus: null,
        toStatus: 'pending',
        handlerId: 'h2',
        handlerRole: 'specialist',
        reason: '案件立案，提交核赔审批',
        createdAt: daysAgo(14),
        durationHours: 24.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'supplement',
        fromStatus: 'pending',
        toStatus: 'supplement',
        handlerId: 'h1',
        handlerRole: 'supervisor',
        reason: '需要补充公安机关立案回执、车辆钥匙、行驶证原件',
        createdAt: daysAgo(13),
        durationHours: 72.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'material_ok',
        fromStatus: 'supplement',
        toStatus: 'pending',
        handlerId: 'h3',
        handlerRole: 'surveyor',
        reason: '已补充所有要求的材料',
        createdAt: daysAgo(10),
        durationHours: 48.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'approve',
        fromStatus: 'pending',
        toStatus: 'approved',
        handlerId: 'h5',
        handlerRole: 'supervisor',
        reason: '材料齐全，事实清楚，同意进入赔付计算',
        createdAt: daysAgo(8),
        durationHours: 12.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'start_calc',
        fromStatus: 'approved',
        toStatus: 'calculating',
        handlerId: 'h4',
        handlerRole: 'specialist',
        reason: '开始赔付计算',
        createdAt: hoursAgo(4),
        durationHours: 0,
      },
    ],
    urgeRecords: [],
    supplementMaterials: [
      {
        id: generateId(),
        claimId: '',
        name: '公安机关立案回执',
        description: '报案回执单',
        requesterId: 'h1',
        providerId: 'h3',
        status: 'provided',
        requestedAt: daysAgo(13),
        providedAt: daysAgo(10),
      },
      {
        id: generateId(),
        claimId: '',
        name: '车辆钥匙',
        description: '全套车钥匙',
        requesterId: 'h1',
        providerId: 'h3',
        status: 'provided',
        requestedAt: daysAgo(13),
        providedAt: daysAgo(10),
      },
      {
        id: generateId(),
        claimId: '',
        name: '行驶证原件',
        description: '车辆行驶证',
        requesterId: 'h1',
        providerId: 'h3',
        status: 'provided',
        requestedAt: daysAgo(13),
        providedAt: daysAgo(10),
      },
    ],
    compensationCalc: {
      id: generateId(),
      claimId: '',
      handlerId: 'h4',
      items: [
        {
          name: '车辆损失',
          amount: 150000,
          formula: '投保金额 × (1 - 折旧率×使用月数)',
          remark: '车辆投保金额15万，使用12个月，月折旧率0.6%',
        },
        {
          name: '免赔金额',
          amount: -30000,
          formula: '损失金额 × 20%（绝对免赔率）',
          remark: '全车盗抢绝对免赔率20%',
        },
      ],
      totalAmount: 120000,
      formula: '车辆损失 - 免赔金额 = 150000 - 30000 = 120000',
      remark: '根据保险条款计算，最终赔付金额为12万元整',
      calculatedAt: '',
    },
  },
  {
    id: generateId(),
    caseNumber: generateCaseNumber(),
    policyNumber: 'POL-2024-001238',
    claimantName: '郑小平',
    accidentType: '意外伤害',
    accidentDescription: '被保险人在旅游途中意外摔伤，导致右臂骨折，门诊治疗。',
    claimAmount: 5600,
    status: 'pending',
    currentHandlerId: 'h1',
    currentHandlerRole: 'supervisor',
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
    stuckReason: '',
    urgeCount: 0,
    workflowLogs: [
      {
        id: generateId(),
        claimId: '',
        actionType: 'create',
        fromStatus: null,
        toStatus: 'pending',
        handlerId: 'h2',
        handlerRole: 'specialist',
        reason: '案件立案，提交核赔审批',
        createdAt: hoursAgo(6),
        durationHours: 0,
      },
    ],
    urgeRecords: [],
    supplementMaterials: [],
  },
  {
    id: generateId(),
    caseNumber: generateCaseNumber(),
    policyNumber: 'POL-2024-001239',
    claimantName: '钱大海',
    accidentType: '货物运输保险',
    accidentDescription: '运输途中发生交通事故，导致部分货物破损。',
    claimAmount: 85000,
    status: 'approved',
    currentHandlerId: 'h2',
    currentHandlerRole: 'specialist',
    createdAt: daysAgo(10),
    updatedAt: hoursAgo(1),
    stuckReason: '',
    urgeCount: 0,
    workflowLogs: [
      {
        id: generateId(),
        claimId: '',
        actionType: 'create',
        fromStatus: null,
        toStatus: 'pending',
        handlerId: 'h4',
        handlerRole: 'specialist',
        reason: '案件立案，提交核赔审批',
        createdAt: daysAgo(10),
        durationHours: 36.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'supplement',
        fromStatus: 'pending',
        toStatus: 'supplement',
        handlerId: 'h5',
        handlerRole: 'supervisor',
        reason: '需要补充货物价值证明、运输合同',
        createdAt: daysAgo(8),
        durationHours: 24.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'material_ok',
        fromStatus: 'supplement',
        toStatus: 'pending',
        handlerId: 'h3',
        handlerRole: 'surveyor',
        reason: '已补充货物发票和运输合同',
        createdAt: daysAgo(7),
        durationHours: 96.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'approve',
        fromStatus: 'pending',
        toStatus: 'approved',
        handlerId: 'h1',
        handlerRole: 'supervisor',
        reason: '材料齐全，定损合理，同意赔付',
        createdAt: hoursAgo(1),
        durationHours: 0,
      },
    ],
    urgeRecords: [],
    supplementMaterials: [
      {
        id: generateId(),
        claimId: '',
        name: '货物价值证明',
        description: '货物采购发票',
        requesterId: 'h5',
        providerId: 'h3',
        status: 'provided',
        requestedAt: daysAgo(8),
        providedAt: daysAgo(7),
      },
      {
        id: generateId(),
        claimId: '',
        name: '运输合同',
        description: '货物运输协议',
        requesterId: 'h5',
        providerId: 'h3',
        status: 'provided',
        requestedAt: daysAgo(8),
        providedAt: daysAgo(7),
      },
    ],
  },
  {
    id: generateId(),
    caseNumber: generateCaseNumber(),
    policyNumber: 'POL-2024-001240',
    claimantName: '冯丽娟',
    accidentType: '疾病医疗',
    accidentDescription: '被保险人因急性阑尾炎住院手术治疗。',
    claimAmount: 12800,
    status: 'completed',
    currentHandlerId: 'h4',
    currentHandlerRole: 'specialist',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
    stuckReason: '',
    urgeCount: 0,
    workflowLogs: [
      {
        id: generateId(),
        claimId: '',
        actionType: 'create',
        fromStatus: null,
        toStatus: 'pending',
        handlerId: 'h2',
        handlerRole: 'specialist',
        reason: '案件立案，提交核赔审批',
        createdAt: daysAgo(20),
        durationHours: 24.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'approve',
        fromStatus: 'pending',
        toStatus: 'approved',
        handlerId: 'h5',
        handlerRole: 'supervisor',
        reason: '材料齐全，属于保险责任',
        createdAt: daysAgo(19),
        durationHours: 12.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'start_calc',
        fromStatus: 'approved',
        toStatus: 'calculating',
        handlerId: 'h4',
        handlerRole: 'specialist',
        reason: '开始赔付计算',
        createdAt: daysAgo(18),
        durationHours: 6.0,
      },
      {
        id: generateId(),
        claimId: '',
        actionType: 'finish_calc',
        fromStatus: 'calculating',
        toStatus: 'completed',
        handlerId: 'h4',
        handlerRole: 'specialist',
        reason: '赔付计算完成',
        createdAt: daysAgo(2),
        durationHours: 0,
      },
    ],
    urgeRecords: [],
    supplementMaterials: [],
    compensationCalc: {
      id: generateId(),
      claimId: '',
      handlerId: 'h4',
      items: [
        {
          name: '住院医疗费用',
          amount: 12800,
          formula: '发票总金额',
          remark: '住院费用发票总额12800元',
        },
        {
          name: '社保报销',
          amount: -5200,
          formula: '医保统筹支付部分',
          remark: '医保已报销5200元',
        },
        {
          name: '免赔额',
          amount: -500,
          formula: '绝对免赔额',
          remark: '保单约定绝对免赔额500元',
        },
        {
          name: '赔付比例',
          amount: 0,
          formula: '剩余部分 × 80%',
          remark: '(12800-5200-500) × 80% = 5680',
        },
      ],
      totalAmount: 5680,
      formula: '(住院费用 - 社保报销 - 免赔额) × 赔付比例 = (12800-5200-500) × 80% = 5680',
      remark: '按照保险条款约定，最终赔付金额为5680元',
      calculatedAt: daysAgo(2),
    },
  },
];

mockClaims.forEach(claim => {
  claim.workflowLogs.forEach(log => {
    log.claimId = claim.id;
  });
  claim.urgeRecords.forEach(record => {
    record.claimId = claim.id;
  });
  claim.supplementMaterials.forEach(mat => {
    mat.claimId = claim.id;
  });
  if (claim.compensationCalc) {
    claim.compensationCalc.claimId = claim.id;
  }
});
