# Generated by Django 4.2.30 on 2026-06-15 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('quotation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒绝'), ('signed', '已签约')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_no', models.CharField(max_length=50, unique=True)),
                ('survey_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('building_type', models.CharField(max_length=50)),
                ('floor_count', models.IntegerField(blank=True, null=True)),
                ('wall_material', models.CharField(blank=True, max_length=50, null=True)),
                ('power_supply', models.BooleanField(default=False)),
                ('installation_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('access_condition', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待勘测'), ('completed', '已完成'), ('reviewing', '审核中')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='parts.customer')),
                ('surveyor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('sign', '标识牌'), ('light_box', '灯箱'), ('letter', '发光字'), ('banner', '横幅'), ('other', '其他')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('material_requirements', models.TextField(blank=True, null=True)),
                ('installation_requirements', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parts.sitesurvey')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.CharField(blank=True, max_length=200, null=True)),
                ('installation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parts.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='parts.sitesurvey'),
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('survey_create', '创建勘测'), ('survey_update', '更新勘测'), ('survey_complete', '完成勘测'), ('quotation_create', '创建报价'), ('quotation_update', '更新报价'), ('quotation_submit', '提交报价'), ('quotation_approve', '批准报价'), ('quotation_reject', '拒绝报价'), ('attachment_upload', '上传附件')], max_length=30)),
                ('description', models.TextField()),
                ('changed_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parts.quotation')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parts.sitesurvey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('design', '设计图'), ('production', '生产单'), ('survey', '勘测报告'), ('other', '其他')], max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='parts.quotation')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='parts.sitesurvey')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
