# Generated by Django 4.2.30 on 2026-06-15 02:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('manager', '维保主管'), ('technician', '现场技师'), ('warehouse', '仓管')], default='technician', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('equipment_model', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', '正常运行'), ('warning', '待保养'), ('downtime', '停机故障')], default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PartsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=50, unique=True)),
                ('part_name', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(default='件', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('assigned', '已分派'), ('warehouse_pending', '待出库'), ('shipped', '已出库'), ('verified', '已核销'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20)),
                ('reason', models.TextField()),
                ('fault_description', models.TextField(blank=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('downtime_start', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.customerequipment')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_no', models.CharField(max_length=50, unique=True)),
                ('verification_date', models.DateTimeField()),
                ('actual_used_quantities', models.JSONField(default=dict)),
                ('remaining_parts', models.TextField(blank=True)),
                ('problem_description', models.TextField(blank=True)),
                ('is_qualified', models.BooleanField(default=True)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='parts.partsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PartsRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('create', '创建'), ('approve', '审核通过'), ('reject', '审核拒绝'), ('assign', '分派'), ('warehouse_check', '仓库确认'), ('ship', '出库'), ('verify', '核销'), ('remark', '备注')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='parts.partsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PartsRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField()),
                ('issued_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.partsinventory')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parts.partsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_no', models.CharField(max_length=50, unique=True)),
                ('outbound_date', models.DateTimeField()),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('tracking_no', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_records', to='parts.partsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parts.outboundrecord')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.partsinventory')),
            ],
        ),
    ]
