# Generated by Django 4.2.30 on 2026-06-09 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', '草稿(治疗师填写评估)'), ('pending_assign', '待分配(前台分配器械)'), ('assigned', '已分配(待确认排班)'), ('in_use', '使用中'), ('pending_review', '待审核(主任审核)'), ('completed', '已完成'), ('exception', '异常')], db_index=True, default='draft', max_length=16)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time_start', models.TimeField(blank=True, null=True)),
                ('scheduled_time_end', models.TimeField(blank=True, null=True)),
                ('exception_reason', models.TextField(blank=True, default='')),
                ('return_reason', models.TextField(blank=True, default='')),
                ('return_target_status', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointment_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('offline', '下线')], default='available', max_length=16)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_record',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(blank=True, default='', max_length=8)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_usage', models.TextField(blank=True, default='')),
                ('patient_feedback', models.TextField(blank=True, default='')),
                ('abnormal', models.BooleanField(default=False)),
                ('abnormal_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_records', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='equipment_booking.appointmentorder')),
            ],
            options={
                'db_table': 'usage_record',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motor_function', models.TextField(blank=True, default='')),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('range_of_motion', models.TextField(blank=True, default='')),
                ('treatment_goal', models.TextField(blank=True, default='')),
                ('equipment_requirement', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='equipment_booking.appointmentorder')),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
        migrations.AddField(
            model_name='appointmentorder',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='equipment_booking.equipment'),
        ),
        migrations.AddField(
            model_name='appointmentorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='equipment_booking.patient'),
        ),
        migrations.AddField(
            model_name='appointmentorder',
            name='receptionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptionist_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentorder',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentorder',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapist_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('warning', '预警'), ('error', '异常'), ('info', '通知')], default='warning', max_length=8)),
                ('message', models.TextField()),
                ('handled', models.CharField(choices=[('pending', '待处理'), ('returned', '已退回'), ('dismissed', '已忽略'), ('resolved', '已解决')], default='pending', max_length=10)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alerts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='equipment_booking.appointmentorder')),
            ],
            options={
                'db_table': 'alert_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
