# Generated by Django 4.2.30 on 2026-06-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_booking', '0002_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentorder',
            name='previous_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
