const EventEmitter = require('events');

const bus = new EventEmitter();

bus.CONTAINER_ENTRY_MODIFIED = 'CONTAINER_ENTRY_MODIFIED';
bus.SLOT_ALLOCATED = 'SLOT_ALLOCATED';
bus.SLOT_RELEASED = 'SLOT_RELEASED';
bus.CONTAINER_STATUS_CHANGED = 'CONTAINER_STATUS_CHANGED';
bus.INSPECTION_MISSED = 'INSPECTION_MISSED';
bus.FEE_DISPUTED = 'FEE_DISPUTED';

module.exports = bus;
