# Generated by Django 4.2.30 on 2026-06-07 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64, verbose_name='客人姓名')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='客人电话')),
                ('item_description', models.TextField(verbose_name='遗失/损坏物品描述')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预估价值')),
                ('compensation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='赔付金额')),
                ('status', models.CharField(choices=[('pending_review', '待审核'), ('reviewed', '已审核'), ('paid', '已支付'), ('rejected', '已拒绝')], default='pending_review', max_length=32, verbose_name='状态')),
                ('proposed_at', models.DateTimeField(auto_now_add=True, verbose_name='提出时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_method', models.CharField(blank=True, max_length=32, verbose_name='支付方式')),
                ('payment_voucher', models.CharField(blank=True, max_length=256, verbose_name='支付凭证号')),
                ('customer_signature', models.CharField(blank=True, max_length=64, verbose_name='客人签收')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签收时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '赔付记录',
                'verbose_name_plural': '赔付记录',
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_no', models.CharField(max_length=32, unique=True, verbose_name='柜号')),
                ('status', models.CharField(choices=[('available', '空闲'), ('occupied', '占用'), ('damaged', '损坏'), ('maintenance', '维护中')], default='available', max_length=32, verbose_name='状态')),
                ('wristband_code', models.CharField(blank=True, max_length=64, verbose_name='绑定手牌')),
                ('customer_name', models.CharField(blank=True, max_length=64, verbose_name='客人姓名')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='入柜时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '储物柜',
                'verbose_name_plural': '储物柜',
                'ordering': ['area', 'locker_no'],
            },
        ),
        migrations.CreateModel(
            name='LockerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='区域名称')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '储物柜区域',
                'verbose_name_plural': '储物柜区域',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reception', '前台'), ('floor_supervisor', '楼层主管'), ('finance', '财务'), ('admin', '管理员')], max_length=32, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('employee_id', models.CharField(max_length=32, unique=True, verbose_name='工号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='技师姓名')),
                ('employee_id', models.CharField(max_length=32, unique=True, verbose_name='工号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '技师',
                'verbose_name_plural': '技师',
            },
        ),
        migrations.CreateModel(
            name='Wristband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='手牌编号')),
                ('status', models.CharField(choices=[('idle', '空闲'), ('issued', '已发放'), ('lost', '遗失'), ('damaged', '损坏')], default='idle', max_length=32, verbose_name='状态')),
                ('customer_name', models.CharField(blank=True, max_length=64, verbose_name='客人姓名')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='客人电话')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bound_locker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wristband', to='locker_system.locker', verbose_name='绑定储物柜')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_wristbands', to='locker_system.staffprofile', verbose_name='发放人')),
            ],
            options={
                'verbose_name': '手牌',
                'verbose_name_plural': '手牌',
            },
        ),
        migrations.CreateModel(
            name='LockerAbnormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormal_type', models.CharField(choices=[('cannot_open', '无法开门'), ('wrong_item', '物品错放'), ('item_missing', '物品遗失'), ('locker_damage', '柜体损坏'), ('wristband_lost', '手牌遗失'), ('customer_complaint', '客人投诉'), ('other', '其他')], max_length=32, verbose_name='异常类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('need_compensation', '待赔付'), ('resolved', '已解决'), ('returned', '已退回')], default='pending', max_length=32, verbose_name='状态')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('customer_name', models.CharField(blank=True, max_length=64, verbose_name='客人姓名')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='客人电话')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='派单时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('process_result', models.TextField(blank=True, verbose_name='处理结果')),
                ('return_reason', models.TextField(blank=True, verbose_name='退回原因')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='退回时间')),
                ('expected_deadline', models.DateTimeField(blank=True, null=True, verbose_name='期望处理时限')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_abnormals', to='locker_system.staffprofile', verbose_name='处理人(楼层主管)')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abnormal_records', to='locker_system.locker', verbose_name='储物柜')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_abnormals', to='locker_system.staffprofile', verbose_name='处理人')),
                ('related_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_records', to='locker_system.technician', verbose_name='涉及技师')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_abnormals', to='locker_system.staffprofile', verbose_name='登记人(前台)')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_abnormals', to='locker_system.staffprofile', verbose_name='退回人')),
                ('wristband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormal_records', to='locker_system.wristband', verbose_name='相关手牌')),
            ],
            options={
                'verbose_name': '储物柜异常记录',
                'verbose_name_plural': '储物柜异常记录',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddField(
            model_name='locker',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='locker_system.lockerarea', verbose_name='所属区域'),
        ),
        migrations.CreateModel(
            name='CompensationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='操作动作')),
                ('detail', models.TextField(verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='locker_system.compensation', verbose_name='赔付记录')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_actions', to='locker_system.staffprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '赔付处理进度',
                'verbose_name_plural': '赔付处理进度',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='compensation',
            name='abnormal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compensation', to='locker_system.lockerabnormal', verbose_name='关联异常'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_compensations', to='locker_system.staffprofile', verbose_name='支付人(财务)'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_compensations', to='locker_system.staffprofile', verbose_name='提出人(楼层主管)'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compensations', to='locker_system.staffprofile', verbose_name='审核人(财务)'),
        ),
        migrations.CreateModel(
            name='AbnormalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='操作动作')),
                ('detail', models.TextField(verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('abnormal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='locker_system.lockerabnormal', verbose_name='异常记录')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='locker_system.staffprofile', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '异常处理进度',
                'verbose_name_plural': '异常处理进度',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='排班日期')),
                ('shift_type', models.CharField(max_length=32, verbose_name='班次')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('assigned_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='locker_system.lockerarea', verbose_name='负责区域')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='locker_system.technician', verbose_name='技师')),
            ],
            options={
                'verbose_name': '技师排班',
                'verbose_name_plural': '技师排班',
                'unique_together': {('technician', 'shift_date')},
            },
        ),
    ]
