from enum import IntEnum


class ErrorCode(IntEnum):
    SUCCESS = 0

    LOCKER_NOT_FOUND = 10001
    LOCKER_ALREADY_OCCUPIED = 10002
    LOCKER_NOT_OCCUPIED = 10003
    LOCKER_DAMAGED = 10004

    WRISTBAND_NOT_FOUND = 10101
    WRISTBAND_ALREADY_ISSUED = 10102
    WRISTBAND_NOT_ISSUED = 10103
    WRISTBAND_MISMATCH = 10104

    ABNORMAL_NOT_FOUND = 10201
    ABNORMAL_INVALID_STATUS = 10202
    ABNORMAL_ALREADY_PROCESSED = 10203
    ABNORMAL_NO_PERMISSION = 10204

    COMPENSATION_NOT_FOUND = 10301
    COMPENSATION_INVALID_STATUS = 10302
    COMPENSATION_AMOUNT_MISMATCH = 10303
    COMPENSATION_ALREADY_PAID = 10304

    PARAM_ERROR = 10400
    PERMISSION_DENIED = 10403
    RESOURCE_NOT_FOUND = 10404
    INTERNAL_ERROR = 10500


ERROR_MESSAGES = {
    ErrorCode.SUCCESS: "操作成功",
    ErrorCode.LOCKER_NOT_FOUND: "储物柜不存在",
    ErrorCode.LOCKER_ALREADY_OCCUPIED: "储物柜已被占用",
    ErrorCode.LOCKER_NOT_OCCUPIED: "储物柜未被占用",
    ErrorCode.LOCKER_DAMAGED: "储物柜已损坏",
    ErrorCode.WRISTBAND_NOT_FOUND: "手牌不存在",
    ErrorCode.WRISTBAND_ALREADY_ISSUED: "手牌已发放",
    ErrorCode.WRISTBAND_NOT_ISSUED: "手牌未发放",
    ErrorCode.WRISTBAND_MISMATCH: "手牌与储物柜不匹配",
    ErrorCode.ABNORMAL_NOT_FOUND: "异常记录不存在",
    ErrorCode.ABNORMAL_INVALID_STATUS: "异常状态无效",
    ErrorCode.ABNORMAL_ALREADY_PROCESSED: "异常已处理",
    ErrorCode.ABNORMAL_NO_PERMISSION: "无权限处理此异常",
    ErrorCode.COMPENSATION_NOT_FOUND: "赔付记录不存在",
    ErrorCode.COMPENSATION_INVALID_STATUS: "赔付状态无效",
    ErrorCode.COMPENSATION_AMOUNT_MISMATCH: "赔付金额不匹配",
    ErrorCode.COMPENSATION_ALREADY_PAID: "赔付已支付",
    ErrorCode.PARAM_ERROR: "参数错误",
    ErrorCode.PERMISSION_DENIED: "权限不足",
    ErrorCode.RESOURCE_NOT_FOUND: "资源不存在",
    ErrorCode.INTERNAL_ERROR: "系统内部错误",
}
