# Generated by Django 6.0.6 on 2026-06-06 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age_months', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', '公'), ('female', '母')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('rescued', '已救助'), ('in_treatment', '治疗中'), ('fostered', '寄养中'), ('available', '待领养'), ('adoption_processing', '领养流程中'), ('adopted', '已领养'), ('returned', '被退回'), ('deceased', '死亡')], default='rescued', max_length=50)),
                ('rescue_date', models.DateField()),
                ('rescue_location', models.CharField(max_length=200)),
                ('health_condition', models.TextField(blank=True)),
                ('medical_records', models.TextField(blank=True)),
                ('medical_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foster_family', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'animal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=200)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'idempotency_key',
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('applicant_id_card', models.CharField(blank=True, max_length=50)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('housing_type', models.CharField(choices=[('apartment', '公寓'), ('house', '独栋房屋'), ('villa', '别墅'), ('other', '其他')], max_length=50)),
                ('has_pet_experience', models.BooleanField(default=False)),
                ('current_pets', models.TextField(blank=True)),
                ('family_members', models.IntegerField(default=1)),
                ('has_children', models.BooleanField(default=False)),
                ('work_situation', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.CharField(blank=True, max_length=50)),
                ('reason_for_adoption', models.TextField()),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('materials_missing', '材料缺失'), ('materials_received', '材料已收'), ('pre_review_pass', '初审通过'), ('pre_review_reject', '初审不通过'), ('home_visit_scheduled', '家访已安排'), ('home_visit_completed', '家访完成'), ('home_visit_pass', '家访通过'), ('home_visit_reject', '家访不通过'), ('recheck_required', '需复核'), ('recheck_pass', '复核通过'), ('recheck_reject', '复核不通过'), ('approved', '审核通过'), ('rejected', '已拒绝'), ('adoption_completed', '领养完成'), ('cancelled', '已取消'), ('timeout', '已超时')], default='submitted', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to='adoption.animal')),
            ],
            options={
                'db_table': 'adoption_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('volunteer', '救助志愿者'), ('vet', '兽医'), ('adoption_auditor', '领养审核员'), ('home_visitor', '家访员'), ('admin', '管理员')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records_list', to='adoption.animal')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adoption.staff')),
            ],
            options={
                'db_table': 'medical_record',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeVisitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '不通过'), ('pending', '待确认')], default='pending', max_length=20)),
                ('environment_score', models.IntegerField(blank=True, null=True)),
                ('experience_score', models.IntegerField(blank=True, null=True)),
                ('attitude_score', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('environment_description', models.TextField(blank=True)),
                ('family_communication', models.TextField(blank=True)),
                ('pet_knowledge', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('recheck_required', models.BooleanField(default=False)),
                ('recheck_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_visit', to='adoption.adoptionapplication')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adoption.staff')),
            ],
            options={
                'db_table': 'home_visit_record',
            },
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_up_date', models.DateField()),
                ('follow_up_type', models.CharField(choices=[('week1', '一周回访'), ('month1', '一月回访'), ('month3', '三月回访'), ('month6', '半年回访'), ('year1', '一年回访'), ('other', '其他')], max_length=50)),
                ('animal_health', models.TextField(blank=True)),
                ('adaptation', models.TextField(blank=True)),
                ('problems', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('next_follow_up_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='adoption.adoptionapplication')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adoption.staff')),
            ],
            options={
                'db_table': 'follow_up_record',
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('status_from', models.CharField(blank=True, choices=[('submitted', '已提交'), ('materials_missing', '材料缺失'), ('materials_received', '材料已收'), ('pre_review_pass', '初审通过'), ('pre_review_reject', '初审不通过'), ('home_visit_scheduled', '家访已安排'), ('home_visit_completed', '家访完成'), ('home_visit_pass', '家访通过'), ('home_visit_reject', '家访不通过'), ('recheck_required', '需复核'), ('recheck_pass', '复核通过'), ('recheck_reject', '复核不通过'), ('approved', '审核通过'), ('rejected', '已拒绝'), ('adoption_completed', '领养完成'), ('cancelled', '已取消'), ('timeout', '已超时')], max_length=50)),
                ('status_to', models.CharField(choices=[('submitted', '已提交'), ('materials_missing', '材料缺失'), ('materials_received', '材料已收'), ('pre_review_pass', '初审通过'), ('pre_review_reject', '初审不通过'), ('home_visit_scheduled', '家访已安排'), ('home_visit_completed', '家访完成'), ('home_visit_pass', '家访通过'), ('home_visit_reject', '家访不通过'), ('recheck_required', '需复核'), ('recheck_pass', '复核通过'), ('recheck_reject', '复核不通过'), ('approved', '审核通过'), ('rejected', '已拒绝'), ('adoption_completed', '领养完成'), ('cancelled', '已取消'), ('timeout', '已超时')], max_length=50)),
                ('operator_role', models.CharField(choices=[('volunteer', '救助志愿者'), ('vet', '兽医'), ('adoption_auditor', '领养审核员'), ('home_visitor', '家访员'), ('admin', '管理员')], max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='adoption.adoptionapplication')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adoption.staff')),
            ],
            options={
                'db_table': 'application_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='rescue_volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescued_animals', to='adoption.staff'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treated_animals', to='adoption.staff'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='current_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_applications', to='adoption.staff'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='home_visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visited_applications', to='adoption.staff'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pre_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_reviewed_applications', to='adoption.staff'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='rechecker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechecked_applications', to='adoption.staff'),
        ),
    ]
