# Generated by Django 6.0.6 on 2026-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuprecord',
            name='gap_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followuprecord',
            name='is_gap',
            field=models.BooleanField(default=False),
        ),
    ]
