// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/6/5 16:34:05
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/plugins/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/composables/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/utils/**/*.{js,ts,mjs}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/liu/Documents/private/model-test/trae-20260601-2/ski-patrol/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;