export enum IntakeBlockReason {
  NONE = 'NONE',
  AWAITING_CUSTOMER_CLARIFICATION = 'AWAITING_CUSTOMER_CLARIFICATION',
  AWAITING_CS_FOLLOWUP = 'AWAITING_CS_FOLLOWUP',
  NO_HOUSEKEEPER_AVAILABLE = 'NO_HOUSEKEEPER_AVAILABLE',
  AWAITING_CUSTOMER_CONFIRM = 'AWAITING_CUSTOMER_CONFIRM',
  AWAITING_HOUSEKEEPER_CONFIRM = 'AWAITING_HOUSEKEEPER_CONFIRM',
  CUSTOMER_UNREACHABLE = 'CUSTOMER_UNREACHABLE',
  HOUSEKEEPER_UNREACHABLE = 'HOUSEKEEPER_UNREACHABLE',
  AWAITING_QUALITY_REVIEW = 'AWAITING_QUALITY_REVIEW',
}
