export enum IntakeStatus {
  CREATED = 'CREATED',
  CLARIFYING = 'CLARIFYING',
  CLARIFIED = 'CLARIFIED',
  MATCHING = 'MATCHING',
  MATCHED = 'MATCHED',
  CONFIRMED = 'CONFIRMED',
  SERVICE_STARTED = 'SERVICE_STARTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
