export enum MatchingFailReason {
  NONE = 'NONE',
  SKILL_MISMATCH = 'SKILL_MISMATCH',
  TIME_UNAVAILABLE = 'TIME_UNAVAILABLE',
  AREA_NOT_COVERED = 'AREA_NOT_COVERED',
  SALARY_BELOW_EXPECTATION = 'SALARY_BELOW_EXPECTATION',
  HOUSEKEEPER_ALREADY_ASSIGNED = 'HOUSEKEEPER_ALREADY_ASSIGNED',
  CUSTOMER_REJECTED_PREVIOUS = 'CUSTOMER_REJECTED_PREVIOUS',
  HOUSEKEEPER_HAS_NEGATIVE_REVIEW = 'HOUSEKEEPER_HAS_NEGATIVE_REVIEW',
  SERVICE_SCOPE_UNCLEAR = 'SERVICE_SCOPE_UNCLEAR',
  EXPERIENCE_INSUFFICIENT = 'EXPERIENCE_INSUFFICIENT',
  NO_MATCH_AFTER_N_ROUNDS = 'NO_MATCH_AFTER_N_ROUNDS',
}
