export enum MatchingStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  RECOMMENDED = 'RECOMMENDED',
  ACCEPTED = 'ACCEPTED',
  REJECTED_BY_CUSTOMER = 'REJECTED_BY_CUSTOMER',
  REJECTED_BY_HOUSEKEEPER = 'REJECTED_BY_HOUSEKEEPER',
  TIMEOUT = 'TIMEOUT',
  CANCELLED = 'CANCELLED',
}
