export enum OrderStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_SERVICE = 'IN_SERVICE',
  COMPLETED = 'COMPLETED',
  NO_SHOW_BY_HOUSEKEEPER = 'NO_SHOW_BY_HOUSEKEEPER',
  NO_SHOW_BY_CUSTOMER = 'NO_SHOW_BY_CUSTOMER',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}
