export enum ReviewStatus {
  SUBMITTED = 'SUBMITTED',
  AWAITING_QUALITY_ASSIGN = 'AWAITING_QUALITY_ASSIGN',
  QUALITY_FOLLOWING = 'QUALITY_FOLLOWING',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
  CLOSED_WITHOUT_RESOLUTION = 'CLOSED_WITHOUT_RESOLUTION',
}
